import test from 'node:test';import assert from 'node:assert/strict';
import {Game} from '../src/simulation.ts';
import {COLOSSUS,summonColossus,updateColossus,colossusVolley,colossusEnemy} from '../src/ashen-colossus.ts';
import {spawnCourtHunt,chooseCourtUpgrade,courtMission,COURT_TEST_RULES} from '../src/stage-two.ts';
import {insideCourt} from '../src/court-map.ts';import {reaperTarget} from '../src/reaper.ts';
import {encodeRun,decodeRun,validateRun} from '../src/run-code.ts';import {resultText} from '../src/results.ts';
const input={x:0,y:0,aimX:0,aimY:0,aiming:false};
function eligible(id='devourer',time=420){const g=new Game(77,{monsterId:id},1);g.time=time;g.wave=Math.floor(time/30)+1;const spawn=g.spawn;g.spawn=function(kind,...a){return kind==='titan'?undefined:spawn.call(this,kind,...a);};for(let n=0;n<8;n++){assert.ok(spawnCourtHunt(g));const e=g.enemies.find(e=>e.active&&e.court?.role==='captain');g.player.x=e.x-70;g.player.y=e.y;g.damage(e,1e8,'execute');assert.ok(chooseCourtUpgrade(g,['power','power','power','recharge','recharge','recharge','haste','haste'][n]));}g.spawn=spawn;g.court.colossus.retryAt=0;g.player.x=g.player.y=0;g.rebuildGrid();return g;}
const record=g=>({version:4,rules:COURT_TEST_RULES,phase:1,...g.identity,seed:g.seed,duration:Math.ceil(g.time),score:g.score.dominance,kills:g.score.kills,wave:Math.floor(g.time/30)+1,elites:g.score.elites,titans:g.score.titans,multi:g.score.largestMulti,peak:g.score.peak,feats:{...g.score.feats},ended:'2026-10-04T18:00:00Z',reason:g.court.cleared?'cleared':'retired',release:g.release,build:'0123456789abcdef',court:{...g.court.stats},mission:courtMission(g),testing:true});
test('colossus is Stage 2 only, arrives once after eight captains before 9:00, on walkable ground',()=>{for(const time of [0,539.99]){const g=eligible('titan',time);assert.ok(summonColossus(g));const e=colossusEnemy(g);assert.ok(insideCourt(e.x,e.y,62));assert.ok(Math.hypot(e.x,e.y)>180);assert.equal(e.maxHp,COLOSSUS.hp);assert.equal(g.court.colossus.expiresAt,time+120);assert.equal(summonColossus(g),false);}for(const time of [540,720,1200])assert.equal(summonColossus(eligible('reaper',time)),false);const g=eligible();g.court.stats.captains=7;assert.equal(summonColossus(g),false);const s1=new Game(77,{},0);assert.equal(summonColossus(s1),false);});
test('volleys place several small fixed zones with readable warnings, staggered impacts and open gaps',()=>{const g=eligible();summonColossus(g);const e=colossusEnemy(g);for(let i=0;i<3;i++){g.court.colossus.zones.length=0;colossusVolley(g,e);const zones=g.court.colossus.zones;assert.ok(zones.length>=3);assert.ok(zones.every(z=>z.radius===65&&z.impactAt-g.time>=1.25));assert.ok(zones.every((z,n)=>n===0||z.impactAt>zones[n-1].impactAt));const positions=zones.map(z=>[z.x,z.y]);g.player.x+=40;g.player.y+=50;g.time+=.5;updateColossus(g);assert.deepEqual(zones.map(z=>[z.x,z.y]),positions);}});
test('warning is harmless, actual impact hurts; leaving its footprint avoids damage and expiry clears hazards',()=>{const g=eligible();summonColossus(g);colossusVolley(g,colossusEnemy(g));const z=g.court.colossus.zones[0];g.player.x=z.x;g.player.y=z.y;g.player.invuln=0;const hp=g.player.hp;g.time=z.impactAt-.01;updateColossus(g);assert.equal(g.player.hp,hp);g.time=z.impactAt;updateColossus(g);assert.ok(g.player.hp<hp);const health=g.player.hp;g.player.y-=110;g.player.invuln=0;g.time+=.45;updateColossus(g);assert.equal(g.player.hp,health);const score=g.score.dominance;g.time=g.court.colossus.expiresAt;updateColossus(g);assert.equal(g.court.colossus.status,'expired');assert.equal(g.court.colossus.zones.length,0);assert.equal(colossusEnemy(g),undefined);assert.equal(g.score.dominance,score);assert.equal(summonColossus(g),false);});
test('colossus kills reward a fixed 1.2M once, outside the minion budget, roundtrip MM4; all fabricated rewards rejected',async()=>{for(const id of ['devourer','titan','sovereign','calamity','overlord','reaper']){const g=eligible(id);assert.ok(summonColossus(g));const e=colossusEnemy(g);g.score.award(1e9);const before=g.score.dominance,combat=g.court.scoring.combat;g.time+=10;assert.ok(g.damage(e,1e9,'direct'));assert.equal(g.score.dominance-before,COLOSSUS.reward);assert.equal(g.court.scoring.combat,combat);assert.equal(g.court.stats.captains,8);assert.equal(g.court.colossus.status,'defeated');assert.equal(g.score.titans,1);assert.equal(g.damage(e,1e9,'direct'),false);const r=record(g),decoded=await decodeRun(await encodeRun(r));assert.deepEqual(decoded.mission.colossus,r.mission.colossus);assert.match(resultText(r),/Ashen Colossus slain · \+1,200,000/);for(const bad of [{reward:1200001},{spawnedAt:540},{defeatedAt:600},{spawnedAt:435},{reward:0},{evil:1}])assert.throws(()=>validateRun({...r,mission:{...r.mission,colossus:{...r.mission.colossus,...bad}}}));assert.throws(()=>validateRun({...r,rules:'2026.10-v27-court-test'}));}});
test('no late-hit reward, no forced boss objective, captain ten still finishes the match',()=>{const g=eligible();summonColossus(g);const e=colossusEnemy(g);g.time=e.colossus.expiresAt;assert.equal(g.damage(e,1e9,'direct'),false);updateColossus(g);validateRun(record(g));const skip=eligible();summonColossus(skip);const boss=colossusEnemy(skip);for(let n=0;n<2;n++){spawnCourtHunt(skip);skip.damage(skip.enemies.find(e=>e.active&&e.court?.role==='captain'),1e9,'execute');if(n===0)chooseCourtUpgrade(skip,'haste');}assert.ok(skip.ended&&skip.court.cleared);assert.equal(boss.active,false);assert.equal(skip.court.colossus.status,'departed');assert.equal(skip.court.colossus.zones.length,0);assert.equal(skip.score.titans,0);validateRun(record(skip));});
test('automatic Reaper attacks prefer the colossus to captains; volleys cannot grow without bound',()=>{const g=eligible('reaper');summonColossus(g);const e=colossusEnemy(g),capt=g.spawn('brute');Object.assign(capt,{x:100,y:0,court:{role:'captain',guard:0}});g.rebuildGrid();assert.equal(reaperTarget(g,700,true),e);for(let i=0;i<20;i++)colossusVolley(g,e);assert.ok(g.court.colossus.zones.length<=COLOSSUS.maxZones);});
test('boon deliberation freezes the colossus clock and warnings',()=>{const g=eligible();summonColossus(g);colossusVolley(g,colossusEnemy(g));g.court.pending=1;const time=g.time,zones=JSON.stringify(g.court.colossus.zones);for(let i=0;i<600;i++)g.update(1/60,input);assert.equal(g.time,time);assert.equal(JSON.stringify(g.court.colossus.zones),zones);});

test('only the colossus has a weakness to Titan heavy impacts; unrelated damage stays unchanged',()=>{const g=eligible('titan');summonColossus(g);const e=colossusEnemy(g),hp=e.hp;g.damage(e,100,'shockwave');assert.equal(hp-e.hp,100*COLOSSUS.titanImpact);const before=e.hp;g.damage(e,100,'direct');assert.equal(before-e.hp,100);const ordinary=g.spawn('titan'),health=ordinary.hp;g.damage(ordinary,100,'shockwave');assert.equal(health-ordinary.hp,100);const dev=eligible();summonColossus(dev);const foe=colossusEnemy(dev),initial=foe.hp;dev.damage(foe,100,'shockwave');assert.equal(initial-foe.hp,100);});

test('a fatal eruption and a manually ended hunt dismiss the boss and all remaining hazards',()=>{for(const manual of [false,true]){const g=eligible();summonColossus(g);colossusVolley(g,colossusEnemy(g));if(manual){g.ended=true;courtMission(g);}else{const z=g.court.colossus.zones[0];g.player.x=z.x;g.player.y=z.y;g.player.hp=1;g.player.invuln=0;g.time=z.impactAt;updateColossus(g);}assert.ok(g.ended);assert.equal(g.court.colossus.zones.length,0);assert.equal(colossusEnemy(g),undefined);assert.equal(g.court.colossus.status,'departed');assert.equal(courtMission(g).colossus.reward,0);}});

test('previous v27 hunts still encode and decode without colossus statistics',async()=>{const g=eligible(),r=record(g);r.rules='2026.10-v27-court-test';assert.equal(r.mission.colossus,undefined);const decoded=await decodeRun(await encodeRun(r));assert.equal(decoded.rules,r.rules);assert.equal(decoded.mission.colossus,undefined);});

test('pursuer volley intercepts steady straight-line kiting but turning away avoids it',()=>{for(const turn of [false,true]){const g=eligible('sovereign');summonColossus(g);g.moving=true;g.movementAngle=0;g.court.colossus.pattern=2;colossusVolley(g,colossusEnemy(g));const z=g.court.colossus.zones[0],speed=g.monster.speed*g.releaseStats.move;assert.ok(Math.abs(z.x-speed*(z.impactAt-g.time))<.01);assert.ok(Math.abs(z.y)<z.radius+23);const hp=g.player.hp;g.player.invuln=0;g.player.x=turn?0:z.x;g.player.y=turn?-200:0;g.time=z.impactAt;updateColossus(g);assert.equal(g.player.hp<hp,!turn);}});

test('current hunt codes reject arena-only feats while historical codes remain readable',()=>{const r=record(eligible());validateRun(r);assert.throws(()=>validateRun({...r,feats:{...r.feats,apex:1}}),/hunt feat/);validateRun({...r,rules:'2026.10-v28-court-test',feats:{...r.feats,apex:1}});});
