import {pathToFileURL} from 'node:url';import {mkdir} from 'node:fs/promises';import assert from 'node:assert/strict';
const {chromium}=await import(process.env.PLAYWRIGHT_PATH?pathToFileURL(process.env.PLAYWRIGHT_PATH).href:'playwright');const browser=await chromium.launch({headless:true,...(process.env.BROWSER_PATH?{executablePath:process.env.BROWSER_PATH}:{})});const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write']});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await mkdir('test-results',{recursive:true});
await page.addInitScript(()=>{const fill=CanvasRenderingContext2D.prototype.fillText;window.__cardNames=[];CanvasRenderingContext2D.prototype.fillText=function(text,...args){if(this.canvas.width===1200&&this.canvas.height===1000)window.__cardNames.push(text);return fill.call(this,text,...args);};});
const ids=process.argv.slice(2);for(const id of ids.length?ids:['sovereign','titan','devourer','calamity','overlord']){
 await page.goto('http://127.0.0.1:4173');await page.locator('#name').fill('AZRAEL');await page.locator('[data-monster='+id+']').click();await page.locator('#title').selectOption('The Unbound');const before=await page.locator('#preview').evaluate(c=>c.toDataURL());await page.locator('[data-channel=primary][data-color="#387ccb"]').click();await page.locator('[data-channel=power][data-color="#49b3aa"]').click();await page.waitForTimeout(100);assert.notEqual(await page.locator('#preview').evaluate(c=>c.toDataURL()),before);await page.screenshot({path:'test-results/'+id+'-selection.png'});
 await page.locator('#startForm button[type=submit]').click();assert.equal(await page.locator('#hudName').textContent(),'AZRAEL');await page.keyboard.down('d');await page.waitForTimeout(500);await page.keyboard.up('d');for(const k of ['q','e','r'])await page.keyboard.press(k);await page.waitForTimeout(7000);await page.keyboard.press(' ');await page.waitForTimeout(1500);assert.ok(Number((await page.locator('#kills').textContent()).replaceAll(',',''))>0);await page.screenshot({path:'test-results/'+id+'-combat.png'});await page.keyboard.press('Escape');assert.equal(await page.locator('#pauseName').textContent(),'AZRAEL');await page.locator('#endRun').click();await page.waitForFunction(()=>document.querySelector('#runCode').value.startsWith('MM3.'));assert.equal(await page.locator('#resultName').textContent(),'AZRAEL');await page.locator('#copy').click();assert.ok((await page.evaluate(()=>navigator.clipboard.readText())).includes('AZRAEL'));const download=page.waitForEvent('download');await page.locator('#saveCard').click();await (await download).saveAs('test-results/'+id+'-card.png');assert.ok((await page.evaluate(()=>window.__cardNames)).includes('AZRAEL'));await page.screenshot({path:'test-results/'+id+'-result.png'});
 const run=await page.evaluate(async()=>{const {decodeRun}=await import('./src/run-code.js');return decodeRun(document.querySelector('#runCode').value);});assert.equal(run.name,'AZRAEL');assert.equal(run.monsterId,id);assert.equal(run.colors.primary,'#387ccb');assert.equal(run.title,'The Unbound');
 await page.locator('#resultRecords').click();assert.ok(await page.locator('#recordList article').count()>5);await page.locator('#closeRecords').click();await page.locator('#again').click();assert.equal(await page.locator('#hudName').textContent(),'AZRAEL');await page.reload();assert.equal(await page.locator('#name').inputValue(),'AZRAEL');assert.equal(await page.locator('[data-monster='+id+']').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('[data-channel=primary][data-color="#387ccb"]').getAttribute('aria-pressed'),'true');console.log(id+': identity, preview/palette, four powers, pause/result, copied text, card, restart and reload passed; new records '+run.newRecords.join(','));
}assert.deepEqual(errors,[]);await browser.close();
