import test from 'node:test';import assert from 'node:assert/strict';
import {Game} from '../src/simulation.ts';import {MONSTERS} from '../src/content-monsters.ts';
import {createIdentity} from '../src/identity.ts';import {huntGrade,huntMaximum} from '../src/hunt-grade.ts';
import {COURT_TEST_RULES,spawnCourtHunt,chooseCourtUpgrade,courtMission} from '../src/stage-two.ts';
import {courtFeatMaximum,COURT_FEATS,courtSlamStart,courtSlamEnd} from '../src/court-feats.ts';
import {COLOSSUS,summonColossus,colossusEnemy,colossusVolley,updateColossus} from '../src/ashen-colossus.ts';
import {encodeRun,decodeRun,validateRun} from '../src/run-code.ts';import {resultText} from '../src/results.ts';

test('every unnamed nature follows its selection, existing defaults migrate and custom names remain untouched',()=>{for(const id of Object.keys(MONSTERS)){const name='Unnamed '+MONSTERS[id].archetype;assert.equal(createIdentity({monsterId:id}).name,name);assert.equal(createIdentity({monsterId:id,name:'  '}).name,name);assert.equal(createIdentity({monsterId:id,name:'Unnamed Calamity'}).name,name);assert.equal(createIdentity({monsterId:id,name:'Lady Ash'}).name,'Lady Ash');}});
test('one fixed maximum includes finite combat, objectives, Colossus, speed and exactly 49 possible feats',()=>{assert.equal(courtFeatMaximum(),1515000);assert.deepEqual(huntMaximum(COURT_TEST_RULES),{combat:500000,captains:30000,objectives:6750000,speed:3200000,colossus:1200000,feats:1515000});const record={rules:COURT_TEST_RULES,mission:{},score:13195000};assert.equal(huntGrade(record).maximum,13195000);for(const [percent,letter] of [[100,'S'],[99.999,'A'],[90,'A'],[89.9,'B'],[80,'B'],[70,'C'],[60,'D'],[50,'E'],[49.9,'F'],[0,'F']]){const grade=huntGrade({...record,score:Math.round(record.score*percent/100)});assert.equal(grade.letter,letter);if(percent<100)assert.ok(grade.percent<100);}assert.equal(huntGrade({...record,rules:'2026.10-v31-court-hunts'}),null);assert.equal(huntGrade({...record,mission:undefined}),null);});
test('feats pay their own finite rewards after combat cap and cannot farm a repeated slam or guard',()=>{const g=new Game(77,{},1);spawnCourtHunt(g);g.score.award(1e9);const cap=g.enemies.find(e=>e.active&&e.court?.role==='captain'),before=g.score.dominance;for(let n=0;n<100;n++){courtSlamStart(g,cap,true);courtSlamEnd(g,cap,false);}assert.equal(g.score.feats.hunt_dodge,1);assert.equal(g.court.scoring.feats,25000);assert.equal(g.score.dominance,before+25000);assert.equal(g.court.scoring.combat,50000);});
test('each volley covers current position and moving lead with surrounding zones, remains bounded, and deals the stronger impact',()=>{const g=new Game(77,{monsterId:'calamity'},1);g.time=420;for(let n=0;n<8;n++){spawnCourtHunt(g);const cap=g.enemies.find(e=>e.active&&e.court?.role==='captain');g.damage(cap,1e9,'direct');g.court.pending=0;}g.player.x=g.player.y=0;g.court.colossus.retryAt=0;if(g.court.colossus.status==='unseen')summonColossus(g);const boss=colossusEnemy(g);g.moving=true;g.movementAngle=0;for(let pattern=0;pattern<3;pattern++){g.court.colossus.zones.length=0;g.court.colossus.pattern=pattern;colossusVolley(g,boss);const zones=g.court.colossus.zones;assert.equal(zones.length,6);assert.deepEqual([zones[0].x,zones[0].y],[0,0]);assert.ok(Math.abs(zones[1].x-g.monster.speed*g.releaseStats.move*(zones[1].impactAt-g.time))<1e-6);assert.ok(zones.slice(2).every(z=>Math.hypot(z.x,z.y)>=150-.001));}g.player.invuln=0;g.shield=0;g.time=g.court.colossus.zones[0].impactAt;const hp=g.player.hp;updateColossus(g);assert.equal(hp-g.player.hp,COLOSSUS.impact*g.monster.armor);for(let n=0;n<20;n++)colossusVolley(g,boss);assert.ok(g.court.colossus.zones.length<=18);});
test('v32 code proves feat totals and limits; earlier codes retain their original three-field score format and name',async()=>{const g=new Game(77,{monsterId:'devourer'},1);g.time=420;spawnCourtHunt(g);const cap=g.enemies.find(e=>e.active&&e.court?.role==='captain');g.player.x=cap.x;g.player.y=cap.y;g.damage(cap,1e9,'lunge');chooseCourtUpgrade(g,'power');const run={version:4,rules:COURT_TEST_RULES,phase:1,...g.identity,seed:77,duration:420,score:g.score.dominance,kills:g.score.kills,wave:15,elites:g.score.elites,titans:g.score.titans,multi:g.score.largestMulti,peak:g.score.peak,feats:{...g.score.feats},ended:'2026-10-06T16:00:00Z',reason:'retired',release:4,build:'0123456789abcdef',court:{...g.court.stats},mission:courtMission(g),testing:true};assert.deepEqual(await decodeRun(await encodeRun(run)),run);assert.match(resultText(run),/GRADE F/);assert.match(resultText(run),/500,000 maximum/);assert.throws(()=>validateRun({...run,score:run.score+1,mission:{...run.mission,scoring:{...run.mission.scoring,feats:run.mission.scoring.feats+1}}}),/feat score/);assert.throws(()=>validateRun({...run,feats:{hunt_focus:11}}));const {feats,...scoring}=run.mission.scoring;for(const version of [28,29,30,31]){const old={...run,name:'Unnamed Calamity',rules:`2026.10-v${version}-court-test`,score:run.score-feats,mission:{...run.mission,scoring}};assert.deepEqual(await decodeRun(await encodeRun(old)),old);}});
