import test from 'node:test';import assert from 'node:assert/strict';
import {Game} from '../src/simulation.ts';import {TITAN_FISSURE_RULES,titanKitForStage} from '../src/champion-kits.ts';import {normalizeProfile,recordProgress} from '../src/profile.ts';import {progressExport,parseProgressExport,mergeProgress} from '../src/progress-transfer.ts';import {stageAccess,STAGE_GATES} from '../src/stage-access.ts';import {rulesForStage} from '../src/stage-two.ts';import {encodeRun,decodeRun,validateRun} from '../src/run-code.ts';import {recordBest} from '../src/personal-bests.ts';import {resultText} from '../src/results.ts';import {reaperTarget,reaperSuggestedTarget,reaperTappedEnemy} from '../src/reaper.ts';
const open=Date.parse(STAGE_GATES[0].opensAt),earned=()=>{const p=normalizeProfile(null);for(let n=1;n<=7;n++)recordProgress(p,{id:'day'+n,monsterId:'devourer',phase:0,reason:'overwhelmed',values:{seconds:510,kills:15000},best:{}},true,new Date(Date.UTC(2026,9,n,16)));return p;};
test('Titan Fissure is account-wide after real Stage 2 access; old saves, locked and missing-clock profiles retain Throw',()=>{const p=earned();p.titanKit='fissure';assert.equal(titanKitForStage(0,p.titanKit,stageAccess(1,p.progress,open)==='open'),'fissure');for(const clock of [open-1,null])assert.equal(titanKitForStage(0,p.titanKit,stageAccess(1,p.progress,clock)==='open'),'throw');assert.equal(titanKitForStage(0,'fissure',false),'throw');assert.equal(titanKitForStage(1,'throw',false),'fissure');assert.equal(normalizeProfile({version:3}).titanKit,'throw');assert.equal(normalizeProfile({version:3,titanKit:'invalid'}).titanKit,'throw');assert.equal(new Game(77,{monsterId:'titan'},0).powers[2].id,'kingfall');const g=new Game(77,{monsterId:'titan'},0,'fissure');assert.equal(g.powers[2].id,'faultline');assert.equal(g.court,null);assert.equal(g.release,0);});
test('Titan kit preference survives exports and merges without discarding titles, qualifying days or historic personal bests',()=>{const p=earned();p.titanKit='fissure';p.personalBests['2026.10-v15-autotarget-squad|0|titan|overwhelmed']={score:99,kills:88,seconds:77};const restored=parseProgressExport(progressExport(p));assert.equal(restored.titanKit,'fissure');assert.deepEqual(restored.progress,normalizeProfile(p).progress);assert.equal(restored.progress.archetypes.titan.stageOneBestSeconds,77);assert.deepEqual(restored.personalBests,p.personalBests);const merged=mergeProgress(normalizeProfile(null),restored);assert.equal(merged.titanKit,'fissure');assert.deepEqual(merged.progress.trials.gatebreaker.devourer,p.progress.trials.gatebreaker.devourer);assert.ok(merged.progress.titles.gatebreaker);});
test('Fissure run codes authenticate kit identity and separate personal bests while retaining historical codes',async()=>{const base={version:4,rules:rulesForStage(0,false,'titan'),phase:0,...new Game(77,{monsterId:'titan'},0).identity,seed:77,duration:60,score:10,kills:5,wave:3,elites:0,titans:0,multi:1,peak:1,feats:{},ended:'2026-10-08T16:00:00Z',reason:'retired',release:0,build:'0123456789abcdef'},r={...base,rules:TITAN_FISSURE_RULES,kit:'fissure'};assert.deepEqual(await decodeRun(await encodeRun(r)),r);assert.deepEqual(await decodeRun(await encodeRun(base)),base);for(const bad of [{kit:undefined},{monsterId:'devourer'},{phase:1},{kit:'throw'},{rules:base.rules}])assert.throws(()=>validateRun({...r,...bad}));const bests={};recordBest(bests,base);recordBest(bests,r);assert.equal(Object.keys(bests).length,2);assert.match(resultText(r),/Fissure kit/);});
const encounter=()=>{const g=new Game(77,{monsterId:'reaper'},1);g.targetView={x:640,y:360};const weak=g.spawn('thrall'),capt=g.spawn('brute');Object.assign(weak,{x:40,y:0,hp:1e6});Object.assign(capt,{x:520,y:0,hp:1e6,court:{role:'captain',guard:0,maxGuard:0}});g.rebuildGrid();return {g,weak,capt};};
test('Reaper suggested targets favor visible captains over adjacent mobs, retain equal-priority focus and never reveal hidden camps',()=>{const {g,weak,capt}=encounter();assert.equal(reaperSuggestedTarget(g),capt);g.player.x=-100;g.rebuildGrid();assert.equal(reaperSuggestedTarget(g),capt);g.player.x=-130;g.rebuildGrid();assert.equal(reaperSuggestedTarget(g),weak);g.player.x=0;capt.x=150;const other=g.spawn('brute');Object.assign(other,{x:110,y:0,court:{role:'captain',guard:0}});g.reaperFocus=capt.serial;g.rebuildGrid();assert.equal(reaperSuggestedTarget(g),capt);capt.active=false;g.rebuildGrid();assert.equal(reaperSuggestedTarget(g),other);other.active=weak.active=false;g.rebuildGrid();assert.equal(reaperSuggestedTarget(g),null);});
test('shorter-range Reaper attacks cannot steal longer-range captain focus; stronger threats and death retarget correctly',()=>{const {g,weak,capt}=encounter();capt.x=1020;g.rebuildGrid();assert.equal(reaperTarget(g,1050,true),capt);assert.equal(reaperTarget(g,990,true),weak);assert.equal(g.reaperFocus,capt.serial);assert.equal(reaperTarget(g,1050,true),capt);capt.x=900;g.rebuildGrid();assert.equal(reaperTarget(g,990,true),capt);const col=g.spawn('titan');Object.assign(col,{x:850,y:0,colossus:{expiresAt:120}});g.rebuildGrid();assert.equal(reaperTarget(g,990,true),col);col.active=false;g.rebuildGrid();assert.equal(reaperTarget(g,990,true),capt);capt.active=false;g.rebuildGrid();assert.equal(reaperTarget(g,990,true),weak);});
test('overlapping tap targets resolve exact ties to captains while deliberate taps on other prey still work',()=>{const {g,weak,capt}=encounter();weak.x=capt.x;g.rebuildGrid();assert.equal(reaperTappedEnemy(g,capt),capt);weak.x=80;g.rebuildGrid();assert.equal(reaperTappedEnemy(g,weak),weak);});

test('actual Reaper basics and Eclipse waves retain captain destinations while moving past nearby fodder',()=>{const {g,capt}=encounter();g.court.initialized=true;capt.court={...capt.court,facing:0,broken:true,homeX:520,homeY:0,homeAngle:0,site:0,tier:0};for(const [x,y] of [[0,0],[100,50],[-30,-20]]){g.player.x=x;g.player.y=y;capt.x=520;capt.y=0;g.attack=0;g.reaperStorm=1;g.reaperPulse=0;g.scytheWaves.length=0;g.rebuildGrid();g.update(1/60,{x:1,y:0,aimX:40,aimY:0,aiming:true});const basic=g.scytheWaves.find(w=>w.source==='scythe'),ultimate=g.scytheWaves.filter(w=>w.source==='moonstorm');assert.ok(basic);assert.equal(ultimate.length,2);for(const w of [basic,...ultimate]){assert.ok(w.end.x>500);assert.ok(Math.abs(w.end.y)<5);}assert.equal(g.reaperFocus,capt.serial);}});
