import test from 'node:test';import assert from 'node:assert/strict';
import {Game} from '../src/simulation.ts';import {ABILITIES} from '../src/content-monsters.ts';
import {claimRelic,equipRelic,restoreNativePower,teleportRealm,updateTitanRealm,realmSummary,TITAN_REALM_TEST_RULES,readRealmClue} from '../src/stage-three.ts';
import {REALM_GROTTOS,REALM_CLUES,insideRealm,moveRealm} from '../src/titan-realm-map.ts';
import {encodeRun,decodeRun,validateRun} from '../src/run-code.ts';import {resultGrade,realmMaximum} from '../src/hunt-grade.ts';import {resultText} from '../src/results.ts';
const idle={x:0,y:0,aimX:0,aimY:0,aiming:false};
function game(id='sovereign',phase=2){const g=new Game(17,{monsterId:id},phase);g.seedOpening();return g;}
function at(g,id){Object.assign(g.player,{x:REALM_GROTTOS[id].x,y:REALM_GROTTOS[id].y-150});}
function record(g){return {version:4,rules:TITAN_REALM_TEST_RULES,phase:2,release:4,build:'1234567890abcdef',name:g.identity.name,title:g.identity.title,monsterId:g.monster.id,colors:g.identity.colors,seed:g.seed,duration:Math.floor(g.time),score:g.score.dominance,kills:g.score.kills,wave:g.wave,elites:g.score.elites,titans:g.score.titans,multi:g.score.largestMulti,peak:Number(g.score.peak.toFixed(2)),feats:g.score.feats,ended:'2026-10-08T12:00:00Z',reason:'retired',testing:true,realm:realmSummary(g)};}
test('relic swaps deposit the outgoing power locally, and occupied portals reject travel without erasing discovery',()=>{const g=game(),a=g.realm.relics[0],b=g.realm.relics[1],homeA=a.shrine,homeB=b.shrine;for(const s of g.realm.shrines)s.cleared=true;at(g,homeA);assert.ok(claimRelic(g,homeA));assert.ok(equipRelic(g,a.id,0));assert.equal(a.shrine,null);at(g,homeB);assert.ok(claimRelic(g,homeB));assert.ok(equipRelic(g,b.id,0));assert.equal(a.shrine,homeB);assert.equal(b.shrine,null);assert.equal(g.realm.shrines[homeB].decor,a.nature);assert.equal(restoreNativePower(g,0),false);assert.ok(teleportRealm(g,homeA));assert.equal(teleportRealm(g,homeA),false);g.realm.shrines[homeB].occupied=true;assert.equal(teleportRealm(g,homeB),false);assert.ok(a.known&&b.known);});
test('recapture is a bounded one-time occupation by ordinary mobs and never a new guardian fight',()=>{const g=game();g.realm.shrines[0].cleared=true;at(g,0);claimRelic(g,0);g.player.x=0;g.player.y=1030;g.time=151;updateTitanRealm(g,0);assert.ok(g.realm.shrines[0].occupied);at(g,0);updateTitanRealm(g,0);const raiders=g.enemies.filter(e=>e.active&&e.realm?.occupation===0);assert.equal(raiders.length,3);assert.ok(raiders.every(e=>e.realm.role==='attendant'));raiders.forEach(e=>{e.active=false;g.alive--;});updateTitanRealm(g,0);assert.equal(g.realm.shrines[0].occupied,false);g.time=1000;g.player.x=0;g.player.y=1030;updateTitanRealm(g,0);assert.equal(g.realm.shrines[0].occupied,false);});
test('swept movement cannot jump a chasm or escape the map, while legal bridge travel remains usable',()=>{const p={x:700,y:700};moveRealm(p,{x:0,y:0},23);assert.ok(insideRealm(p.x,p.y,23));assert.ok(Math.hypot(p.x,p.y)<550);const q={x:1900,y:0};moveRealm(q,{x:1500,y:0},23);assert.ok(q.x>1850);});
test('Vault has visible airborne travel and damages and knocks back only on landing',()=>{const g=game('lycanthrope',0);g.enemies.forEach(e=>e.active=false);g.alive=0;const e=g.spawn('brute');Object.assign(e,{x:300,y:0,hp:10000,maxHp:10000});g.rebuildGrid();g.setMovementDirection(1,0);assert.ok(g.cast(0,{x:300,y:0}));assert.equal(g.player.x,0);assert.equal(e.hp,10000);g.update(.2,idle);assert.ok(g.player.x>0&&g.player.x<300);g.update(.5,idle);assert.equal(g.vault,null);assert.ok(e.hp<10000);assert.ok(Math.hypot(e.vx,e.vy)>0);});
test('Bloodmoon runs rather than teleports, protects for its entire duration and stops protecting afterward',()=>{const g=game('lycanthrope',0);g.enemies.forEach(e=>e.active=false);g.alive=0;g.player.hp=500;const e=g.spawn('brute');Object.assign(e,{x:300,y:0,hp:100000,maxHp:100000});g.rebuildGrid();g.cast(3);const hp=g.player.hp;g.hurt(10000);assert.equal(g.player.hp,hp);g.update(1/60,idle);assert.ok(g.player.x>0&&g.player.x<=800/60);for(let i=0;i<420;i++)g.update(1/60,idle);assert.ok(g.player.hp>hp);assert.equal(g.moonFury,0);g.hurt(10000);assert.equal(g.player.hp,0);});
test('all four defense clues can be read before battle, pay once, and serialize without revealing the solution',async()=>{const g=game();for(const [i,q] of REALM_CLUES.entries()){Object.assign(g.player,q);assert.ok(readRealmClue(g,i));assert.ok(readRealmClue(g,i));}assert.equal(g.realm.attempts,0);assert.equal(g.score.feats.council,4);const r=record(g),decoded=await decodeRun(await encodeRun(r));assert.deepEqual(decoded.realm,r.realm);assert.equal('pattern' in decoded.realm,false);assert.ok(resultGrade(r));assert.match(resultText(r),/GRADE F/);});
test('Stage 3 grade accounts for all finite sources, and a mathematically complete run earns S',()=>{const g=game(),r=record(g),max=Object.values(realmMaximum(r.rules)).reduce((a,b)=>a+b,0);assert.equal(resultGrade({...r,score:max}).letter,'S');assert.equal(resultGrade({...r,score:Math.ceil(max*.9)}).letter,'A');assert.equal(resultGrade({...r,score:0}).letter,'F');});
test('Vortex cannot instantly kill, drag or devour a titan in either existing stage',()=>{for(const phase of [0,1]){const g=game('calamity',phase);g.enemies.forEach(e=>e.active=false);g.alive=0;const e=g.spawn('titan');Object.assign(e,{x:150,y:0,hp:50000,maxHp:50000});g.rebuildGrid();g.cast(2,{x:150,y:0});g.update(1/60,idle);assert.ok(e.hp>49000);assert.equal(e.vx,0);assert.equal(e.vy,0);}});
test('v35 score budgets and issued feat values remain valid after the new grading rules',async()=>{const g=game(),r=record(g);r.rules='2026.10-v35-titan-test';r.feats={prepared:1};r.realm={...r.realm,shrines:4,guardians:12,relics:4,attempts:1,objective:4*700000+180000};r.score=r.realm.objective;validateRun(r);assert.equal((await decodeRun(await encodeRun(r))).score,r.score);});

test('lingering correct powers do not become wrong guesses at a new defense, and a reset cannot farm insight',()=>{const g=game(),s=g.realm;g.player.x=0;g.player.y=100;s.engaged=true;s.pattern=['sovereign','titan','calamity','reaper'];s.trials.spellsteel=0;g.damage(s.boss,1e9,'relic:sovereign:spellsteel');assert.equal(s.layer,1);g.damage(s.boss,1000,'relic:sovereign:spellsteel');assert.equal(s.firstWrong,0);s.layer=0;s.open=false;s.boss.hp=s.boss.maxHp;g.damage(s.boss,1000,'relic:sovereign:spellsteel');assert.equal(g.score.feats.insight,1);});
