import test from 'node:test';import assert from 'node:assert/strict';
import {Game} from '../src/simulation.ts';import {ABILITIES} from '../src/content-monsters.ts';
import {gripTarget,releaseGrip} from '../src/lycanthrope.ts';
import {precisionReward,realmKill,RELIC_POOLS,TITAN_REALM_TEST_RULES,realmSummary} from '../src/stage-three.ts';
import {REALM_GROTTOS,realmPortal,insideRealm} from '../src/titan-realm-map.ts';
import {encodeRun,decodeRun} from '../src/run-code.ts';
import {titanMotion} from '../src/realm-encounter.ts';
const idle={x:0,y:0,aimX:0,aimY:0,aiming:false};
function clean(phase=0){const g=new Game(17,{monsterId:'lycanthrope'},phase);g.seedOpening();g.enemies.forEach(e=>e.active=false);g.alive=0;g.player.x=g.player.y=0;g.rebuildGrid();return g;}
function prey(g,kind='hound',hp=100000){const e=g.spawn(kind);Object.assign(e,{x:70,y:0,hp,maxHp:hp});g.rebuildGrid();return e;}
test('Clinch captures a real enemy without killing it, excludes it from normal targeting and credits its defeat once',()=>{const g=clean(),e=prey(g);assert.ok(g.cast(2));assert.equal(e.grabbed,true);assert.equal(g.score.kills,0);assert.equal(g.nearestEnemy(1000),null);g.damage(e,1e9,'direct');assert.equal(e.hp,100000);const victim=prey(g,'thrall');victim.x=160;g.rebuildGrid();g.update(.1,idle);assert.ok(victim.hp<100000);assert.equal(e.hp,100000);assert.ok(g.grip.remaining<g.grip.total);releaseGrip(g,true);assert.equal(e.active,false);assert.equal(g.score.kills,1);releaseGrip(g,true);assert.equal(g.score.kills,1);});
test('Clinch cannot capture apex enemies, allows brutes at Release II and weakened elites at Final Release',()=>{for(const [kind,release,ratio,allowed] of [['brute',0,1,false],['brute',2,1,true],['elite',3,.1,false],['elite',4,.36,false],['elite',4,.35,true],['titan',4,.1,false]]){const g=clean(),e=prey(g,kind);g.release=release;e.hp=e.maxHp*ratio;assert.equal(!!gripTarget(g),allowed,kind+' '+release+' '+ratio);}const g=clean();const e=prey(g);e.realm={role:'guardian'};assert.equal(gripTarget(g),null);e.realm=undefined;e.court={role:'captain'};assert.equal(gripTarget(g),null);assert.equal(g.cast(2),false);assert.equal(g.cooldowns[2],0);});
test('held enemies cannot be reused by the spawn pool and protection ends with the grip',()=>{const g=clean(),e=prey(g);g.cast(2);const serial=e.serial;for(let i=0;i<50;i++)g.spawn('thrall');assert.equal(e.serial,serial);g.player.hp=900;g.hurt(100);assert.equal(g.player.hp,815);releaseGrip(g);g.player.invuln=0;g.hurt(100);assert.equal(g.player.hp,715);assert.equal(e.grabbed,false);});
test('Bloodmoon retains its duration and immunity but permits movement when the view has no targets',()=>{const g=clean();g.cast(3);const total=g.moonFuryTotal;g.update(.1,idle);assert.equal(g.moonFuryFree,true);const before=g.player.x;g.update(.1,{...idle,x:1});assert.ok(g.player.x>before);assert.ok(g.moonFury>0&&g.moonFury<total);g.hurt(1e9);assert.ok(g.player.hp>0);});
test('precision rewards required grottos and deducts for excess rather than paying for all seven',()=>{assert.equal(precisionReward(4,0),8400000);assert.equal(precisionReward(4,1),7500000);assert.equal(precisionReward(4,3),5700000);const g=new Game(17,{},2);g.seedOpening();const needed=g.realm.shrines.find(s=>s.required),extra=g.realm.shrines.find(s=>!s.required);for(const shrine of [needed,extra]){const e=g.spawn('brute');e.realm={role:'guardian',shrine:shrine.id};e.active=false;realmKill(g,e);}assert.equal(g.realm.precision.earned,1200000);assert.equal(g.realm.objective,1200000);assert.equal(g.realm.precision.unneeded,1);});
test('every donor offers all four existing powers and its fifth power',()=>{for(const [nature,ids] of Object.entries(RELIC_POOLS)){assert.equal(ids.length,5);assert.equal(new Set(ids).size,5);ids.forEach(id=>assert.ok(ABILITIES[id],nature+' '+id));}});
test('native relics match their recognizable themed grotto and each portal is on its floor',()=>{for(let seed=1;seed<=50;seed++){const g=new Game(seed,{},2);for(const s of REALM_GROTTOS){assert.equal(g.realm.relics.find(r=>r.shrine===s.id).nature,s.nature);const p=realmPortal(s.id);assert.ok(insideRealm(p.x,p.y,24));}}});
test('the titan rush is telegraphed, moves continuously and can be dodged',()=>{for(const dodge of [false,true]){const g=new Game(17,{},2);g.seedOpening();const s=g.realm,b=s.boss;s.engaged=true;g.player.x=240;g.player.y=0;b.x=0;b.y=0;b.timer=0;titanMotion(g,b,0);assert.equal(s.action.kind,'rush');const hp=g.player.hp;titanMotion(g,b,.4);assert.equal(b.x,0);assert.equal(g.player.hp,hp);if(dodge)g.player.y=170;titanMotion(g,b,.5);assert.ok(b.x>0&&b.x<=300);assert.equal(g.player.hp<hp,!dodge);}});
test('eruption surrounds the player, remains bounded and gives the slowest body room to react',()=>{const g=new Game(17,{},2);g.seedOpening();g.realm.engaged=true;g.realm.attackIndex=2;g.realm.boss.timer=0;g.player.y=180;titanMotion(g,g.realm.boss,0);titanMotion(g,g.realm.boss,1);assert.equal(g.realm.zones.length,6);assert.deepEqual([g.realm.zones[0].x,g.realm.zones[0].y],[g.player.x,g.player.y]);assert.ok(g.realm.zones.every(z=>z.warning>=1.3));});
test('new precision results reject score inflation and previously issued v36 codes still roundtrip',async()=>{const g=new Game(17,{},2);g.seedOpening();const run={version:4,rules:TITAN_REALM_TEST_RULES,phase:2,release:4,build:'1234567890abcdef',name:g.identity.name,title:g.identity.title,monsterId:g.monster.id,colors:g.identity.colors,seed:g.seed,duration:0,score:0,kills:0,wave:1,elites:0,titans:0,multi:0,peak:1,feats:{},ended:'2026-10-08T12:00:00Z',reason:'retired',testing:true,realm:realmSummary(g)};assert.deepEqual((await decodeRun(await encodeRun(run))).realm.precision,{needed:0,unneeded:0,earned:0});await assert.rejects(()=>encodeRun({...run,realm:{...run.realm,precision:{needed:0,unneeded:0,earned:1}}}));const old={...run,rules:'2026.10-v36-titan-test',realm:{...run.realm}};delete old.realm.precision;assert.equal((await decodeRun(await encodeRun(old))).rules,old.rules);});
test('borrowed powers do not pretend to be the body’s native powers when exposing a guardian',()=>{const g=new Game(17,{monsterId:'sovereign'},2);g.seedOpening();g.player.x=g.player.y=0;const e=g.spawn('brute');Object.assign(e,{x:30,y:0,hp:100,maxHp:1000,realm:{role:'guardian',shrine:0,homeX:30,homeY:0,variant:0}});g.rebuildGrid();g.powers[0]=ABILITIES.worldbreaker;g.relicOwners[0]='titan';g.cast(0);assert.ok(e.active);assert.equal(e.realm.exposedUntil,undefined);g.powers[0]=ABILITIES.rupture;g.relicOwners[0]='sovereign';g.cooldowns[0]=0;g.cast(0);assert.equal(e.active,false);});
test('Calamity’s smaller-crowd ward is confined to Stage 3',()=>{for(const phase of [0,1,2]){const g=new Game(17,{monsterId:'calamity'},phase);g.seedOpening();g.completeAttack(6);assert.equal(g.shield,phase===2?96:0);}});
