import test from 'node:test';
import assert from 'node:assert/strict';
import {REALM_EDGE,REALM_LANES,insideRealm,moveRealm,slideRealm,REALM_GROTTOS,REALM_START,realmWaypoint} from '../src/titan-realm-map.ts';
import {Game} from '../src/simulation.ts';
import {parkourLanding} from '../src/lycanthrope.ts';
const bridges=REALM_LANES.filter(l=>l.a.x!==l.b.x||l.a.y!==l.b.y);
test('walking, knockback and dashes cannot cross any outer mana curtain',()=>{for(const lane of bridges)for(const end of [lane.a,lane.b])for(const radius of [23,24,30]){const horizontal=lane.a.x!==lane.b.x,axis=horizontal?'x':'y',sign=Math.sign(end[axis]),from={...end},body={...end};from[axis]=sign*(REALM_EDGE-100);body[axis]=sign*(REALM_EDGE+500);moveRealm(body,from,radius);assert.ok(insideRealm(body.x,body.y,radius));assert.ok(Math.abs(body[axis])<=REALM_EDGE-radius+.001);const outside={...end};outside[axis]=sign*(REALM_EDGE+1);assert.equal(insideRealm(outside.x,outside.y,radius),false);const displaced={...end};displaced[axis]=sign*(REALM_EDGE+1000);slideRealm(displaced,radius);assert.ok(insideRealm(displaced.x,displaced.y,radius));assert.ok(Math.abs(displaced[axis])<=REALM_EDGE-radius+.001);}});
test('horizontal bridge collision follows the illustrated floor rather than its lower railing',()=>{for(const row of [-1536,0,1536])for(const x of [-2090,-800,800,2090]){assert.ok(insideRealm(x,row-38,23));assert.equal(insideRealm(x,row+30,23),false);assert.equal(insideRealm(x,row-106,23),false);}});
test('Vault rejects landings in the ether and every shrine still has a connected approach',()=>{const g=new Game(17,{monsterId:'lycanthrope'},2);g.player.x=REALM_EDGE-90;g.player.y=-38;assert.equal(parkourLanding(g,{x:REALM_EDGE+40,y:-38}),null);const nearEdge=parkourLanding(g,{x:REALM_EDGE-15,y:-38});assert.ok(nearEdge&&insideRealm(nearEdge.x,nearEdge.y,23));assert.ok(parkourLanding(g,{x:REALM_EDGE-170,y:-38}));for(const shrine of REALM_GROTTOS){const goal={x:shrine.x,y:shrine.y-150},p={...REALM_START};for(let i=0;i<7000&&Math.hypot(p.x-goal.x,p.y-goal.y)>30;i++){const q=realmWaypoint(p.x,p.y,goal.x,goal.y),d=Math.hypot(q.x-p.x,q.y-p.y)||1,from={...p};p.x+=(q.x-p.x)/d*4;p.y+=(q.y-p.y)/d*4;moveRealm(p,from,23);}assert.ok(Math.hypot(p.x-goal.x,p.y-goal.y)<30,shrine.name);}});
