import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';import {writeFile} from 'node:fs/promises';
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_PATH).href),browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_PATH}),origin='http://127.0.0.1:4173',errors=[],report={};
async function hooks(page){page.on('pageerror',e=>errors.push(e.message));await page.evaluate(async()=>{const {Game}=await import('./src/simulation.js'),u=Game.prototype.update;Game.prototype.update=function(...a){window.g=this;return u.apply(this,a);};const {Renderer}=await import('./src/renderer.js'),d=Renderer.prototype.draw;Renderer.prototype.draw=function(...a){window.r=this;return d.apply(this,a);};const {AudioEngine}=await import('./src/audio.js'),m=AudioEngine.prototype.setMusic;AudioEngine.prototype.setMusic=function(...a){window.audio=this;return m.apply(this,a);};});}
try{
 const context=await browser.newContext({viewport:{width:1440,height:900},serviceWorkers:'block'}),page=await context.newPage();await page.goto(origin+'/stage2-test/');await hooks(page);await page.locator('[data-monster=reaper]').click();await page.waitForFunction(()=>r.assets.status(r.previewIdentity,'selection')==='ready'&&r.assets.get(r.previewIdentity,'selection')?.selection);await page.screenshot({path:'test-results/reaper-selection-v26.png',fullPage:true});
 report.art=await page.evaluate(async()=>{const {createIdentity}=await import('./src/identity.js');const identity=createIdentity({monsterId:'reaper',colors:{primary:'#eee5d4',secondary:'#49b3aa',accent:'#c14137',power:'#8862c7'}});const sizes={};for(const type of ['selection','portrait','cutin','gameplay']){await r.assets.prepare(identity,type,true);while(r.assets.status(identity,type)!=='ready')await new Promise(resolve=>setTimeout(resolve,30));const image=r.assets.get(identity,type)[type];sizes[type]=[image.width,image.height];if(type==='selection'){const canvas=document.querySelector('#preview');canvas.width=768;canvas.height=1024;const c=canvas.getContext('2d');c.clearRect(0,0,768,1024);c.drawImage(image,0,0);window.contrastSelection=image.toDataURL();}}return sizes;});
 assert.deepEqual(report.art,{selection:[768,1024],portrait:[512,512],cutin:[1024,512],gameplay:[1536,1280]});await writeFile('test-results/reaper-contrast-v26.png',Buffer.from((await page.evaluate(()=>contrastSelection)).split(',')[1],'base64'));
 await page.locator('#startForm button[type=submit]').click();await page.locator('#pause').click();assert.equal(await page.evaluate(()=>g.monster.id),'reaper');assert.equal(await page.evaluate(()=>g.phase),1);await page.evaluate(()=>{g.cast(3);g.player.invuln=100;document.querySelector('#paused').hidden=true;});await page.waitForFunction(()=>r.vfx.has('reaper-eclipse')&&r.assets.status(g.identity,'gameplay')==='ready'&&r.assets.status(g.identity,'cutin')==='ready');await page.screenshot({path:'test-results/reaper-gameplay-v26.png'});await page.evaluate(()=>document.querySelector('#paused').hidden=false);
 // Force a real loss far from the opening terrain, so the previous game's
 // renderer must not evict the opening tiles while Rise Again awaits them.
 await page.evaluate(async()=>{const {COURT_REGIONS}=await import('./src/court-map.js'),region=COURT_REGIONS[2];window.old=g;g.time=240;g.wave=9;g.player.x=region.x;g.player.y=region.y-600;await r.courtTerrain.prepare(g.player.x,g.player.y,680,460);g.player.hp=0;g.ended=true;});await page.locator('#result').waitFor({state:'visible'});await page.waitForFunction(()=>document.querySelector('#runCode').value.startsWith('MM4.'));await page.waitForFunction(()=>!document.querySelector('#resultPortrait').hidden);await page.screenshot({path:'test-results/reaper-result-v26.png'});
 let startFetches=0;await page.route('**/assets/arena/five-regions/*.webp*',async route=>{startFetches++;await new Promise(resolve=>setTimeout(resolve,100));await route.continue();});await page.locator('#again').click();await page.waitForFunction(()=>window.g!==window.old&&g.time<10&&!g.ended,{timeout:20000});assert.equal(await page.locator('#result').isVisible(),false);report.restart={terrainRequests:startFetches,phase:await page.evaluate(()=>g.phase),health:await page.evaluate(()=>g.player.hp)};assert.ok(startFetches>0);assert.equal(report.restart.phase,1);assert.ok(report.restart.health>0);await page.locator('#pause').click();await page.locator('#endRun').click();await page.locator('#back').click();
 await page.locator('[data-monster=titan]').click();await page.locator('#startForm button[type=submit]').click();await page.locator('#pause').click();await page.evaluate(()=>{g.player.maxHp=1839.9999999998;g.player.hp=689;});await page.waitForFunction(()=>document.querySelector('#healthText').textContent.startsWith('689 / 1840'));assert.equal(await page.evaluate(()=>g.player.maxHp),1839.9999999998);await page.locator('#endRun').click();await page.locator('#back').click();
 // Production entry: no title => locked even for Stage 1. The same title,
 // earned on Titan, makes Reaper available for either stage after opening.
 await page.goto(origin+'/');assert.equal(await page.locator('[data-monster=reaper]').isDisabled(),true);await page.evaluate(async()=>{const {normalizeProfile,recordProgress}=await import('./src/profile.js'),p=normalizeProfile(null);for(let n=1;n<=7;n++)recordProgress(p,{id:'q'+n,monsterId:'titan',phase:0,reason:'overwhelmed',values:{seconds:510,kills:15000},best:{seconds:510}},true,new Date(Date.UTC(2026,9,n,16)));localStorage.setItem('mm-profile',JSON.stringify(p));});await page.route('**/index.html?stage-clock=*',route=>route.fulfill({status:200,headers:{Date:'Thu, 08 Oct 2026 05:00:00 GMT'},body:''}));await page.reload();await page.waitForFunction(()=>!document.querySelector('[data-monster=reaper]').disabled);await hooks(page);await page.locator('[data-monster=reaper]').click();await page.locator('#startForm button[type=submit]').click();await page.locator('#pause').click();assert.equal(await page.evaluate(()=>g.phase),0);await page.locator('#endRun').click();await page.locator('#back').click();await page.locator('[data-phase="1"]').click();await page.locator('#startForm button[type=submit]').click();await page.locator('#pause').click();assert.equal(await page.evaluate(()=>g.phase),1);report.access={earnedOn:'titan',reaperPlayableStages:[1,2]};
 // Worker renderer produces the complete score; cancelled generation stays
 // cancelled. The main thread never renders its seven procedural layers.
 report.music=await page.evaluate(async()=>{const {ProceduralMusic}=await import('./src/procedural-music.js'),ctx=new AudioContext(),music=new ProceduralMusic(ctx,ctx.destination);const first=music.prepare('reaper'),worker=music.scoreWorker;const next=music.prepare('ashen-wilds');await Promise.all([first,next]);const result={worker:worker instanceof Worker,theme:music.theme,buffers:music.buffers.length,voices:music.voices.length};music.dispose();await ctx.close();return result;});assert.deepEqual(report.music,{worker:true,theme:'ashen-wilds',buffers:7,voices:7});assert.deepEqual(errors,[]);await writeFile('test-results/reaper-browser-v26.json',JSON.stringify(report,null,2));console.log(report);await context.close();
}finally{await browser.close();}
