import {pathToFileURL} from 'node:url';import assert from 'node:assert/strict';
const {chromium}=await import(process.env.PLAYWRIGHT_PATH?pathToFileURL(process.env.PLAYWRIGHT_PATH).href:'playwright');const browser=await chromium.launch({headless:true,...(process.env.BROWSER_PATH?{executablePath:process.env.BROWSER_PATH}:{})});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install();await page.goto('http://127.0.0.1:4173');
await page.evaluate(async()=>{const {normalizeProfile,saveProfile}=await import('./src/profile.js');const p=normalizeProfile(null);p.identity.name='AZRAEL';p.identity.monsterId='calamity';p.progress.total={kills:24999,runs:1};saveProfile(p,localStorage);});await page.reload();await page.evaluate(async()=>{const {Game}=await import('./src/simulation.js');const update=Game.prototype.update;Game.prototype.update=function(...args){window.recordGame=this;this.player.invuln=100;return update.apply(this,args);};});await page.locator('#startForm button[type=submit]').click();
for(let i=0;i<7;i++){await page.clock.runFor(10000);for(const key of ['q','e','r',' '])await page.keyboard.press(key);}
// Protected progression fixture: perform real kills to cross the record threshold.
await page.evaluate(()=>{const g=recordGame;for(let i=0;i<500;i++){g.spawn('thrall');}for(const e of g.enemies)if(e.active){e.x=g.player.x+(g.random()-.5)*120;e.y=g.player.y+(g.random()-.5)*120;}g.rebuildGrid();g.cooldowns[3]=0;g.cast(3);});await page.clock.runFor(1000);await page.locator('#pause').click();await page.locator('#endRun').click();await page.waitForFunction(()=>document.querySelector('#runCode').value.startsWith('MM4.'));
const run=await page.evaluate(async()=>{const {decodeRun}=await import('./src/run-code.js');return decodeRun(document.querySelector('#runCode').value);});const saved=await page.evaluate(async()=>{const {loadProfile}=await import('./src/profile.js');return loadProfile(localStorage);});assert.ok(saved.progress.titles.slaughter0);assert.ok(saved.records.bloodbath.unlockedAt);assert.ok((await page.locator('#newTitles').textContent()).includes('The Butcher'));await page.locator('#resultRecords').click();assert.equal(await page.locator('#titleList article').count(),26);assert.equal(await page.locator('#recordList h2').count(),0);assert.equal(await page.locator('#featList article').count(),7);assert.ok((await page.locator('#featList').boundingBox()).y>(await page.locator('#titleList').boundingBox()).y);await page.screenshot({path:'test-results/records-v3.png'});
await page.reload();await page.locator('#recordsButton').click();assert.ok((await page.locator('#recordList .unlocked').allTextContents()).some(t=>t.includes('FIRST BLOODBATH')));await page.locator('#closeRecords').click();await page.locator('#title').selectOption('The Butcher');await page.reload();assert.equal(await page.locator('#title').inputValue(),'The Butcher');assert.equal(await page.locator('#title option[value="The World Eater"]').count(),0);
for(const name of ["Vex O'Night",'Lady Ash-Wing','mIxEd CaSe','The Ancient Calamity of Midnight','鬼王 🦇']){await page.locator('#name').fill(name);await page.reload();assert.equal(await page.locator('#name').inputValue(),name);}
await page.setViewportSize({width:390,height:844});await page.locator('#recordsButton').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'test-results/records-mobile-v3.png'});
const storageFree=await browser.newContext();await storageFree.addInitScript(()=>{Object.defineProperty(window,'localStorage',{get(){throw Error('Unavailable');}});});const offline=await storageFree.newPage();await offline.goto('http://127.0.0.1:4173');await offline.locator('#name').fill('No Storage');await offline.locator('#startForm button[type=submit]').click();assert.equal(await offline.locator('#hudName').textContent(),'No Storage');assert.deepEqual(errors,[]);console.log('Protected progression fixture earns record through real kills and a near-threshold title; title equip/reload, separate grids, mobile width, fantasy names, unavailable storage pass.');await browser.close();
