import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
const source=await readFile(new URL('../public/sw.js',import.meta.url),'utf8');
async function request({full=false,unavailable=false,module=false,imageHit=false,version='24',moduleVersion=''}={}){const listeners={},hit=module?new Response('current module'):imageHit?new Response('cached image'):undefined;let fetched=0;vm.runInNewContext(source.replace('__BUILD_HASH__','build-test').replace("const ASSETS=['./','index.html'];","const ASSETS=['./','index.html','src/main.js'];"),{URL,Request,self:{registration:{scope:'https://test.invalid/monster-mash/'},addEventListener:(name,fn)=>listeners[name]=fn},caches:{open:async()=>{if(unavailable)throw Error('Storage denied');return {match:async req=>moduleVersion&&typeof req!=='string'?undefined:hit,put:async()=>{if(full)throw Error('QuotaExceededError');}};}},fetch:async()=>{fetched++;return new Response('downloaded image',{status:200});}});let result;listeners.fetch({request:new Request('https://test.invalid/monster-mash/'+(module?'src/main.js'+(moduleVersion?'?v='+moduleVersion:''):'assets/monsters/sovereign/selection-base.webp?v='+version)),respondWith:p=>result=p});return {text:await(await result).text(),fetched};}
test('full or inaccessible browser storage cannot discard a successful artwork download',async()=>{for(const options of [{full:true},{unavailable:true}])assert.deepEqual(await request(options),{text:'downloaded image',fetched:1});});
test('a running service-worker build keeps its cached modules coherent until safe activation',async()=>assert.deepEqual(await request({module:true}),{text:'current module',fetched:0}));

test('immutable artwork is served locally only when its version matches the worker build',async()=>{assert.deepEqual(await request({imageHit:true,version:'build-test'}),{text:'cached image',fetched:0});assert.deepEqual(await request({imageHit:true,version:'next-build'}),{text:'downloaded image',fetched:1});});

test('a versioned module never falls back to another worker build',async()=>{assert.deepEqual(await request({module:true,moduleVersion:'build-test'}),{text:'current module',fetched:0});assert.deepEqual(await request({module:true,moduleVersion:'next-build'}),{text:'downloaded image',fetched:1});});
