import test from 'node:test';import assert from 'node:assert/strict';
import {Game} from '../src/simulation.ts';import {COURT,COURT_RULES,COURT_TEST_RULES,spawnCourtHunt,updateCourt,breakCourtGuard,rulesForStage,courtContactScale,initializeCourt,chooseCourtUpgrade,upgradeRank,courtMission,courtProgress,courtScorePolicy,courtSpeedBonus,courtGuardCover} from '../src/stage-two.ts';
import {COURT_RADIUS,COURT_REGIONS,COURT_SITES,COURT_SHRINES,COURT_SEARCH_ROUTE,insideCourt,slideCourt,courtSteer} from '../src/court-map.ts';
import {localStageTest} from '../src/local-stage-test.ts';import {ENEMIES,EVENT} from '../src/data.ts';
import {dominate,addServant,updateServants} from '../src/servants.ts';import {createIdentity} from '../src/identity.ts';
import {encodeRun,decodeRun,validateRun} from '../src/run-code.ts';
const idle={x:0,y:0,aimX:0,aimY:0,aiming:false};
const fixture=(id='titan')=>{const g=new Game(77,{monsterId:id},1);g.wave=1;assert.ok(spawnCourtHunt(g));g.rebuildGrid();return g;};
const captain=g=>g.enemies.find(e=>e.active&&e.court?.role==='captain');
test('Court hunts belong only to Stage 2 and use separated sectors with finite captains and launchable vanguards',()=>{
 const g=fixture(),first=captain(g);assert.equal(g.enemies.filter(e=>e.active&&e.court?.role==='vanguard').length,4);assert.ok(g.enemies.filter(e=>e.active&&['thrall','hound'].includes(e.kind)).length>=10);assert.equal(first.kind,'brute');assert.ok(Math.hypot(first.x,first.y)>400);assert.ok(spawnCourtHunt(g));const chiefs=g.enemies.filter(e=>e.active&&e.court?.role==='captain');assert.ok(Math.hypot(chiefs[0].x-chiefs[1].x,chiefs[0].y-chiefs[1].y)>600);assert.ok(spawnCourtHunt(g));
 assert.equal(new Game(77,{},0).court,null);assert.equal(new Game(77,{},2).court,null);assert.equal(rulesForStage(0),EVENT.rules);assert.equal(rulesForStage(1),COURT_RULES);
});
test('ten seeded camps activate on approach, rather than timed replacement hunts',()=>{const g=new Game(77,{},1);g.time=700;updateCourt(g,.01);assert.equal(g.court.camps.length,10);assert.equal(g.court.stats.hunts,0);g.player.x=g.court.camps[0].x;g.player.y=g.court.camps[0].y;updateCourt(g,.01);assert.ok(g.court.stats.hunts>=1);assert.equal(g.court.camps[0].spawned,true);const same=new Game(77,{},1),other=new Game(123,{},1);initializeCourt(same);initializeCourt(other);assert.deepEqual(same.court.camps.map(c=>[c.x,c.y]),g.court.camps.map(c=>[c.x,c.y]));assert.notDeepEqual(other.court.camps,same.court.camps);});
test('vanguards hold separated home positions for distant champions and engage once the sector is approached',()=>{
 const g=fixture(),guards=g.enemies.filter(e=>e.active&&e.court?.role==='vanguard'),homes=guards.map(e=>({x:e.x,y:e.y}));assert.equal(new Set(guards.map(e=>e.court.homeX+':'+e.court.homeY)).size,4);
 g.update(.1,idle);guards.forEach((e,i)=>assert.ok(Math.hypot(e.x-homes[i].x,e.y-homes[i].y)<1));const e=guards[0];g.player.x=e.x-200;g.player.y=e.y;const x=e.x;g.update(.1,idle);assert.ok(e.x<x-1);
});
test('Court troop protection is paired with lower contact damage; ordinary enemies retain their exact damage',()=>{
 for(const [role,damage] of [['vanguard',22.5],['captain',24],[null,50]]){const g=fixture('sovereign'),e=role?g.enemies.find(e=>e.court?.role===role):g.spawn('brute');for(const other of g.enemies)if(other!==e)other.active=false;g.alive=1;g.attack=100;e.x=20;e.y=0;g.rebuildGrid();g.update(.01,idle);assert.ok(Math.abs((1000-g.player.hp)-damage)<1e-8);addServant(g,e.x,e.y,'summoned');g.rebuildGrid();updateServants(g,.01);assert.ok(Math.abs((220-g.servants[0].hp)-damage*.55)<1e-8);}
});
test('frontal guards absorb finite damage; rear attacks bypass it; repeated ordinary damage always breaks it',()=>{
 const g=fixture(),e=captain(g),hp=e.hp;e.court.facing=0;g.damage(e,100,'meteor',{x:e.x+100,y:e.y});assert.equal(e.hp,hp-40);assert.equal(e.court.guard,e.court.maxGuard-60);
 g.damage(e,100,'direct',{x:e.x-100,y:e.y});assert.equal(e.hp,hp-140);assert.equal(e.court.guard,e.court.maxGuard-85);
 for(let n=0;n<20&&e.active;n++)g.damage(e,80,'summoned',{x:e.x+100,y:e.y});assert.equal(e.court.guard,0);assert.equal(e.court.broken,true);assert.equal(g.court.stats.guards,1);
});
test('Titan launch breaks guard immediately, retains actual knockback, and awards its bonus once',()=>{
 const g=fixture(),e=g.enemies.find(e=>e.active&&e.court?.role==='vanguard');g.player.x=e.x-80;g.player.y=e.y;g.rebuildGrid();const hp=e.hp;g.area(g.player.x,g.player.y,100,50,'launch',1300);assert.equal(e.court.guard,0);assert.equal(e.hp,hp-50*g.releaseStats.damage);assert.ok(e.vx>1000);const guards=g.court.stats.guards;breakCourtGuard(g,e);assert.equal(g.court.stats.guards,guards);
});
test('impact and close-hunt bonuses reward positioning once; ranged and servant kills can also earn a close hunt',()=>{
 for(const [id,source] of [['devourer','lunge'],['titan','trample'],['sovereign','shockwave'],['calamity','meteor'],['overlord','summoned']]){const g=fixture(id),e=captain(g);g.player.x=e.x-150;g.player.y=e.y;const impact=['lunge','trample','shockwave'].includes(source);g.damage(e,1e6,source);assert.equal(g.court.stats.close,1);assert.equal(g.court.stats.impacts,impact?1:0);assert.equal(g.court.stats.bonus,COURT.guardBonus+COURT.closeBonus+(impact?COURT.impactBonus:0));g.damage(e,1e6,source);assert.equal(g.court.stats.close,1);}
});
test('every kit and every spell/servant source can defeat a guarded captain; there is no magic or army immunity',()=>{
 for(const [id,source] of [['devourer','execute'],['titan','trample'],['sovereign','beam'],['calamity','meteor'],['overlord','controlled'],['overlord','summoned'],['overlord','dot'],['overlord','chain']]){const g=fixture(id),e=captain(g);assert.equal(g.damage(e,(e.maxHp+e.court.maxGuard+1)*2,source,{x:e.x+100,y:e.y}),true,id+' '+source);assert.equal(g.court.stats.captains,1);assert.equal(g.court.seals.length,1);}
});
test('Overlord can convert lesser escorts without stealing the hunt objective or converting armored units',()=>{
 const g=fixture('overlord'),e=captain(g);g.player.x=e.x;g.player.y=e.y;g.rebuildGrid();assert.ok(dominate(g,300,12)>=10);assert.ok(captain(g).active);assert.equal(g.court.stats.captains,0);assert.equal(g.court.seals.length,0);assert.equal(g.score.kills,0);
});
test('a ranged or servant kill drops a seal; only champion contact claims the fixed bonus, once, without healing or Carnage',()=>{
 const g=fixture('overlord'),e=captain(g);g.damage(e,1e6,'controlled');assert.equal(g.court.stats.seals,0);const before=g.score.dominance,carnage=g.score.carnage,hp=g.player.hp;updateCourt(g,.1);assert.equal(g.score.dominance,before);g.player.x=g.court.seals[0].x;g.player.y=g.court.seals[0].y;updateCourt(g,.1);assert.equal(g.score.dominance,before+COURT.sealBonus);assert.equal(g.score.carnage,carnage);assert.equal(g.player.hp,hp);assert.equal(g.court.stats.seals,1);updateCourt(g,.1);assert.equal(g.score.dominance,before+COURT.sealBonus);
});
test('knocked-outside captains drop reachable seals and unclaimed seals expire with no score',()=>{
 const g=fixture(),e=captain(g);e.x=COURT_RADIUS+500;e.y=500;g.damage(e,1e6,'launch');const seal=g.court.seals[0];assert.ok(Math.hypot(seal.x,seal.y)<COURT_RADIUS-60);const before=g.score.dominance;updateCourt(g,COURT.sealLife+.1);assert.equal(g.court.seals.length,0);assert.equal(g.court.stats.lost,1);assert.equal(g.score.dominance,before);
});
test('only ten captains can spawn; persistent guards survive distant travel; pooled enemies shed Court tags',()=>{const g=fixture();const first=captain(g),guard=g.enemies.find(e=>e.court?.role==='vanguard');g.update(.01,idle);assert.ok(first.active);assert.ok(guard.active);for(let i=0;i<10;i++){const e=captain(g);g.damage(e,1e8,'execute');if(i<9&&!captain(g))assert.ok(spawnCourtHunt(g));}assert.equal(spawnCourtHunt(g),false);assert.equal(g.court.stats.captains,10);assert.equal(g.court.cleared,true);assert.equal(g.ended,true);assert.equal(g.court.seals.length,9);assert.equal(g.court.stats.seals,1);assert.equal(g.spawn('thrall').court,undefined);});
test('local playtest bypass is explicit and loopback-only, with separate test rules',()=>{
 for(const hostname of ['localhost','127.0.0.1','[::1]'])assert.equal(localStageTest({hostname,search:'?stage2-test=1'}),true);
 for(const hostname of ['almatter.github.io','stage2.invalid','192.168.1.4','localhost.attacker.test'])assert.equal(localStageTest({hostname,search:'?stage2-test=1'}),false);
 assert.equal(localStageTest({hostname:'localhost',search:''}),false);assert.equal(localStageTest({hostname:'localhost',search:'?stage2-test=0'}),false);assert.equal(rulesForStage(1,true),COURT_TEST_RULES);
});
const courtRun=(testing,rules=testing?COURT_TEST_RULES:COURT_RULES)=>{const identity=createIdentity({monsterId:'devourer'}),p=courtScorePolicy(rules),bonus=p.sealBonus+5*p.guardBonus+2*p.impactBonus+p.closeBonus;return {version:4,rules,phase:1,...identity,seed:77,duration:120,score:bonus+4000,kills:17,wave:5,elites:0,titans:0,multi:5,peak:2,feats:{},ended:'2026-10-01T18:00:00Z',reason:'retired',release:4,build:'0123456789abcdef',court:{hunts:3,captains:1,guards:5,impacts:2,close:1,seals:1,lost:0,bonus},mission:{upgrades:[],cleared:false,total:10,scoring:{combat:1000,captain:3000,speed:0}},testing};};
test('Court stats and explicit local test markers survive authenticated codes while Stage 1 retains the old format',async()=>{
 for(const testing of [true,false]){const run=courtRun(testing),decoded=await decodeRun(await encodeRun(run));assert.deepEqual(decoded.court,run.court);assert.equal(decoded.testing,testing);assert.equal(decoded.rules,run.rules);}
 const old={...courtRun(false),rules:EVENT.rules};delete old.court;delete old.testing;delete old.mission;old.release=0;assert.equal((await decodeRun(await encodeRun(old))).court,undefined);
});
test('Court codes reject a wrong stage, inflated bonus, inconsistent seal claims or disguised test runs',()=>{
 const r=courtRun(false);for(const bad of [{...r,phase:0},{...r,court:{...r.court,bonus:17001}},{...r,court:{...r.court,seals:2,bonus:32000}},{...r,testing:true},{...r,rules:COURT_TEST_RULES,testing:false},{...r,rules:EVENT.rules}])assert.throws(()=>validateRun(bad));
});

test('captain defeat pauses the simulation and powers until a valid boon is chosen; progress never follows elapsed time',()=>{const g=fixture('devourer');g.time=700;g.update(.01,idle);assert.equal(g.release,4);const e=captain(g);g.damage(e,1e8,'execute');const time=g.time,hp=g.player.hp;g.update(5,idle);g.hurt(100);assert.equal(g.time,time);assert.equal(g.player.hp,hp);assert.equal(g.cast(0),false);assert.equal(chooseCourtUpgrade(g,'invented'),false);assert.equal(chooseCourtUpgrade(g,'haste'),true);assert.equal(chooseCourtUpgrade(g,'power'),false);assert.equal(upgradeRank(g,'haste'),1);assert.ok(g.releaseStats.move>1);g.update(.01,idle);assert.ok(g.time>time);});
test('boons are capped at three ranks and reset between missions; vitality increases actual HP, reach and recharge affect actual casts',()=>{const g=fixture('calamity');g.court.pending=9;for(let i=0;i<3;i++)assert.ok(chooseCourtUpgrade(g,'haste'));assert.equal(chooseCourtUpgrade(g,'haste'),false);g.player.hp=100;chooseCourtUpgrade(g,'vitality');assert.equal(g.player.maxHp,720*1.15);assert.ok(g.player.hp>300);chooseCourtUpgrade(g,'reach');chooseCourtUpgrade(g,'recharge');g.court.pending=0;g.update(.01,idle);const base=g.powers[1];g.cast(1,{x:g.player.x,y:g.player.y});assert.ok(g.fields[0].radius>base.radius);assert.ok(g.cooldowns[1]<base.cooldown);assert.deepEqual(new Game(77,{},1).court.upgrades,[]);});
test('captains grow tougher after a kill, close pressure and Execution help hunters, and collision overlap is throttled',()=>{const g=fixture('devourer');spawnCourtHunt(g);const [a,b]=g.enemies.filter(e=>e.court?.role==='captain'),hp=b.hp;g.damage(a,1e8,'execute');assert.ok(b.hp>hp);assert.equal(b.court.tier,1);g.court.pending=0;b.court.guard=0;g.player.x=b.x+80;g.player.y=b.y;const before=b.hp;g.damage(b,100,'execute');assert.ok(before-b.hp>=b.maxHp*.055-1e-8);const pre=b.hp;g.damage(b,100,'collision');g.damage(b,100,'collision');assert.equal(pre-b.hp,562.5);});
test('Stage 2 bounds and rock collision are independent of the ritual arena',()=>{const g=new Game(77,{},1),old=new Game(77,{},0);assert.equal(g.arenaRadius,COURT_RADIUS);assert.equal(old.arenaRadius,1500);const rock=COURT_REGIONS[0],body={x:rock.x,y:rock.y};slideCourt(body,23);assert.ok(insideCourt(body.x,body.y,23-.01));g.player.x=2050;g.player.y=-850;g.update(.01,idle);assert.ok(g.player.x>1500);});
test('a clear outcome and chosen upgrades roundtrip with Final Release from entry; impossible clears are rejected',async()=>{const r=courtRun(true);r.duration=660;r.wave=23;r.reason='cleared';r.release=4;r.kills=20000;r.court={hunts:10,captains:10,guards:50,impacts:20,close:8,seals:10,lost:0,bonus:10*COURT.sealBonus+50*COURT.guardBonus+20*COURT.impactBonus+8*COURT.closeBonus};r.mission={upgrades:['power','power','power','recharge','recharge','recharge','haste','haste','haste'],cleared:true,total:10,scoring:{combat:0,captain:30000,speed:courtSpeedBonus(r.duration)}};r.score=r.court.bonus+r.mission.scoring.captain+r.mission.scoring.speed;const decoded=await decodeRun(await encodeRun(r));assert.deepEqual(decoded.mission,r.mission);assert.equal(decoded.reason,'cleared');assert.throws(()=>validateRun({...r,court:{...r.court,captains:9}}));assert.throws(()=>validateRun({...r,release:3}));assert.throws(()=>validateRun({...r,mission:{...r.mission,upgrades:Array(9).fill('power')}}));});

test('Stage 2 reserves captain drain for Devour, keeps meaningful bounded kit sustain and gives shrine recovery on independent cooldowns',()=>{const g=fixture('devourer'),e=captain(g);e.court.guard=0;g.player.hp=200;g.damage(e,10000,'direct');assert.equal(g.player.hp,200);g.heal(100);assert.equal(g.player.hp,275);g.ward(100,200,4);assert.equal(g.shield,40);g.player.x=0;g.player.y=0;updateCourt(g,.01);assert.equal(g.court.healingVisits,1);const hp=g.player.hp;updateCourt(g,.01);assert.equal(g.player.hp,hp);g.player.hp=100;g.time=90;updateCourt(g,.01);assert.equal(g.court.healingVisits,2);const old=new Game(77,{},0);old.player.hp=200;old.heal(100);assert.equal(old.player.hp,300);old.ward(100,200,4);assert.equal(old.shield,100);});
test('every captain site and shrine is reachable through fixed canyon pathways',()=>{for(const target of [...COURT_SITES,...COURT_SHRINES]){assert.ok(insideCourt(target.x,target.y,24));const body={x:0,y:0};for(let i=0;i<10000&&Math.hypot(body.x-target.x,body.y-target.y)>70;i++){const d=courtSteer(body.x,body.y,target.x,target.y);body.x+=d.x*5;body.y+=d.y*5;slideCourt(body,23);}assert.ok(Math.hypot(body.x-target.x,body.y-target.y)<=70,JSON.stringify({target,body}));}});
test('public test directory is explicit while normal public pages still enforce stage access',()=>{for(const hostname of ['almatter.github.io','stage2.invalid']){assert.equal(localStageTest({hostname,search:'',pathname:'/monster-mash/stage2-test/'}),true);assert.equal(localStageTest({hostname,search:'?stage2-test=1',pathname:'/monster-mash/'}),false);}});
test('attack-speed and sustained-duration boons affect real combat without changing dash distances',()=>{for(const boon of ['tempo','duration']){const g=fixture('devourer');g.court.pending=1;chooseCourtUpgrade(g,boon);const e=captain(g);g.player.x=e.x-90;g.player.y=e.y;g.rebuildGrid();if(boon==='tempo'){g.update(.01,idle);assert.ok(g.attack<g.monster.basic.interval*g.releaseStats.attack);}else{g.cast(3);assert.equal(g.frenzy,g.powers[3].duration*1.2);g.cast(0);assert.equal(g.dash.remaining,g.powers[0].duration);}}});

test('captain pressure kills a stationary fully released champion before idle basic attacks can finish the hunt',()=>{for(const id of ['devourer','titan','sovereign','calamity','overlord']){const g=fixture(id),e=captain(g);g.player.x=e.x-70;g.player.y=e.y;for(const other of g.enemies)if(other!==e)other.active=false;g.alive=1;g.spawn=()=>undefined;for(let frame=0;frame<60*90&&!g.ended;frame++)g.update(1/60,idle);assert.equal(g.ended,true,id);assert.equal(g.court.cleared,false,id);assert.ok(g.time<60,id+' '+g.time);}});
test('hunt rewards distinguish partial hunts, complete speed runs and max-rank choices',()=>{const g=fixture();g.court.stats.captains=10;g.court.stats.guards=50;g.court.stats.close=8;g.court.upgrades=['tempo','tempo','tempo','duration','duration','duration','haste','haste','haste'];g.time=660;assert.equal(courtProgress(g,true).values.courtClears,0);g.court.cleared=true;const p=courtProgress(g,true);assert.equal(p.values.courtClears,1);assert.equal(p.best.courtFastClear,1);assert.equal(p.best.courtSwiftClear,0);assert.equal(p.best.courtTempoClear,1);assert.equal(p.best.courtDurationClear,1);assert.equal(p.best.courtHasteClear,1);assert.equal(courtProgress(new Game(77,{},0),true).values.courtCaptains,undefined);});
test('duration extends actual Titan barriers, Sovereign rage and Overlord servants at the first rank',()=>{for(const id of ['titan','sovereign','overlord']){const g=fixture(id);g.court.pending=1;chooseCourtUpgrade(g,'duration');if(id==='titan'){g.ward(100,200,8);assert.equal(g.shieldTime,9.6);}if(id==='sovereign'){g.cast(1);assert.ok(Math.abs(g.player.rage-7.2)<1e-8);}if(id==='overlord'){g.cast(2);assert.ok(g.servants.some(s=>s.active&&Math.abs(s.life-21.6)<1e-8));}}});
test('previous Court hunt codes remain readable after the Stage 2 rules advance',async()=>{for(const version of [16,17,18,19,20,21,22,23])for(const testing of [true,false]){const r=courtRun(testing,'2026.10-v'+version+'-court-'+(testing?'test':'hunts'));r.release=version>=19?4:0;if(version<18)delete r.mission.scoring;assert.equal((await decodeRun(await encodeRun(r))).rules,r.rules);}});
