import test from 'node:test';import assert from 'node:assert/strict';
import {Game} from '../src/simulation.ts';import {initializeCourt} from '../src/stage-two.ts';
import {COURT_REGIONS,COURT_SITE_GROUPS,COURT_SITES,insideCourt,slideCourt,courtArtVisible,courtSteer} from '../src/court-map.ts';
test('five authored regions each select two distinct captains from four pockets with deterministic varied occupancy',()=>{
 assert.equal(COURT_REGIONS.length,5);assert.equal(COURT_SITES.length,20);const seen=COURT_SITE_GROUPS.map(()=>new Set());for(let seed=1;seed<=100;seed++){const g=new Game(Math.imul(seed,2654435761)>>>0,{},1);initializeCourt(g);assert.equal(g.court.camps.length,10);assert.equal(new Set(g.court.camps.map(c=>c.x+':'+c.y)).size,10);COURT_SITE_GROUPS.forEach((group,i)=>{const selected=g.court.camps.filter(c=>group.some(p=>p.x===c.x&&p.y===c.y));assert.equal(selected.length,2);selected.forEach(c=>seen[i].add(c.x+':'+c.y));});}seen.forEach(choices=>assert.equal(choices.size,4));
});
test('district scenery blocks its central structure but leaves captain ground and multiple clear retreat routes walkable',()=>{for(const r of COURT_REGIONS)assert.equal(insideCourt(r.x,r.y,23),false);for(const p of COURT_SITES){assert.equal(insideCourt(p.x,p.y,80),true);assert.ok([0,Math.PI/2,Math.PI,Math.PI*1.5].filter(angle=>insideCourt(p.x+Math.cos(angle)*220,p.y+Math.sin(angle)*220,23)).length>=3);const body={x:p.x,y:p.y};slideCourt(body,23);assert.deepEqual(body,{x:p.x,y:p.y});}});
test('partly visible section artwork remains visible at every camera edge',()=>{for(const angle of [0,Math.PI/2,Math.PI/4]){const width=516,height=516,hw=(Math.abs(Math.cos(angle))*width+Math.abs(Math.sin(angle))*height)/2,hh=(Math.abs(Math.sin(angle))*width+Math.abs(Math.cos(angle))*height)/2;for(const sign of [-1,1]){assert.ok(courtArtVisible(sign*(600+hw-1),0,width,height,angle,0,0,600,380));assert.ok(courtArtVisible(0,sign*(380+hh-1),width,height,angle,0,0,600,380));assert.equal(courtArtVisible(sign*(600+hw+33),0,width,height,angle,0,0,600,380),false);}}});
test('following any of the five visible district roads reveals a captain within two minutes without hidden-site knowledge',()=>{
 for(const id of ['devourer','titan','sovereign','calamity','overlord'])for(const seed of [77,123,444])for(const region of COURT_REGIONS){const g=new Game(seed,{monsterId:id},1);g.seedOpening();const route=COURT_SITES.filter(p=>p.region===region.id);let stop=0,visible=false;for(let frame=0;frame<120*30&&!g.ended&&!visible;frame++){const p=route[stop%4];if(Math.hypot(p.x-g.player.x,p.y-g.player.y)<100)stop++;const d=courtSteer(g.player.x,g.player.y,p.x,p.y);g.setMovementDirection(d.x,d.y);g.update(1/30,{...d,aimX:p.x,aimY:p.y,aiming:false});visible=g.enemies.some(e=>e.active&&e.court?.role==='captain'&&Math.abs(e.x-g.player.x)<543&&Math.abs(e.y-g.player.y)<323);}assert.ok(visible,id+' '+seed+' '+region.id+' '+g.time);}
});
