import test from 'node:test';
import assert from 'node:assert/strict';
import {Game} from '../src/simulation.ts';
import {MONSTERS,ABILITIES} from '../src/content-monsters.ts';
import {createTitanRealm,viableRelicSolution,RELIC_POOLS,realmSummary,realmDamage,claimRelic,equipRelic,restoreNativePower,realmTraits,TITAN_REALM_TEST_RULES,SWARM_TEST_RULES} from '../src/stage-three.ts';
import {REALM_GROTTOS,REALM_START,REALM_LANES,insideRealm,slideRealm,realmWaypoint} from '../src/titan-realm-map.ts';
import {rulesForStage} from '../src/stage-two.ts';
import {encodeRun,decodeRun,validateRun} from '../src/run-code.ts';
import {runOutcome,resultText} from '../src/results.ts';
const idle={x:0,y:0,aimX:0,aimY:0,aiming:false};
function game(nature='sovereign',seed=12){const g=new Game(seed,{monsterId:nature},2);g.seedOpening();return g;}
function record(g,reason='retired'){return {version:4,rules:TITAN_REALM_TEST_RULES,phase:2,name:g.identity.name,title:g.identity.title,monsterId:g.monster.id,colors:g.identity.colors,seed:g.seed,duration:Math.floor(g.time),score:g.score.dominance,kills:g.score.kills,wave:g.wave,elites:g.score.elites,titans:g.score.titans,multi:g.score.largestMulti,peak:Number(g.score.peak.toFixed(2)),feats:{},ended:'2026-10-08T12:00:00Z',reason,release:4,build:'1234567890abcdef',testing:true,realm:realmSummary(g)};}
test('random relic offerings always contain an obtainable four-nature solution with recovery and burst',()=>{for(let seed=1;seed<=2000;seed++){const g=game('titan',seed),s=g.realm;assert.ok(viableRelicSolution(s.relics,s.pattern));assert.equal(new Set(s.pattern).size,4);assert.equal(new Set(s.relics.map(r=>r.shrine)).size,6);assert.equal(s.shrines.length,7);assert.ok(s.relics.every(r=>!r.known&&RELIC_POOLS[r.nature].includes(r.ability)));assert.equal(s.shrines[6].decor,'dormant');}assert.deepEqual(game('titan',55).realm.pattern,game('titan',55).realm.pattern);assert.notDeepEqual(game('titan',55).realm.pattern,game('titan',56).realm.pattern);});
test('all grottos and altar interaction areas are reachable without walking across scenery',()=>{for(const destination of REALM_GROTTOS){let p={...REALM_START},goal={x:destination.x,y:destination.y-120};assert.ok(insideRealm(goal.x,goal.y,24));for(let i=0;i<6000&&Math.hypot(p.x-goal.x,p.y-goal.y)>30;i++){const waypoint=realmWaypoint(p.x,p.y,goal.x,goal.y),d=Math.hypot(waypoint.x-p.x,waypoint.y-p.y)||1;p.x+=(waypoint.x-p.x)/d*4;p.y+=(waypoint.y-p.y)/d*4;slideRealm(p,24);assert.ok(insideRealm(p.x,p.y,24));}assert.ok(Math.hypot(p.x-goal.x,p.y-goal.y)<30,'unreachable grotto '+destination.id);assert.equal(insideRealm(destination.x,destination.y-350,24),false,'altar pedestal is scenery');}for(const lane of REALM_LANES){const p={x:(lane.a.x+lane.b.x)/2,y:(lane.a.y+lane.b.y)/2};assert.ok(insideRealm(p.x,p.y,24));}});
test('wrong powers cannot bypass a defense, overkill stops at each gate, and reward cannot be farmed by resetting',()=>{const g=game(),s=g.realm,b=s.boss;g.player.x=0;g.player.y=100;s.engaged=true;s.pattern=['sovereign','titan','calamity','reaper'];assert.equal(g.damage(b,1e9,'direct'),false);assert.equal(b.hp,b.maxHp);for(let i=0;i<3;i++){g.damage(b,1e9,'relic:'+s.pattern[i]+':ability');assert.equal(b.hp,b.maxHp*(3-i)/4);assert.equal(s.layer,i+1);assert.equal(s.open,false);}assert.equal(s.objective,1800000);g.player.x=0;g.player.y=800;for(let i=0;i<190;i++)g.update(1/60,idle);assert.equal(s.layer,0);assert.equal(b.hp,b.maxHp);assert.equal(s.resets,1);g.player.x=0;g.player.y=100;s.engaged=true;for(let i=0;i<4;i++)g.damage(b,1e9,'relic:'+s.pattern[i]+':ability');assert.ok(s.cleared);assert.equal(s.objective,5600000);assert.equal(g.ended,true);assert.equal(g.score.titans,1);});
test('outside the seal neither damage nor delayed servant/projectile hits can damage the titan',()=>{const g=game(),s=g.realm,b=s.boss;s.pattern[0]='overlord';s.engaged=true;g.player.x=0;g.player.y=800;g.damage(b,1000,'summoned',{x:0,y:0});assert.equal(b.hp,b.maxHp);g.player.y=100;g.damage(b,1000,'summoned',{x:0,y:800});assert.equal(b.hp,b.maxHp);});
test('all 24 borrowed powers can actually breach their nature defense on another champion',()=>{for(const [nature,ids] of Object.entries(RELIC_POOLS))for(const id of ids){const g=game(nature==='sovereign'?'titan':'sovereign');g.player.x=0;g.player.y=100;g.player.hp=g.player.maxHp=100000;g.realm.engaged=true;g.realm.pattern[0]=nature;g.powers[0]=ABILITIES[id];g.relicOwners[0]=nature;g.setMovementDirection(0,-1);g.targetView={x:600,y:450};if(id==='command'){const e=g.spawn('hound');Object.assign(e,{x:20,y:130,hp:500,maxHp:500});}g.rebuildGrid();assert.ok(g.cast(0,['meteor','vortex','graveshift','reapingarc'].includes(id)?{x:0,y:0}:undefined),id+' should cast');for(let i=0;i<900&&!g.realm.breaches;i++)g.update(1/60,idle);assert.ok(g.realm.breaches>0,nature+' '+id+' did not breach');}});
test('relics stay mysterious until claimed, replacing powers changes unique traits without changing body identity',()=>{const g=game('overlord'),s=g.realm,r=s.relics.find(r=>r.nature==='devourer'),spot=REALM_GROTTOS[r.shrine];g.player.x=spot.x;g.player.y=spot.y-120;assert.equal(claimRelic(g,r.shrine),false);s.shrines[r.shrine].cleared=true;assert.ok(claimRelic(g,r.shrine));assert.ok(equipRelic(g,r.id,0));assert.equal(g.identity.monsterId,'overlord');assert.ok(realmTraits(g).some(t=>t.id==='devourer'));assert.equal(g.powers[0].id,r.ability);assert.equal(equipRelic(g,r.id,1),false);g.realm.engaged=true;assert.equal(restoreNativePower(g,0),false);g.realm.engaged=false;assert.ok(restoreNativePower(g,0));assert.equal(realmTraits(g).length,1);});
test('titan warnings deal no early damage, impacts punish standing still, and avoidable zones remain bounded',()=>{const g=game(),s=g.realm;g.player.x=0;g.player.y=250;s.engaged=true;s.zones.push({x:0,y:250,radius:100,warning:.5,life:.55,damage:220,hit:false});const hp=g.player.hp;for(let i=0;i<25;i++)g.update(1/60,idle);assert.equal(g.player.hp,hp);for(let i=0;i<9;i++)g.update(1/60,idle);assert.ok(g.player.hp<hp-100);assert.ok(s.zones.length<=12);});
test('realm results survive authenticated roundtrip and reject inflated objectives or hidden defense answers',async()=>{const g=game();g.update(1/60,idle);const r=record(g);assert.deepEqual((await decodeRun(await encodeRun(r))).realm,r.realm);assert.match(resultText(r),/STAGE 3/);assert.match(runOutcome({...r,reason:'overwhelmed'}),/DEPTHS/);assert.throws(()=>validateRun({...r,score:r.score+1}));assert.throws(()=>validateRun({...r,realm:{...r.realm,pattern:g.realm.pattern}}));assert.throws(()=>validateRun({...r,testing:false}));assert.throws(()=>validateRun({...r,reason:'cleared'}));});
test('all-stage tester results are separate while shipped Stage 1 and Stage 2 rules stay unchanged',async()=>{for(const nature of Object.keys(MONSTERS)){assert.equal(rulesForStage(0,true,nature),SWARM_TEST_RULES);const g=new Game(1,{monsterId:nature},0);g.update(1/60,idle);const r={...record(game(nature)),rules:SWARM_TEST_RULES,phase:0,release:0,realm:undefined,score:0,kills:0,titans:0,elites:0,wave:1};assert.equal((await decodeRun(await encodeRun(r))).testing,true);}assert.equal(rulesForStage(0,false,'sovereign'),'2026.10-v15-autotarget-squad');assert.equal(rulesForStage(1,false,'titan'),'2026.10-v33-court-hunts');});

test('route steering handles every grotto pair and multiple movement speeds without corner traps',()=>{for(const a of REALM_GROTTOS)for(const b of REALM_GROTTOS){let p={x:a.x,y:a.y-120},goal={x:b.x,y:b.y-120};for(let i=0;i<6000&&Math.hypot(p.x-goal.x,p.y-goal.y)>30;i++){const next=realmWaypoint(p.x,p.y,goal.x,goal.y),d=Math.hypot(next.x-p.x,next.y-p.y)||1,step=Math.min(d,7);p.x+=(next.x-p.x)/d*step;p.y+=(next.y-p.y)/d*step;slideRealm(p,23);}assert.ok(Math.hypot(p.x-goal.x,p.y-goal.y)<30,a.id+' to '+b.id);}});
test('grotto guardians resist conversion and Feast titan hits share its capped recovery reserve',()=>{const g=game('overlord');g.player.x=g.player.y=0;g.realm.engaged=true;const h=g.spawn('hound');Object.assign(h,{x:50,y:0,realm:{role:'guardian',shrine:0,homeX:50,homeY:0,variant:2}});g.rebuildGrid();g.cast(0);assert.ok(h.active);g.frenzy=8;g.frenzyHealing=10;g.player.hp=100;g.realm.pattern[0]='devourer';g.damage(g.realm.boss,1000,'direct');assert.equal(g.frenzyHealing,0);assert.equal(g.player.hp,110);g.damage(g.realm.boss,1000,'direct');assert.equal(g.player.hp,110);});

test('borrowed Lunge retains three rapid charges in any slot and refills them at its donor cooldown',()=>{const g=game('sovereign');g.powers[2]=ABILITIES.rendlunge;g.relicOwners[2]='devourer';g.lungeCharges=3;g.player.hp=g.player.maxHp=100000;assert.equal(g.maxLungeCharges(),3);for(let i=0;i<3;i++){assert.ok(g.cast(2));assert.equal(g.lungeCharges,2-i);}assert.equal(g.cast(2),false);for(let i=0;i<250;i++)g.update(1/60,idle);assert.ok(g.lungeCharges>=1);assert.ok(g.cast(2));const native=game('devourer');assert.equal(native.lungeCharges,3);});
