import {MONSTERS,type Channel,type Palette} from './content-monsters.ts';
import {compose,type ArtEntry} from './assets.ts';
import {loadProfile,saveProfile,resetProgress} from './profile.ts';
const $=(id:string)=>document.getElementById(id)!;
const monster=$('monster') as HTMLSelectElement;for(const m of Object.values(MONSTERS))monster.add(new Option(m.archetype,m.id));
let catalog:Record<string,ArtEntry>={},files=new Map<string,File>(),pack:Partial<Record<keyof ArtEntry,HTMLCanvasElement>>={},busy=false,dirty=false;
const colors={...MONSTERS.overlord.palette};for(const key of Object.keys(colors) as Channel[]){const label=document.createElement('label'),input=document.createElement('input');label.textContent=key;input.type='color';input.value=colors[key];input.id='color-'+key;input.oninput=()=>{colors[key]=input.value;void refresh();};label.append(input);$('channels').append(label);}
async function localImage(path:string){if(!path.startsWith('assets/')||path.includes('..'))throw Error('Path outside assets: '+path);const file=files.get(path);if(!file)throw Error('Missing '+path);if(!/\.(png|webp)$/i.test(path)||file.size>16*1024*1024)throw Error('Use PNG/lossless WebP under 16 MiB per layer');const url=URL.createObjectURL(file);try{return await new Promise<HTMLImageElement>((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(Error('Invalid image '+path));im.src=url;});}finally{URL.revokeObjectURL(url);}}
async function refresh(){if(busy){dirty=true;return;}busy=true;const entry=catalog[monster.value];pack={};const errors:string[]=[];try{if(!entry)throw Error('No catalog entry for '+monster.value);for(const type of ['gameplay','selection','portrait','cutin'] as (keyof ArtEntry)[]){if(!entry[type]){errors.push(type+': not supplied');continue;}try{pack[type]=await compose(entry[type]!,{...colors} as Palette,type,localImage);errors.push(type+': dimensions and layer registration valid');}catch(e){errors.push(type+': '+String(e));}}const bytes=Object.values(pack).reduce((n,c)=>n+c.width*c.height*4,0);errors.push('Composited set: '+(bytes/1048576).toFixed(1)+' MiB. Verify shading, alpha edges and neutral linework visually.');}catch(e){errors.push(String(e));}finally{busy=false;$('status').textContent=errors.join('\n');if(dirty){dirty=false;void refresh();}}}
($('folder') as HTMLInputElement).onchange=async e=>{files.clear();for(const file of Array.from((e.target as HTMLInputElement).files||[])){const parts=file.webkitRelativePath.split('/');parts.shift();files.set('assets/'+parts.join('/'),file);}try{const file=files.get('assets/catalog.json');if(!file)throw Error('Select the assets folder itself, including catalog.json');const parsed=JSON.parse(await file.text());if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw Error('Catalog must be an object');catalog=parsed;await refresh();}catch(e){pack={};$('status').textContent=String(e);}};
monster.onchange=()=>{for(const key of Object.keys(colors) as Channel[]){colors[key]=MONSTERS[monster.value].palette[key];($('color-'+key) as HTMLInputElement).value=colors[key];}void refresh();};
let previous=0;function draw(stamp:number){requestAnimationFrame(draw);if(stamp-previous<33)return;previous=stamp;const bg=($('background') as HTMLInputElement).value;for(const type of ['gameplay','selection','portrait','cutin'] as const){const canvas=$(type) as HTMLCanvasElement,c=canvas.getContext('2d')!,image=pack[type];c.fillStyle=bg;c.fillRect(0,0,canvas.width,canvas.height);if(type==='gameplay'){const scale=Number(($('scale') as HTMLInputElement).value)*MONSTERS[monster.value].visual.scale,v=MONSTERS[monster.value].visual,state=v.states[($('animation') as HTMLSelectElement).value],frame=Math.floor(stamp/1000*state.fps)%state.frames,x=canvas.width/2,y=canvas.height*.6;c.fillStyle='#0005';c.beginPath();c.ellipse(x,y+12,38*scale,12*scale,0,0,7);c.fill();if(image)c.drawImage(image,frame*256,state.row*256,256,256,x-64*scale,y-80*scale,128*scale,128*scale);if(($('guides') as HTMLInputElement).checked){c.strokeStyle='#ff6666';c.beginPath();c.arc(x,y,23,0,7);c.stroke();c.strokeStyle='#64ffe0';c.beginPath();c.moveTo(x-10,y);c.lineTo(x+10,y);c.moveTo(x,y-10);c.lineTo(x,y+10);c.stroke();}c.fillStyle=colors.power;c.fillRect(12,canvas.height-16,100,4);}else if(image){const s=Math.min(canvas.width/image.width,canvas.height/image.height);c.drawImage(image,(canvas.width-image.width*s)/2,(canvas.height-image.height*s)/2,image.width*s,image.height*s);}}}requestAnimationFrame(draw);
if(['localhost','127.0.0.1','[::1]'].includes(location.hostname)){ $('resetPanel').hidden=false;$('reset').onclick=()=>{if(($('resetText') as HTMLInputElement).value!=='RESET PROGRESSION'){$('resetStatus').textContent='Enter the exact phrase first.';return;}try{const p=loadProfile(localStorage);resetProgress(p);$('resetStatus').textContent=saveProfile(p,localStorage)?'Progression cleared. Reload the game tab.':'Storage unavailable.';}catch{$('resetStatus').textContent='Storage unavailable.';}};}
