export type Palette={primary:string;secondary:string;accent:string;power:string};
export type Channel=keyof Palette;
export type AbilityDef={id:string;name:string;short:string;description:string;symbol:string;cooldown:number;radius:number;damage:number;effect:string;duration?:number};
export type MonsterDef={id:string;archetype:string;rank:string;description:string;hp:number;speed:number;armor:number;basic:{name:string;description:string;damage:number;radius:number;interval:number;ranged:boolean};abilities:string[];passive:{id:string;name:string;description:string};palette:Palette;channels:{id:Channel;label:string}[];visual:{scale:number;assetRoot:string;frameSize:number;states:Record<string,{row:number;frames:number;fps:number}>}};
export const SWATCHES=['#a83248','#202433','#eee5d4','#d9af61','#387ccb','#8862c7','#49b3aa','#8cb865','#d88868','#aab9ce','#e975bc','#705b4b'];
export const BASE_TITLES=['','The Unbound','Scourge of the Dark Continent','The Nameless Terror'];
export const ABILITIES:Record<string,AbilityDef>={
 command:{id:'command',name:"Tyrant's Command",short:'Dominate',description:'Convert up to 12 nearby common enemies into temporary servants. Elites and Titans resist control.',symbol:'♟',cooldown:12,radius:360,damage:1,effect:'dominate',duration:12},
 curse:{id:'curse',name:'Plague of Crowns',short:'Corrupt',description:'Curse nearby enemies for eight seconds. They take damage and explode on death, spreading corruption.',symbol:'◇',cooldown:9,radius:430,damage:55,effect:'curse',duration:8},
 legion:{id:'legion',name:'Graveborn Legion',short:'Raise',description:'Raise eight disposable servants for twelve seconds. Your army is capped at 32.',symbol:'♜',cooldown:16,radius:180,damage:1,effect:'summon',duration:12},
 throne:{id:'throne',name:'Absolute Dominion',short:'Dominion',description:'Corrupt the battlefield, seize weak foes and ignite a massive cascading detonation.',symbol:'✦',cooldown:46,radius:750,damage:240,effect:'dominion'},
 oblivion:{id:'oblivion',name:'Oblivion Ray',short:'Ray',description:'Sweep a high-damage piercing beam for three seconds.',symbol:'ϟ',cooldown:12,radius:720,damage:125,effect:'beam',duration:3},
 meteor:{id:'meteor',name:'Starfall Verdict',short:'Starfall',description:'A meteor strikes 360 units ahead after a 1.2-second warning.',symbol:'◆',cooldown:10,radius:260,damage:650,effect:'meteor',duration:1.2},
 vortex:{id:'vortex',name:'Event Horizon',short:'Vortex',description:'Pull enemies into a damaging field ahead of you for four seconds.',symbol:'◉',cooldown:16,radius:220,damage:70,effect:'vortex',duration:4},
 crimson:{id:'crimson',name:'Crimson Catastrophe',short:'Catastrophe',description:'Erase an enormous area with a signature magical detonation.',symbol:'✦',cooldown:48,radius:850,damage:2200,effect:'blast'},
 rendlunge:{id:'rendlunge',name:'Riftfang Lunge',short:'Lunge',description:'Lunge through prey in your aim direction.',symbol:'➤',cooldown:5,radius:60,damage:100,effect:'lunge',duration:.3},
 maw:{id:'maw',name:'Maw of Ruin',short:'Devour',description:'Eat nearby prey. Healing is capped at 25% of maximum health per cast.',symbol:'♜',cooldown:9,radius:160,damage:520,effect:'devour'},
 execution:{id:'execution',name:'Royal Execution',short:'Execute',description:'Strike the nearest wounded elite within 420 units; otherwise the nearest prey. Double damage below half health.',symbol:'◇',cooldown:11,radius:420,damage:700,effect:'execute'},
 frenzy:{id:'frenzy',name:'Feast of the Unbound',short:'Frenzy',description:'Eight seconds of accelerated claws and damage. Feeding heals at most 20% maximum health in total.',symbol:'✦',cooldown:42,radius:140,damage:1,effect:'frenzy',duration:8},
 worldbreaker:{id:'worldbreaker',name:'World Breaker',short:'Breaker',description:'Shatter nearby ranks and hurl bodies through their allies.',symbol:'◉',cooldown:6,radius:210,damage:145,effect:'shockwave'},
 stampede:{id:'stampede',name:'Iron Stampede',short:'Stampede',description:'Charge in your aim direction, trampling enemies for 0.7 seconds.',symbol:'➤',cooldown:8,radius:85,damage:95,effect:'charge',duration:.7},
 kingfall:{id:'kingfall',name:'Kingfall Throw',short:'Throw',description:'Launch nearby enemies and their remains at extreme speed.',symbol:'♜',cooldown:10,radius:155,damage:150,effect:'launch'},
 heavenfall:{id:'heavenfall',name:'Heavenfall Cataclysm',short:'Heavenfall',description:'A colossal ground impact that scatters entire armies.',symbol:'✦',cooldown:45,radius:580,damage:1800,effect:'blast'},
 rupture:{id:'rupture',name:'Rupture',short:'Rupture',description:'Radial damage and violent knockback.',symbol:'◉',cooldown:6,radius:190,damage:110,effect:'shockwave'},
 devour:{id:'devour',name:'Devour',short:'Devour',description:'Consume nearby prey to heal and enrage.',symbol:'♜',cooldown:10,radius:135,damage:400,effect:'devour'},
 beam:{id:'beam',name:'Death Beam',short:'Beam',description:'Sweep a piercing beam with your aim for 2.5 seconds.',symbol:'ϟ',cooldown:13,radius:680,damage:110,effect:'beam',duration:2.5},
 catastrophe:{id:'catastrophe',name:'Catastrophe',short:'Catastrophe',description:'Annihilate the surrounding horde.',symbol:'✦',cooldown:48,radius:630,damage:1800,effect:'blast'}
};
export const channels:MonsterDef['channels']=[{id:'primary',label:'Body / armor'},{id:'secondary',label:'Mantle / markings'},{id:'accent',label:'Bone / trim'},{id:'power',label:'Eyes / supernatural power'}];
export function visual(id:string,scale=1):MonsterDef['visual']{return {scale,assetRoot:'assets/monsters/'+id,frameSize:256,states:{idle:{row:0,frames:4,fps:6},move:{row:1,frames:6,fps:10},attack:{row:2,frames:6,fps:14},hurt:{row:3,frames:2,fps:10},ultimate:{row:4,frames:6,fps:12}}};}
export const MONSTERS:Record<string,MonsterDef>={
 overlord:{id:'overlord',archetype:'Overlord',rank:'DEMON SOVEREIGN',description:'Make the horde your weapon. Dominate lesser monsters, raise servants and let corruption consume the battlefield.',hp:950,speed:200,armor:1,basic:{name:'Edict of Ruin',description:'Dark bolts automatically strike along your aim.',damage:65,radius:600,interval:.5,ranged:true},abilities:['command','curse','legion','throne'],passive:{id:'ownership',name:'The Crown Owns All',description:'Controlled, summoned and corruption kills earn full Body Count, Dominance and Carnage, with separate source records.'},palette:{primary:'#8862c7',secondary:'#202433',accent:'#aab9ce',power:'#49b3aa'},channels,visual:visual('overlord',1.05)},
 calamity:{id:'calamity',archetype:'Calamity',rank:'LIVING DISASTER',description:'A fragile walking apocalypse. Sweep distant ranks, gather them into a vortex, and call down stars.',hp:720,speed:195,armor:1.08,basic:{name:'Ruin Lance',description:'Automatically fires powerful magic bolts along your aim.',damage:85,radius:650,interval:.42,ranged:true},abilities:['oblivion','meteor','vortex','crimson'],passive:{id:'massacre',name:'Disaster Resonance',description:'A 20+ kill activation grants +0.15 Carnage and reduces other cooldowns by 0.75s, at most once per second.'},palette:{primary:'#387ccb',secondary:'#202433',accent:'#aab9ce',power:'#8862c7'},channels,visual:visual('calamity',.95)},
 devourer:{id:'devourer',archetype:'Devourer',rank:'APEX ABERRATION',description:'A swift, relentless predator. Hunt champions, feed through danger and build lethal momentum.',hp:850,speed:245,armor:1,basic:{name:'Ravenous Fangs',description:'Fast circular claws; attack twice as fast during Frenzy.',damage:45,radius:90,interval:.28,ranged:false},abilities:['rendlunge','maw','execution','frenzy'],passive:{id:'hunger',name:'Predatory Momentum',description:'Recent kills grant up to 25% damage and 15% movement speed. Momentum fades when feeding stops.'},palette:{primary:'#eee5d4',secondary:'#705b4b',accent:'#d9af61',power:'#a83248'},channels,visual:visual('devourer',.92)},
 titan:{id:'titan',archetype:'Titan',rank:'ANCIENT BEAST',description:'An armored catastrophe. Charge into the crowd and turn bodies into siege weapons.',hp:1600,speed:165,armor:.72,basic:{name:'Continental Cleave',description:'Slow, heavy circular impacts. Strongest in crowded melee.',damage:100,radius:125,interval:.7,ranged:false},abilities:['worldbreaker','stampede','kingfall','heavenfall'],passive:{id:'surrounded',name:'Besieged Colossus',description:'Three or more nearby enemies grant 25% damage reduction.'},palette:{primary:'#a83248',secondary:'#202433',accent:'#d9af61',power:'#d88868'},channels,visual:visual('titan',1.25)},
 sovereign:{id:'sovereign',archetype:'Sovereign',rank:'ORIGINAL INCARNATION',description:'The original all-round destroyer. Claws, feeding and overwhelming magic.',hp:1000,speed:205,armor:1,basic:{name:'Sovereign Claws',description:'Automatic circular cleave.',damage:42,radius:95,interval:.45,ranged:false},abilities:['rupture','devour','beam','catastrophe'],passive:{id:'rage',name:'Feeding Rage',description:'Devour grants 40% increased damage for six seconds.'},palette:{primary:'#aab9ce',secondary:'#a83248',accent:'#d9af61',power:'#d88868'},channels,visual:visual('sovereign')}
};
export function paletteFor(monster:MonsterDef,value:unknown):Palette{const output={...monster.palette};if(!value||typeof value!=='object')return output;for(const {id} of monster.channels){const color=(value as Record<string,unknown>)[id];if(typeof color==='string'&&/^#[0-9a-f]{6}$/i.test(color))output[id]=color.toLowerCase();}return output;}
export function validateContent(){for(const m of Object.values(MONSTERS))if(m.abilities.length!==4||!m.abilities.every(id=>ABILITIES[id])||m.hp<=0||m.speed<=0||m.basic.interval<=0)throw Error('Invalid monster '+m.id);for(const a of Object.values(ABILITIES))if(a.cooldown<=0||a.damage<0||a.radius<=0)throw Error('Invalid ability '+a.id);}
