export type Palette={primary:string;secondary:string;accent:string;power:string;skin?:string;hair?:string};
export type Channel=keyof Palette;
export type AbilityDef={id:string;name:string;short:string;description:string;symbol:string;cooldown:number;radius:number;damage:number;effect:string;duration?:number};
// Compact action labels and full fantasy names are paired wherever space permits.
export const abilityLabel=(power:AbilityDef)=>power.short===power.name?power.name:power.short+' · '+power.name;
export type MonsterDef={unlockStage?:number;id:string;archetype:string;rank:string;description:string;hp:number;speed:number;armor:number;basic:{name:string;description:string;damage:number;radius:number;interval:number;ranged:boolean};abilities:string[];passive:{id:string;name:string;description:string};palette:Palette;channels:{id:Channel;label:string}[];visual:{scale:number;assetRoot:string;frameSize:number;facesLeft:boolean;states:Record<string,{row:number;frames:number;fps:number}>}};
export const SWATCHES=['#a83248','#202433','#eee5d4','#d9af61','#387ccb','#8862c7','#49b3aa','#8cb865','#d88868','#aab9ce','#e975bc','#705b4b'];
export const SKIN_SWATCHES=['#f3dfd1','#e4b997','#c68e6a','#a66c49','#784c35','#493127','#aab9ce','#8cb865','#8862c7','#49b3aa','#eee5d4','#202433'];
export const BASE_TITLES=['','The Unbound','Scourge of the Dark Continent','The Nameless Terror'];
export const ABILITIES:Record<string,AbilityDef>={
 soulwrit:{id:'soulwrit',name:'Soul Writ',short:'Writ',description:'Bind a threat inside a spectral court. Repeated soul strikes restore a bounded amount of health.',symbol:'♜',cooldown:13,radius:210,damage:270,effect:'realmrelic',duration:4},
 prismcollapse:{id:'prismcollapse',name:'Prism Collapse',short:'Prism',description:'After a brief warning, collapse a mana prism on a nearby threat and form a small ward.',symbol:'◆',cooldown:12,radius:210,damage:1600,effect:'realmrelic',duration:1},
 bloodthread:{id:'bloodthread',name:'Blood Thread',short:'Thread',description:'Hook the nearest significant threat with a ranged fang tether. Deal heavy damage and drain life within a per-cast limit.',symbol:'◇',cooldown:8,radius:420,damage:950,effect:'realmrelic'},
 gravitonseal:{id:'gravitonseal',name:'Graviton Seal',short:'Gravity',description:'A gravity seal crushes and briefly binds lesser prey, while granting a small barrier.',symbol:'◉',cooldown:14,radius:250,damage:240,effect:'realmrelic',duration:4},
 spellsteel:{id:'spellsteel',name:'Spellsteel Reversal',short:'Reversal',description:'Raise a brief ward, restore a little health and erupt with retaliatory spellsteel strikes.',symbol:'✦',cooldown:12,radius:230,damage:440,effect:'realmrelic',duration:2},
 soulorbit:{id:'soulorbit',name:'Soul Orbit',short:'Orbit',description:'A circling soul blade follows your movement, repeatedly cutting prey and returning bounded life.',symbol:'☽',cooldown:13,radius:160,damage:230,effect:'realmrelic',duration:5},
 moonrend:{id:'moonrend',name:'Moonrend',short:'Moonrend',description:'Rend a distant threat with a lingering crescent of lunar claws and reclaim a little life.',symbol:'☽',cooldown:11,radius:190,damage:330,effect:'realmrelic',duration:3},
 wolfbound:{id:'wolfbound',name:'Moonstrider Vault',short:'Vault',description:'Vault over walls and gaps to a nearby safe floor. Press again to leap in your movement direction, or click/tap a landing. Strike on arrival and briefly dodge attacks.',symbol:'➤',cooldown:8,radius:110,damage:200,effect:'parkour'},
 moonhowl:{id:'moonhowl',name:'Howl of the Pale Moon',short:'Howl',description:'Drive lesser enemies away in fear. Guardians and captains withstand fear, but still take the howl’s impact.',symbol:'☽',cooldown:13,radius:330,damage:130,effect:'wolfhowl',duration:3},
 ravage:{id:'ravage',name:'Fang and Fury',short:'Ravage',description:'A powerful claw sweep tears through nearby prey and knocks them away.',symbol:'◇',cooldown:7,radius:230,damage:290,effect:'wolfravage'},
 moonfury:{id:'moonfury',name:'Bloodmoon Reign',short:'Bloodmoon',description:'For seven seconds, warp between visible threats and slash them. Brief dodges during each leap give your innate regeneration room to work.',symbol:'✦',cooldown:46,radius:650,damage:180,effect:'wolffury',duration:7},
 command:{id:'command',name:"Tyrant's Command",short:'Dominate',description:'Convert up to 12 nearby common enemies into 28-second servants. At the ally cap, new converts replace weakened servants. Elites and Titans resist control.',symbol:'♟',cooldown:12,radius:360,damage:1,effect:'dominate',duration:12},
 curse:{id:'curse',name:'Plague of Crowns',short:'Corrupt',description:'Curse nearby enemies for eight seconds. They take damage and explode on death, spreading corruption.',symbol:'◇',cooldown:9,radius:430,damage:55,effect:'curse',duration:8},
 legion:{id:'legion',name:'Graveborn Legion',short:'Raise',description:'Raise eight servants for 18 seconds. They hunt farther when you are safe and defend nearby when pressed. Your army is capped at 24–28 allies as Release grows.',symbol:'♜',cooldown:16,radius:180,damage:1,effect:'summon',duration:12},
 throne:{id:'throne',name:'Absolute Dominion',short:'Dominion',description:'Corrupt the battlefield, seize weak foes and ignite a massive cascading detonation.',symbol:'✦',cooldown:46,radius:750,damage:240,effect:'dominion'},
 oblivion:{id:'oblivion',name:'Oblivion Ray',short:'Ray',description:'Sweep a focused, lethal ray toward the closest enemy in range for 2.4 seconds. It widens and lasts longer with Release.',symbol:'ϟ',cooldown:12,radius:720,damage:220,effect:'beam',duration:2.4},
 meteor:{id:'meteor',name:'Starfall Verdict',short:'Starfall',description:'Press Starfall to suggest a target; press again to confirm, or click/tap your own placement. A meteor strikes after 1.2 seconds.',symbol:'◆',cooldown:10,radius:260,damage:650,effect:'meteor',duration:1.2},
 vortex:{id:'vortex',name:'Event Horizon',short:'Vortex',description:'Press Vortex to suggest a target; press again to confirm, or click/tap your own placement. Pull enemies into a damaging field for four seconds.',symbol:'◉',cooldown:16,radius:220,damage:70,effect:'vortex',duration:4},
 crimson:{id:'crimson',name:'Crimson Catastrophe',short:'Catastrophe',description:'Erase an enormous area with a signature magical detonation.',symbol:'✦',cooldown:48,radius:850,damage:2200,effect:'blast'},
 rendlunge:{id:'rendlunge',name:'Riftfang Lunge',short:'Lunge',description:'Lunge through prey in your movement direction. When stationary, use your last movement direction (right before your first move). Gain a second charge at Unbound II and a third at Final Release; rapid recasts chain the dash. The first 0.16 seconds of each Lunge dodge incoming damage.',symbol:'➤',cooldown:5,radius:60,damage:100,effect:'lunge',duration:.3},
 maw:{id:'maw',name:'Maw of Ruin',short:'Devour',description:'Devour nearby prey with Maw of Ruin. Healing is capped at 35% of maximum health per cast.',symbol:'♜',cooldown:9,radius:160,damage:520,effect:'devour'},
 execution:{id:'execution',name:'Royal Execution',short:'Execute',description:'Execute a nearby Titan first, then a wounded elite, then the nearest prey. Eightfold Titan damage; double damage below half health.',symbol:'◇',cooldown:11,radius:420,damage:700,effect:'execute'},
 frenzy:{id:'frenzy',name:'Feast of the Unbound',short:'Feast',description:'Feast of the Unbound grants eight seconds of faster claws. Kills heal up to 25–65% maximum health per cast; every 20 kills grants brief 40–60% damage reduction. Both improve with Release. From Unbound II, each Feast claw attack also launches a piercing ranged slash wave in your movement direction, retaining your last movement direction while stationary (right before your first move). Wave kills score normally and feed the same capped Feast healing, guard and Predatory Momentum as nearby kills.',symbol:'✦',cooldown:42,radius:140,damage:1,effect:'frenzy',duration:8},
 worldbreaker:{id:'worldbreaker',name:'World Breaker',short:'Breaker',description:'Shatter nearby ranks and hurl bodies through their allies.',symbol:'◉',cooldown:6,radius:210,damage:145,effect:'shockwave'},
 stampede:{id:'stampede',name:'Iron Stampede',short:'Stampede',description:'Charge in your movement direction, or the last direction you moved, trampling enemies for 0.7 seconds.',symbol:'➤',cooldown:8,radius:85,damage:95,effect:'charge',duration:.7},
 kingfall:{id:'kingfall',name:'Kingfall Throw',short:'Throw',description:'Launch nearby enemies and their remains at extreme speed.',symbol:'♜',cooldown:10,radius:155,damage:150,effect:'launch'},
 heavenfall:{id:'heavenfall',name:'Heavenfall Cataclysm',short:'Heavenfall',description:'A colossal ground impact that scatters entire armies.',symbol:'✦',cooldown:45,radius:580,damage:1800,effect:'blast'},
 rupture:{id:'rupture',name:'Rupture',short:'Rupture',description:'Radial damage and violent knockback.',symbol:'◉',cooldown:6,radius:190,damage:110,effect:'shockwave'},
 devour:{id:'devour',name:'Devour',short:'Devour',description:'Consume nearby prey to heal up to 40% maximum health and enrage. Each kill builds a magical Aegis ward for eight seconds, even at full health; capacity rises from 100 to 180 with Release.',symbol:'♜',cooldown:9,radius:155,damage:400,effect:'devour'},
 beam:{id:'beam',name:'Death Beam',short:'Beam',description:'Track the nearest enemy in range with a focused death beam for 2.2 seconds. It widens and lasts longer with Release; kills rebuild a small amount of Aegis ward when the beam ends.',symbol:'ϟ',cooldown:13,radius:680,damage:180,effect:'beam',duration:2.2},
 catastrophe:{id:'catastrophe',name:'Catastrophe',short:'Catastrophe',description:'Annihilate the surrounding horde. Kills rebuild a small amount of Aegis ward.',symbol:'✦',cooldown:48,radius:630,damage:1800,effect:'blast'},
 soulsweep:{id:'soulsweep',name:'Soul Harvest',short:'Harvest',description:'Sweep your scythe around you, push enemies away and steal life from struck prey.',symbol:'☽',cooldown:7,radius:230,damage:300,effect:'reapersweep'},
 graveshift:{id:'graveshift',name:'Graveshift',short:'Blink',description:'Choose Blink to suggest a dangerous visible enemy; press Blink again to confirm, or click/tap another enemy. Warp beside it and strike hard. Release and Kingslayer strengthen the strike; briefly evade damage on arrival.',symbol:'➤',cooldown:9,radius:580,damage:340,effect:'reaperblink'},
 reapingarc:{id:'reapingarc',name:'Reaping Arc',short:'Arc',description:'Choose Arc to suggest a dangerous visible target; press Arc again to confirm, or click/tap a target or direction. Three spinning crescents curve through the ranks. Scythe attacks share capped life steal.',symbol:'☽',cooldown:12,radius:720,damage:235,effect:'reapervolley'},
 moonstorm:{id:'moonstorm',name:'Eclipse Requiem',short:'Eclipse',description:'For eight seconds, sustain a damaging scythe aura and send curved, spinning crescents toward captains, Titans and other dangerous prey. Movement changes their bend.',symbol:'✦',cooldown:46,radius:700,damage:110,effect:'reaperstorm',duration:8},
 faultline:{id:'faultline',name:'Faultline Rupture',short:'Fissure',description:'Spend Momentum and 35% of your current barrier to crack a path in your movement direction. The fissure damages and slows enemies over time; high Momentum briefly snares lesser foes. More Momentum makes it stronger, wider and longer-lasting.',symbol:'ϟ',cooldown:11,radius:300,damage:65,effect:'fissure',duration:4}
};
export const channels:MonsterDef['channels']=[{id:'primary',label:'Body / armor'},{id:'secondary',label:'Mantle / markings'},{id:'accent',label:'Bone / trim'},{id:'power',label:'Eyes / supernatural power'}];
export function visual(id:string,scale=1):MonsterDef['visual']{return {scale,assetRoot:'assets/monsters/'+id,frameSize:256,facesLeft:['sovereign','titan','devourer'].includes(id),states:{idle:{row:0,frames:4,fps:6},move:{row:1,frames:6,fps:10},attack:{row:2,frames:6,fps:14},hurt:{row:3,frames:2,fps:10},ultimate:{row:4,frames:6,fps:12}}};}
export const MONSTERS:Record<string,MonsterDef>={
 lycanthrope:{id:'lycanthrope',unlockStage:2,archetype:'Lycanthrope',rank:'MOONSTRIDER',description:'A swift wolf huntress. Cross broken paths, scatter pursuers and regenerate while making space.',hp:930,speed:235,armor:1,basic:{name:'Savage Claws',description:'Swift claw swipes cut nearby prey.',damage:57,radius:105,interval:.34,ranged:false},abilities:['wolfbound','moonhowl','ravage','moonfury'],passive:{id:'moonblood',name:'Moonblood',description:'Regenerate health steadily. Vault, Howl and Bloodmoon create breathing room; regeneration grows with Release.'},palette:{primary:'#8862c7',secondary:'#eee5d4',accent:'#d9af61',power:'#e975bc',skin:'#f3dfd1'},channels:[{id:'primary',label:'Battle cloth / leather'},{id:'secondary',label:'Hair / wolf fur'},{id:'accent',label:'Metal / claws'},{id:'power',label:'Eyes / moon power'},{id:'skin',label:'Skin'}],visual:visual('lycanthrope',1.04)},
 overlord:{id:'overlord',archetype:'Overlord',rank:'DEMON SOVEREIGN',description:'Make the horde your weapon. Dominate lesser monsters, raise servants and let corruption consume the battlefield.',hp:950,speed:200,armor:1,basic:{name:'Edict of Ruin',description:'Dark bolts automatically seek the closest enemy in range.',damage:65,radius:600,interval:.5,ranged:true},abilities:['command','curse','legion','throne'],passive:{id:'ownership',name:'The Crown Owns All',description:'Controlled, summoned and corruption kills earn full Body Count, Dominance and Carnage, with separate source records.'},palette:{primary:'#202433',secondary:'#a83248',accent:'#d9af61',power:'#49b3aa',skin:'#eee5d4'},channels:[...channels.map(c=>c.id==='accent'?{...c,label:'Metal / ornament'}:c),{id:'skin',label:'Bone / skulls'}],visual:visual('overlord',1.05)},
 calamity:{id:'calamity',archetype:'Calamity',rank:'LIVING DISASTER',description:'A fragile walking apocalypse. Sweep distant ranks, gather them into a vortex, and call down stars.',hp:720,speed:195,armor:1.08,basic:{name:'Ruin Lance',description:'Automatically fires powerful magic bolts at the closest enemy in range.',damage:85,radius:650,interval:.42,ranged:true},abilities:['oblivion','meteor','vortex','crimson'],passive:{id:'massacre',name:'Disaster Resonance',description:'A 20+ kill activation grants +0.15 Carnage and reduces other cooldowns by 0.75s, at most once per second.'},palette:{primary:'#8862c7',secondary:'#49b3aa',accent:'#d9af61',power:'#e975bc',skin:'#eee5d4'},channels:[...channels,{id:'skin',label:'Mask / arms'}],visual:visual('calamity',.95)},
 devourer:{id:'devourer',archetype:'Devourer',rank:'APEX ABERRATION',description:'A swift, relentless predator. Hunt champions, feed through danger and build lethal momentum.',hp:850,speed:245,armor:1,basic:{name:'Ravenous Fangs',description:'Fast circular claws; attack twice as fast during Feast. From Unbound II, Feast also sends piercing claw waves through distant ranks.',damage:45,radius:90,interval:.28,ranged:false},abilities:['rendlunge','maw','execution','frenzy'],passive:{id:'hunger',name:'Predatory Momentum',description:'Recent kills grant up to 25% damage and 15% movement speed. Momentum fades when feeding stops.'},palette:{primary:'#eee5d4',secondary:'#705b4b',accent:'#d9af61',power:'#a83248'},channels,visual:visual('devourer',.92)},
 titan:{id:'titan',archetype:'Titan',rank:'ANCIENT BEAST',description:'An armored catastrophe. Charge into the crowd and turn bodies into siege weapons.',hp:1600,speed:165,armor:.9,basic:{name:'Continental Cleave',description:'Slow, heavy circular impacts. Strongest in crowded melee.',damage:100,radius:125,interval:.7,ranged:false},abilities:['worldbreaker','stampede','kingfall','heavenfall'],passive:{id:'surrounded',name:'Juggernaut Momentum',description:'Actual movement builds Momentum, strengthening kill-earned barrier and reinforcing it while moving. Standing still weakens this protection. Three nearby enemies grant 15% damage reduction.'},palette:{primary:'#a83248',secondary:'#202433',accent:'#d9af61',power:'#d88868'},channels,visual:visual('titan',1.25)},
 sovereign:{id:'sovereign',archetype:'Sovereign',rank:'ORIGINAL INCARNATION',description:'The original all-round destroyer. Claws, feeding and overwhelming magic.',hp:1000,speed:205,armor:1,basic:{name:'Sovereign Claws',description:'Automatic circular cleave.',damage:42,radius:95,interval:.45,ranged:false},abilities:['rupture','devour','beam','catastrophe'],passive:{id:'rage',name:'Feeding Rage',description:'Devour grants 40% increased damage and 25% damage reduction for six seconds. Kills with Devour, Death Beam and Catastrophe build an eight-second Aegis ward. Devour earns more ward per kill; magic provides a smaller second route to protection.'},palette:{primary:'#aab9ce',secondary:'#a83248',accent:'#d9af61',power:'#d88868',skin:'#e4b997',hair:'#202433'},channels:[...channels.map(c=>c.id==='secondary'?{...c,label:'Cloak / fabric'}:c.id==='accent'?{...c,label:'Horns / metal trim'}:c),{id:'skin',label:'Face / skin'},{id:'hair',label:'Hair'}],visual:visual('sovereign')},
 reaper:{id:'reaper',unlockStage:1,archetype:'Reaper',rank:'ECLIPSE HARVESTER',description:'A scythe-wielding hunter of souls. Pierce distant ranks, blink through danger and sweep the horde away.',hp:850,speed:215,armor:1,basic:{name:'Crescent Sever',description:'Spinning crescents curve through the ranks toward the most dangerous enemy in range.',damage:68,radius:660,interval:.55,ranged:true},abilities:['soulsweep','graveshift','reapingarc','moonstorm'],passive:{id:'soulharvest',name:'Soul Tithe',description:'Scythe hits steal life, with a shared recovery limit. Use sweeps and Blink to create space while your ranged waves cut through prey.'},palette:{primary:'#202433',secondary:'#8862c7',accent:'#d9af61',power:'#49b3aa',skin:'#f3dfd1'},channels:[{id:'primary',label:'Armor / fabric'},{id:'secondary',label:'Twin tails / hair'},{id:'accent',label:'Metal / ornament'},{id:'power',label:'Eyes / soul energy'},{id:'skin',label:'Skin'}],visual:visual('reaper',1.05)}
};
export const abilitiesForStage=(monsterId:string,phase=0,titanKit='throw')=>MONSTERS[monsterId].abilities.map(id=>ABILITIES[(phase>=1||phase===0&&titanKit==='fissure')&&monsterId==='titan'&&id==='kingfall'?'faultline':id]);
export function paletteFor(monster:MonsterDef,value:unknown):Palette{const output={...monster.palette};if(!value||typeof value!=='object')return output;for(const {id} of monster.channels){const color=(value as Record<string,unknown>)[id];if(typeof color==='string'&&/^#[0-9a-f]{6}$/i.test(color))output[id]=color.toLowerCase();}return output;}
export function validateContent(){for(const m of Object.values(MONSTERS))if(m.abilities.length!==4||!m.abilities.every(id=>ABILITIES[id])||m.hp<=0||m.speed<=0||m.basic.interval<=0)throw Error('Invalid monster '+m.id);for(const a of Object.values(ABILITIES))if(a.cooldown<=0||a.damage<0||a.radius<=0)throw Error('Invalid ability '+a.id);}
