import {COURT_LANES,COURT_BOUNDS,COURT_RADIUS,MAP_CHUNKS,type Point} from './court-layout.ts';
export {COURT_BOUNDS,COURT_RADIUS,COURT_REGIONS,COURT_SITE_GROUPS,COURT_SITES,COURT_SHRINES,COURT_SEARCH_ROUTE,COURT_LANES,MAP_CHUNKS,courtRegionAt} from './court-layout.ts';
// Walkable capsules define connected ground, not the bounds of the painted image.
const size=400,key=(x:number,y:number)=>x*65536+y,buckets=new Map<number,number[]>();
COURT_LANES.forEach((l,i)=>{for(let x=Math.floor((Math.min(l.a.x,l.b.x)-l.radius)/size);x<=Math.floor((Math.max(l.a.x,l.b.x)+l.radius)/size);x++)for(let y=Math.floor((Math.min(l.a.y,l.b.y)-l.radius)/size);y<=Math.floor((Math.max(l.a.y,l.b.y)+l.radius)/size);y++){const k=key(x,y),items=buckets.get(k);if(items)items.push(i);else buckets.set(k,[i]);}});
function closest(p:Point,a:Point,b:Point){const x=b.x-a.x,y=b.y-a.y,t=Math.max(0,Math.min(1,((p.x-a.x)*x+(p.y-a.y)*y)/(x*x+y*y||1)));return {x:a.x+x*t,y:a.y+y*t};}
export function courtClearance(x:number,y:number){let best=-Infinity;for(const i of buckets.get(key(Math.floor(x/size),Math.floor(y/size)))??[]){const l=COURT_LANES[i],p=closest({x,y},l.a,l.b),d=l.radius-Math.hypot(x-p.x,y-p.y);if(d>best)best=d;}return best;}
export function insideCourt(x:number,y:number,radius=0){return x>=COURT_BOUNDS.left+radius&&x<=COURT_BOUNDS.right-radius&&y>=COURT_BOUNDS.top+radius&&y<=COURT_BOUNDS.bottom-radius&&courtClearance(x,y)>=radius-.00001;}
export function slideCourt(body:Point,radius:number){if(insideCourt(body.x,body.y,radius))return;const nearby=new Set<number>();for(let x=-1;x<=1;x++)for(let y=-1;y<=1;y++)for(const i of buckets.get(key(Math.floor(body.x/size)+x,Math.floor(body.y/size)+y))??[])nearby.add(i);const candidates=nearby.size?[...nearby]:COURT_LANES.map((_,i)=>i);let best=Infinity,chosen:Point|null=null;for(const i of candidates){const l=COURT_LANES[i],p=closest(body,l.a,l.b),dx=body.x-p.x,dy=body.y-p.y,d=Math.hypot(dx,dy),allowed=l.radius-radius-.05;if(allowed<=0)continue;const scale=d>allowed?allowed/(d||1):1,q={x:p.x+dx*scale,y:p.y+dy*scale},cost=(q.x-body.x)**2+(q.y-body.y)**2;if(cost<best&&insideCourt(q.x,q.y,radius)){best=cost;chosen=q;}}if(chosen){body.x=chosen.x;body.y=chosen.y;}}
export function courtArtVisible(x:number,y:number,width:number,height:number,angle:number,cx:number,cy:number,halfW:number,halfH:number){const co=Math.abs(Math.cos(angle)),si=Math.abs(Math.sin(angle));return Math.abs(x-cx)<=halfW+(co*width+si*height)/2+32&&Math.abs(y-cy)<=halfH+(si*width+co*height)/2+32;}
// Cover the full segment with exact capsule intervals. Sparse samples can miss a narrow corner.
function clear(a:Point,b:Point){
 const dx=b.x-a.x,dy=b.y-a.y,length2=dx*dx+dy*dy;
 if(length2<.000001)return insideCourt(a.x,a.y,40);
 if(!insideCourt(a.x,a.y,40)||!insideCourt(b.x,b.y,40))return false;
 const ids=new Set<number>(),intervals:number[][]=[];
 for(let x=Math.floor(Math.min(a.x,b.x)/size);x<=Math.floor(Math.max(a.x,b.x)/size);x++)for(let y=Math.floor(Math.min(a.y,b.y)/size);y<=Math.floor(Math.max(a.y,b.y)/size);y++)for(const i of buckets.get(key(x,y))??[])ids.add(i);
 const circle=(x:number,y:number,r:number)=>{const px=a.x-x,py=a.y-y,dot=px*dx+py*dy,disc=dot*dot-length2*(px*px+py*py-r*r);if(disc<0)return;const root=Math.sqrt(disc),lo=Math.max(0,(-dot-root)/length2),hi=Math.min(1,(-dot+root)/length2);if(lo<=hi)intervals.push([lo,hi]);};
 const range=(v:number,d:number,low:number,high:number)=>{if(Math.abs(d)<1e-10)return v>=low&&v<=high?[0,1]:null;const p=(low-v)/d,q=(high-v)/d;return [Math.max(0,Math.min(p,q)),Math.min(1,Math.max(p,q))];};
 for(const i of ids){const l=COURT_LANES[i],r=l.radius-40;if(r<=0)continue;circle(l.a.x,l.a.y,r);const ux=l.b.x-l.a.x,uy=l.b.y-l.a.y,n=Math.hypot(ux,uy);if(n<.01)continue;circle(l.b.x,l.b.y,r);const px=a.x-l.a.x,py=a.y-l.a.y,across=range((px*-uy+py*ux)/n,(dx*-uy+dy*ux)/n,-r,r),along=range((px*ux+py*uy)/n,(dx*ux+dy*uy)/n,0,n);if(across&&along){const lo=Math.max(across[0],along[0]),hi=Math.min(across[1],along[1]);if(lo<=hi)intervals.push([lo,hi]);}}
 intervals.sort((a,b)=>a[0]-b[0]);let covered=0;for(const [lo,hi] of intervals){if(lo>covered+1e-8)return false;covered=Math.max(covered,hi);if(covered>=1-1e-8)return true;}return false;
}
const step=200,cols=Math.ceil((COURT_BOUNDS.right-COURT_BOUNDS.left)/step)+1,rows=Math.ceil((COURT_BOUNDS.bottom-COURT_BOUNDS.top)/step)+1;
const nodes:Point[]=[],indices=new Int16Array(cols*rows).fill(-1),nodeBuckets=new Map<number,number[]>();
for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const p={x:COURT_BOUNDS.left+x*step,y:COURT_BOUNDS.top+y*step};if(!insideCourt(p.x,p.y,65))continue;indices[y*cols+x]=nodes.length;nodes.push(p);const k=key(x,y),items=nodeBuckets.get(k);if(items)items.push(nodes.length-1);else nodeBuckets.set(k,[nodes.length-1]);}
export const COURT_NAV_NODE_COUNT=nodes.length;
const links=nodes.map(p=>{const x=Math.round((p.x-COURT_BOUNDS.left)/step),y=Math.round((p.y-COURT_BOUNDS.top)/step),out:number[]=[];for(let dx=-1;dx<=1;dx++)for(let dy=-1;dy<=1;dy++){const xx=x+dx,yy=y+dy;if(!(dx||dy)||xx<0||yy<0||xx>=cols||yy>=rows)continue;const j=indices[yy*cols+xx];if(j>=0&&clear(p,nodes[j]))out.push(j);}return out;});
function cell(p:Point){const x=Math.round((p.x-COURT_BOUNDS.left)/step),y=Math.round((p.y-COURT_BOUNDS.top)/step);let best=Infinity,index=-1;for(const range of [1,3]){for(let dx=-range;dx<=range;dx++)for(let dy=-range;dy<=range;dy++)for(const j of nodeBuckets.get(key(x+dx,y+dy))??[]){const q=nodes[j],cost=(p.x-q.x)**2+(p.y-q.y)**2;if(cost<best&&clear(p,q)){best=cost;index=j;}}if(index>=0)break;}return index;}
const flows=new Map<number,Int16Array>();let goalX=NaN,goalY=NaN,goalCell=-1;
function flow(goal:number){let f=flows.get(goal);if(f)return f;f=new Int16Array(nodes.length).fill(-1);f[goal]=goal;const queue=[goal];for(let n=0;n<queue.length;n++)for(const j of links[queue[n]])if(f[j]<0){f[j]=queue[n];queue.push(j);}if(flows.size>=12)flows.delete(flows.keys().next().value!);flows.set(goal,f);return f;}
export function courtWaypoint(x:number,y:number,tx:number,ty:number){const from={x,y},goal={x:tx,y:ty};if(!insideCourt(x,y,42)){slideCourt(from,42);const d=Math.hypot(from.x-x,from.y-y);if(d>2)return from;}if(!insideCourt(tx,ty,42))slideCourt(goal,42);if(!clear(from,goal)){const i=cell(from);if(goal.x!==goalX||goal.y!==goalY){goalX=goal.x;goalY=goal.y;goalCell=cell(goal);}if(i>=0&&goalCell>=0){const k=flow(goalCell)[i];if(k>=0){const p=clear(from,nodes[k])?nodes[k]:nodes[i];tx=p.x;ty=p.y;}}}else{tx=goal.x;ty=goal.y;}return {x:tx,y:ty};}
export function courtSteer(x:number,y:number,tx:number,ty:number){const p=courtWaypoint(x,y,tx,ty),dx=p.x-x,dy=p.y-y,d=Math.hypot(dx,dy)||1;return {x:dx/d,y:dy/d};}
