import { EVENT, FEATS, PHASES, POWERS } from './data.ts';
import { Game, type Input } from './simulation.ts';
import { Renderer } from './renderer.ts';
import { AudioEngine } from './audio.ts';
import { encodeRun, type RunRecord } from './run-code.ts';
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const renderer=new Renderer($<HTMLCanvasElement>('arena')),audio=new AudioEngine();
let game:Game|null=null,paused=false,last=0,accumulator=0,uiClock=0,frameAverage=16,run:RunRecord|null=null,code='',resultGeneration=0;
const input:Input={x:0,y:0,aimX:0,aimY:0,aiming:false},keys=new Set<string>();let joyX=0,joyY=0,joyId:number|null=null;
const safeRead=(key:string,fallback:string)=>{try{return localStorage.getItem(key)??fallback;}catch{return fallback;}};
const safeWrite=(key:string,value:string)=>{try{localStorage.setItem(key,value);}catch{}};
$<HTMLInputElement>('name').value=safeRead('mm-name','Dread Sovereign');
for(const id of ['mute','shake','lowFX']){const el=$<HTMLInputElement>(id);el.checked=safeRead('mm-'+id,id==='shake'&&!matchMedia('(prefers-reduced-motion: reduce)').matches?'1':'0')==='1';el.addEventListener('change',()=>{safeWrite('mm-'+id,el.checked?'1':'0');applyPreferences();});}
function applyPreferences(){audio.muted=$<HTMLInputElement>('mute').checked;renderer.shake=$<HTMLInputElement>('shake').checked;renderer.low=$<HTMLInputElement>('lowFX').checked;}applyPreferences();
const buttons=POWERS.map((p,i)=>{const b=document.createElement('button');b.className='ability ready';b.innerHTML=`<span class="key">${i+1} / ${p.key}</span><span class="symbol">${p.symbol}</span><span class="title">${p.name.toUpperCase()}</span><span class="cool" hidden></span>`;b.setAttribute('aria-label',`${p.name}, ${p.cooldown} second cooldown`);b.addEventListener('pointerdown',e=>{e.preventDefault();if(game&&!paused)game.cast(i);});$('abilities').append(b);return b;});
function clearInput(){keys.clear();joyX=joyY=0;joyId=null;input.x=input.y=0;input.aiming=false;$('joystick').firstElementChild!.setAttribute('style','transform:translate(0,0)');}
function start(){
 resultGeneration++;clearInput();run=null;code='';$('result').hidden=true;$('menu').hidden=true;$('paused').hidden=true;
 for(const id of ['hud','combatInfo','controls'])$(id).hidden=false;
 const name=$<HTMLInputElement>('name').value.trim().slice(0,24)||'Dread Sovereign';$<HTMLInputElement>('name').value=name;safeWrite('mm-name',name);
 audio.unlock();game=new Game(crypto.getRandomValues(new Uint32Array(1))[0]);game.sound=k=>audio.play(k);paused=false;accumulator=0;document.body.classList.add('playing');
 game.update(1/60,input);for(let i=0;i<65;i++)game.spawn(i%7===0?'hound':'thrall');game.rebuildGrid();updateUI();
 if(matchMedia('(pointer:coarse)').matches&&innerHeight>innerWidth)setPaused(true);
}
$('startForm').addEventListener('submit',e=>{e.preventDefault();start();});$('again').onclick=start;
$('howButton').onclick=()=>{$('help').hidden=false;};$('closeHelp').onclick=()=>{$('help').hidden=true;};
function setPaused(value:boolean){if(!game||game.ended)return;paused=value;$('paused').hidden=!paused;clearInput();accumulator=0;}
$('pause').onclick=()=>setPaused(true);$('resume').onclick=()=>{audio.unlock();setPaused(false);};$('endRun').onclick=()=>{if(game){game.ended=true;void finish('retired');}};
$('back').onclick=()=>{game=null;$('result').hidden=true;$('menu').hidden=false;for(const id of ['hud','combatInfo','controls'])$(id).hidden=true;document.body.classList.remove('playing');};
const bindings:Record<string,number>={'1':0,q:0,'2':1,e:1,'3':2,r:2,'4':3,' ':3};
window.addEventListener('keydown',e=>{if(!game||game.ended||e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement)return;if([' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))e.preventDefault();if(e.key==='Escape'||e.key.toLowerCase()==='p'){if(!e.repeat)setPaused(!paused);return;}keys.add(e.key.toLowerCase());if(!paused&&!e.repeat&&bindings[e.key.toLowerCase()]!==undefined)game.cast(bindings[e.key.toLowerCase()]);});
window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{clearInput();setPaused(true);});document.addEventListener('visibilitychange',()=>{if(document.hidden)setPaused(true);});
window.addEventListener('resize',()=>{renderer.resize();if(game&&matchMedia('(pointer:coarse)').matches&&innerHeight>innerWidth)setPaused(true);});
$('arena').addEventListener('pointermove',e=>{if(!game||e.pointerType==='touch')return;const p=renderer.screenToWorld(e.clientX,e.clientY,game);input.aimX=p.x;input.aimY=p.y;input.aiming=true;});
const joystick=$('joystick');joystick.addEventListener('pointerdown',e=>{if(joyId!==null)return;joyId=e.pointerId;joystick.setPointerCapture(e.pointerId);moveJoy(e);});joystick.addEventListener('pointermove',moveJoy);
function moveJoy(e:PointerEvent){if(e.pointerId!==joyId)return;e.preventDefault();const r=joystick.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,d=Math.hypot(dx,dy),max=r.width*.34;joyX=dx/Math.max(max,d);joyY=dy/Math.max(max,d);input.aiming=false;(joystick.firstElementChild as HTMLElement).style.transform=`translate(${joyX*max}px,${joyY*max}px)`;}
for(const event of ['pointerup','pointercancel','lostpointercapture'])joystick.addEventListener(event,e=>{if((e as PointerEvent).pointerId===joyId){joyId=null;joyX=joyY=0;(joystick.firstElementChild as HTMLElement).style.transform='';}});
const timeText=(s:number)=>`${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`;
function updateUI(){if(!game)return;const g=game;$('score').textContent=g.score.dominance.toLocaleString();$('kills').textContent=g.score.kills.toLocaleString();$('health').style.width=`${g.player.hp/g.player.maxHp*100}%`;$('healthText').textContent=`${Math.ceil(g.player.hp)} / ${g.player.maxHp}`;$('wave').textContent=`WAVE ${g.wave.toString().padStart(2,'0')}`;$('clock').textContent=timeText(g.time);$('phaseLabel').textContent=`${EVENT.phase+1} · ${PHASES[EVENT.phase].name}`;$('carnage').innerHTML=`CARNAGE <b>×${g.score.carnage.toFixed(1)}</b>`;$('notice').textContent=g.noticeTime>0?g.notice:'';const titan=g.enemies.find(e=>e.active&&e.kind==='titan');$('boss').textContent=titan?`♛ THE HOLLOW KING · ${Math.ceil(titan.hp/titan.maxHp*100)}%`:'';buttons.forEach((b,i)=>{const cool=b.querySelector<HTMLElement>('.cool')!;cool.hidden=g.cooldowns[i]<=0;cool.textContent=Math.ceil(g.cooldowns[i]).toString();b.classList.toggle('ready',g.cooldowns[i]<=0);b.setAttribute('aria-label',`${POWERS[i].name}: ${g.cooldowns[i]>0?Math.ceil(g.cooldowns[i])+' seconds':'ready'}`);});}
async function finish(reason:'overwhelmed'|'retired'){
 if(!game||run)return;const g=game,generation=++resultGeneration;paused=false;clearInput();$('paused').hidden=true;document.body.classList.remove('playing');for(const id of ['hud','controls','combatInfo'])$(id).hidden=true;
 run={version:1,rules:EVENT.rules,phase:EVENT.phase,name:$<HTMLInputElement>('name').value,seed:g.seed,duration:Math.round(g.time),score:g.score.dominance,kills:g.score.kills,wave:g.wave,elites:g.score.elites,titans:g.score.titans,multi:g.score.largestMulti,peak:Number(g.score.peak.toFixed(2)),feats:{...g.score.feats},ended:new Date().toISOString(),reason};
 $('resultName').textContent=`${run.name} · ${reason==='retired'?'RITUAL ENDED':'OVERWHELMED'}`;$('resultScore').textContent=run.score.toLocaleString();$('stats').replaceChildren();for(const [label,value] of [['BODY COUNT',run.kills.toLocaleString()],['WAVE / TIME',`${run.wave} / ${timeText(run.duration)}`],['PEAK CARNAGE',`×${run.peak.toFixed(1)}`],['ELITES SLAIN',run.elites],['TITANS SLAIN',run.titans],['LARGEST MULTIKILL',run.multi]]){const div=document.createElement('div'),b=document.createElement('b'),span=document.createElement('span');b.textContent=String(value);span.textContent=String(label);div.append(b,span);$('stats').append(div);}
 $('feats').textContent=Object.entries(run.feats).map(([id,n])=>`${FEATS.find(f=>f.id===id)?.name||id} ×${n}`).join(' · ')||'A new legend is taking shape.';$('resultStatus').textContent='Preparing run code…';$<HTMLTextAreaElement>('runCode').value='';$('result').hidden=false;
 try{const encoded=await encodeRun(run);if(generation!==resultGeneration)return;code=encoded;$<HTMLTextAreaElement>('runCode').value=code;$('resultStatus').textContent='Post your result card and run code to your community Discord.';}catch{$('resultStatus').textContent='Run code unavailable. Use HTTPS or localhost to enable secure browser features.';}
}
async function copy(text:string){try{await navigator.clipboard.writeText(text);$('resultStatus').textContent='Copied. Bring your legend to Discord.';}catch{$('resultStatus').textContent='Clipboard unavailable. Select and copy the run code below.';$<HTMLTextAreaElement>('runCode').select();}}
$('copyCode').onclick=()=>{if(code)void copy(code);};$('copy').onclick=()=>{if(run)void copy(`${run.name} — MONSTER MASH\nDominance: ${run.score.toLocaleString()} | Body count: ${run.kills.toLocaleString()}\nWeek ${run.phase+1} · Wave ${run.wave} · ${timeText(run.duration)} · Peak Carnage ×${run.peak}\n${code}`);};
$('saveCard').onclick=()=>{
 if(!run)return;const card=document.createElement('canvas');card.width=1200;card.height=760;const c=card.getContext('2d')!;c.fillStyle='#141116';c.fillRect(0,0,1200,760);c.strokeStyle='#a64b3b';c.lineWidth=2;c.strokeRect(28,28,1144,704);c.fillStyle='#d1ac72';c.font='18px Arial';c.fillText('ISEKAI HELL / OCTOBER 2026',70,82);c.fillStyle='#e95641';c.font='bold 68px Arial';c.fillText('MONSTER MASH',65,164);c.fillStyle='#e7dace';c.font='28px Georgia';c.fillText(run.name,70,222);c.fillStyle='#b39b89';c.font='18px Arial';c.fillText(`WEEK ${run.phase+1} · ${PHASES[run.phase].name} · ${run.reason.toUpperCase()}`,70,266);c.fillStyle='#e5c58f';c.font='bold 110px Arial';c.fillText(run.score.toLocaleString(),64,390);c.font='18px Arial';c.fillText('DOMINANCE',70,430);
 const stats=[['BODY COUNT',run.kills.toLocaleString()],['WAVE / TIME',`${run.wave} / ${timeText(run.duration)}`],['PEAK CARNAGE',`×${run.peak.toFixed(1)}`],['ELITES / TITANS',`${run.elites} / ${run.titans}`],['LARGEST MULTIKILL',String(run.multi)]];stats.forEach(([label,value],i)=>{const x=70+(i%3)*370,y=490+Math.floor(i/3)*95;c.fillStyle='#aa9285';c.font='14px Arial';c.fillText(label,x,y);c.fillStyle='#eee0ce';c.font='bold 30px Arial';c.fillText(value,x,y+38);});c.fillStyle='#a87961';c.font='14px Arial';c.fillText(`YOUR BODY FALLS. YOUR LEGEND REMAINS.  /  RULES ${run.rules}`,70,697);
 const notable=Object.entries(run.feats).sort((a,b)=>b[1]-a[1]).slice(0,2);c.fillStyle='#aa9285';c.font='14px Arial';c.fillText('NOTABLE FEATS',810,585);c.fillStyle='#e5c58f';c.font='14px Arial';notable.forEach(([id,n],i)=>c.fillText(`${FEATS.find(f=>f.id===id)?.name||id} ×${n}`,810,612+i*22));
 card.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='monster-mash-result.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},'image/png');
};
function frame(stamp:number){const delta=Math.min(.1,(stamp-last)/1000||0);last=stamp;frameAverage=frameAverage*.97+delta*1000*.03;renderer.autoLow=frameAverage>23;
 if(game&&!game.ended&&!paused){input.x=joyX+(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0);input.y=joyY+(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);accumulator+=delta;let steps=0;while(accumulator>=1/60&&steps<6&&!game.ended){game.update(1/60,input);accumulator-=1/60;steps++;}if(game.ended)void finish('overwhelmed');}
 renderer.draw(game,game?game.time:stamp/1000);uiClock+=delta;if(uiClock>.1){uiClock=0;updateUI();$('performance').textContent=game&&!game.ended?`${game.alive} IN THE HORDE${renderer.autoLow?' · ADAPTIVE FX':''}`:'';}requestAnimationFrame(frame);
}requestAnimationFrame(frame);
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{/* Offline mode is optional; gameplay stays available. */});

