import { EVENT, FEATS, PHASES } from './data.ts';
import { Game, type Input } from './simulation.ts';
import { Renderer } from './renderer.ts';
import { AudioEngine } from './audio.ts';
import { encodeRun, type RunRecord } from './run-code.ts';
import {createIdentity} from './identity.ts';
import {MONSTERS,ABILITIES} from './content-monsters.ts';
import {loadProfile,saveProfile,updateRecords,recordProgress} from './profile.ts';
import {mountSelection,showRecords} from './selection.ts';
import {TITLES} from './content-titles.ts';
import {ACHIEVEMENTS} from './content-records.ts';
import {resultDetails,resultText,resultCard,showNewTitles} from './results.ts';
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const renderer=new Renderer($<HTMLCanvasElement>('arena')),audio=new AudioEngine();
let game:Game|null=null,paused=false,last=0,accumulator=0,uiClock=0,frameAverage=16,run:RunRecord|null=null,code='',resultGeneration=0;
const input:Input={x:0,y:0,aimX:0,aimY:0,aiming:false},keys=new Set<string>();let joyX=0,joyY=0,joyId:number|null=null;
const safeRead=(key:string,fallback:string)=>{try{return localStorage.getItem(key)??fallback;}catch{return fallback;}};
const safeWrite=(key:string,value:string)=>{try{localStorage.setItem(key,value);}catch{}};
let storage:Storage|undefined;try{storage=localStorage;}catch{}
const profile=loadProfile(storage);let newRecords:string[]=[],newTitles:string[]=[],runId='';let recordSaveTime=0;
function persist(){if(!saveProfile(profile,storage))$('storageStatus').textContent='Storage unavailable. You can play; records last only for this session.';}
const refreshSelection=mountSelection(profile,()=>{persist();renderer.previewIdentity=profile.identity;});renderer.previewIdentity=profile.identity;
$('recordsButton').onclick=()=>showRecords(profile);$('resultRecords').onclick=()=>showRecords(profile);$('closeRecords').onclick=()=>{$('records').hidden=true;refreshSelection();};
function trackRecords(finished=false,flush=false){if(!game)return;const unlocked=updateRecords(profile,game.score.metrics(),game.identity);for(const id of unlocked){newRecords.push(id);const a=ACHIEVEMENTS.find(a=>a.id===id)!;game.announce('RECORD · '+a.name);audio.play('achievement');}if(flush||finished||unlocked.length||game.time-recordSaveTime>5){const s=game.score,sources=s.sources;const earned=recordProgress(profile,{id:runId,monsterId:game.monster.id,values:{kills:s.kills,dominance:s.dominance,seconds:game.time,elites:s.elites,titans:s.titans,...sources,owned:(sources.controlled||0)+(sources.summoned||0),magic:['beam','meteor','vortex','ultimate'].reduce((n,k)=>n+(sources[k]||0),0),eliteDevoured:s.eliteDevoured},best:{seconds:game.time,wave:game.wave,multi:s.largestMulti,carnage:s.maxStreak,dominance:s.dominance,calamityMulti:game.monster.id==='calamity'?s.largestMulti:0}},finished);for(const id of earned){newTitles.push(id);game.announce('TITLE EARNED · '+TITLES.find(t=>t.id===id)!.name);audio.play('title');}recordSaveTime=game.time;persist();}}
for(const id of ['mute','shake','lowFX']){const el=$<HTMLInputElement>(id);el.checked=safeRead('mm-'+id,id==='mute'?(audio.muted?'1':'0'):id==='shake'&&!matchMedia('(prefers-reduced-motion: reduce)').matches?'1':'0')==='1';el.addEventListener('change',()=>{safeWrite('mm-'+id,el.checked?'1':'0');applyPreferences();});}
function applyPreferences(){audio.muted=$<HTMLInputElement>('mute').checked;renderer.shake=$<HTMLInputElement>('shake').checked;renderer.low=$<HTMLInputElement>('lowFX').checked;}applyPreferences();
for(const bus of ['music','sfx','ui'] as const){const slider=$<HTMLInputElement>('volume-'+bus);slider.value=String(Math.round(audio.preferences[bus]*100));$('value-'+bus).textContent=slider.value+'%';slider.oninput=()=>{audio.unlock();audio.setVolume(bus,Number(slider.value)/100);$('value-'+bus).textContent=slider.value+'%';};}
$('audioButton').onclick=()=>{if(game&&!game.ended)setPaused(true);$('audioSettings').hidden=false;};$('closeAudio').onclick=()=>{$('audioSettings').hidden=true;};
document.addEventListener('click',e=>{if((e.target as Element).closest('button,select')){audio.unlock();audio.play((e.target as Element).closest('.primary')?'confirm':'menu');}});
let buttons:HTMLButtonElement[]=[];
function buildButtons(){ $('abilities').replaceChildren();buttons=(game?.powers||MONSTERS[profile.identity.monsterId].abilities.map(id=>ABILITIES[id])).map((p,i)=>{const b=document.createElement('button');b.className='ability ready';b.innerHTML=`<span class="key">${i+1} / ${['Q','E','R','␣'][i]}</span><span class="symbol">${p.symbol}</span><span class="title">${p.short.toUpperCase()}</span><span class="cool" hidden></span>`;b.setAttribute('aria-label',`${p.name}, ${p.cooldown} second cooldown`);b.addEventListener('pointerdown',e=>{e.preventDefault();if(game&&!paused)game.cast(i);});$('abilities').append(b);return b;});}buildButtons();
function clearInput(){keys.clear();joyX=joyY=0;joyId=null;input.x=input.y=0;input.aiming=false;$('joystick').firstElementChild!.setAttribute('style','transform:translate(0,0)');}
function start(){
 resultGeneration++;clearInput();run=null;code='';$('result').hidden=true;$('menu').hidden=true;$('paused').hidden=true;
 for(const id of ['hud','combatInfo','controls'])$(id).hidden=false;
 profile.identity=createIdentity({...profile.identity,name:$<HTMLInputElement>('name').value});const name=profile.identity.name;$<HTMLInputElement>('name').value=name;safeWrite('mm-name',name);persist();newRecords=[];newTitles=[];runId=crypto.randomUUID();recordSaveTime=-5;
 audio.setPaused(false);audio.unlock();void audio.setMusic('combat');game=new Game(crypto.getRandomValues(new Uint32Array(1))[0],profile.identity);$('hudName').textContent=game.identity.name;$('hudClass').textContent=[game.identity.title,game.monster.archetype].filter(Boolean).join(' · ');$('pauseName').textContent=game.identity.name;$('pauseIdentity').textContent=$('hudClass').textContent;buildButtons();game.sound=k=>audio.play(k);paused=false;accumulator=0;document.body.classList.add('playing');
 game.update(1/60,input);game.seedOpening();updateUI();
 if(matchMedia('(pointer:coarse)').matches&&innerHeight>innerWidth)setPaused(true);
}
$('startForm').addEventListener('submit',e=>{e.preventDefault();start();});$('again').onclick=start;
$('howButton').onclick=()=>{$('help').hidden=false;};$('closeHelp').onclick=()=>{$('help').hidden=true;};
function setPaused(value:boolean){if(!game||game.ended)return;paused=value;audio.setPaused(value);$('paused').hidden=!paused;clearInput();accumulator=0;}
$('pause').onclick=()=>setPaused(true);$('resume').onclick=()=>{audio.unlock();setPaused(false);};$('endRun').onclick=()=>{if(game){game.ended=true;void finish('retired');}};
$('back').onclick=()=>{audio.setPaused(false);void audio.setMusic('menu');game=null;$('result').hidden=true;$('menu').hidden=false;for(const id of ['hud','combatInfo','controls'])$(id).hidden=true;document.body.classList.remove('playing');$('menu').scrollTop=0;refreshSelection();renderer.previewIdentity=profile.identity;};
const bindings:Record<string,number>={'1':0,q:0,'2':1,e:1,'3':2,r:2,'4':3,' ':3};
window.addEventListener('keydown',e=>{if(!game||game.ended||e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement||e.target instanceof HTMLSelectElement)return;if([' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))e.preventDefault();if(e.key==='Escape'||e.key.toLowerCase()==='p'){if(!e.repeat)setPaused(!paused);return;}keys.add(e.key.toLowerCase());if(!paused&&!e.repeat&&bindings[e.key.toLowerCase()]!==undefined)game.cast(bindings[e.key.toLowerCase()]);});
window.addEventListener('pagehide',()=>{if(game&&!game.ended){trackRecords(false,true);persist();}});
window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{clearInput();setPaused(true);});document.addEventListener('visibilitychange',()=>{if(document.hidden){setPaused(true);audio.setPaused(true);}else if(!game||game.ended)audio.setPaused(false);});
window.addEventListener('resize',()=>{renderer.resize();if(game&&matchMedia('(pointer:coarse)').matches&&innerHeight>innerWidth)setPaused(true);});
$('arena').addEventListener('pointermove',e=>{if(!game||e.pointerType==='touch')return;const p=renderer.screenToWorld(e.clientX,e.clientY,game);input.aimX=p.x;input.aimY=p.y;input.aiming=true;});
const joystick=$('joystick');joystick.addEventListener('pointerdown',e=>{if(joyId!==null)return;joyId=e.pointerId;joystick.setPointerCapture(e.pointerId);moveJoy(e);});joystick.addEventListener('pointermove',moveJoy);
function moveJoy(e:PointerEvent){if(e.pointerId!==joyId)return;e.preventDefault();const r=joystick.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,d=Math.hypot(dx,dy),max=r.width*.34;joyX=dx/Math.max(max,d);joyY=dy/Math.max(max,d);input.aiming=false;(joystick.firstElementChild as HTMLElement).style.transform=`translate(${joyX*max}px,${joyY*max}px)`;}
for(const event of ['pointerup','pointercancel','lostpointercapture'])joystick.addEventListener(event,e=>{if((e as PointerEvent).pointerId===joyId){joyId=null;joyX=joyY=0;(joystick.firstElementChild as HTMLElement).style.transform='';}});
const timeText=(s:number)=>`${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`;
function updateUI(){if(!game)return;const g=game;if(!g.ended)trackRecords();$('score').textContent=g.score.dominance.toLocaleString();$('kills').textContent=g.score.kills.toLocaleString();$('health').style.width=`${g.player.hp/g.player.maxHp*100}%`;$('healthText').textContent=`${Math.ceil(g.player.hp)} / ${g.player.maxHp}${g.shield>0?' · WARD '+Math.ceil(g.shield):''}`;$('wave').textContent=`WAVE ${g.wave.toString().padStart(2,'0')}`;$('clock').textContent=timeText(g.time);$('phaseLabel').textContent=`${EVENT.phase+1} · ${PHASES[EVENT.phase].name}`;$('carnage').innerHTML=`CARNAGE <b>×${g.score.carnage.toFixed(1)}</b>`;$('notice').textContent=g.noticeTime>0?g.notice:'';$('ultimateCutin').hidden=g.ultimateTime<=0||paused;$('ultimateCutin').textContent=g.identity.name+' · '+g.powers[3].name;$('ultimateCutin').style.setProperty('--power',g.identity.colors.power);const titan=g.enemies.find(e=>e.active&&e.kind==='titan');if(!g.ended&&!paused)void audio.setMusic(titan?'titan':g.score.carnage>=4||g.time>=300?'escalation':'combat');$('boss').textContent=titan?`♛ THE HOLLOW KING · ${Math.ceil(titan.hp/titan.maxHp*100)}%`:'';buttons.forEach((b,i)=>{const cool=b.querySelector<HTMLElement>('.cool')!;cool.hidden=g.cooldowns[i]<=0;cool.textContent=Math.ceil(g.cooldowns[i]).toString();b.classList.toggle('ready',g.cooldowns[i]<=0);b.setAttribute('aria-label',`${g.powers[i].name}: ${g.cooldowns[i]>0?Math.ceil(g.cooldowns[i])+' seconds':'ready'}`);});}
async function finish(reason:'overwhelmed'|'retired'){
 if(!game||run)return;const g=game,generation=++resultGeneration;paused=false;audio.setPaused(false);void audio.setMusic('menu');clearInput();$('paused').hidden=true;document.body.classList.remove('playing');for(const id of ['hud','controls','combatInfo'])$(id).hidden=true;
 trackRecords(true);persist();run={version:2,rules:EVENT.rules,phase:EVENT.phase,name:g.identity.name,title:g.identity.title,monsterId:g.identity.monsterId,colors:{...g.identity.colors},newRecords:[...newRecords],newTitles:[...newTitles],sources:{...g.score.sources},seed:g.seed,duration:Math.round(g.time),score:g.score.dominance,kills:g.score.kills,wave:g.wave,elites:g.score.elites,titans:g.score.titans,multi:g.score.largestMulti,peak:Number(g.score.peak.toFixed(2)),feats:{...g.score.feats},ended:new Date().toISOString(),reason};
 $('resultName').textContent=`${run.name} · ${reason==='retired'?'RITUAL ENDED':'OVERWHELMED'}`;$('resultScore').textContent=run.score.toLocaleString();$('stats').replaceChildren();for(const [label,value] of [['BODY COUNT',run.kills.toLocaleString()],['WAVE / TIME',`${run.wave} / ${timeText(run.duration)}`],['PEAK CARNAGE',`×${run.peak.toFixed(1)}`],['ELITES SLAIN',run.elites],['TITANS SLAIN',run.titans],['LARGEST MULTIKILL',run.multi]]){const div=document.createElement('div'),b=document.createElement('b'),span=document.createElement('span');b.textContent=String(value);span.textContent=String(label);div.append(b,span);$('stats').append(div);}
 $('feats').textContent=Object.entries(run.feats).map(([id,n])=>`${FEATS.find(f=>f.id===id)?.name||id} ×${n}`).join(' · ')||'A new legend is taking shape.';$('resultStatus').textContent='Preparing run code…';$<HTMLTextAreaElement>('runCode').value='';resultDetails(run);showNewTitles(run);$('result').hidden=false;$('result').scrollTop=0;
 try{const encoded=await encodeRun(run);if(generation!==resultGeneration)return;code=encoded;$<HTMLTextAreaElement>('runCode').value=code;$('resultStatus').textContent='Post your result card and run code to your community Discord.';}catch{$('resultStatus').textContent='Run code unavailable. Use HTTPS or localhost to enable secure browser features.';}
}
async function copy(text:string){try{await navigator.clipboard.writeText(text);$('resultStatus').textContent='Copied. Bring your legend to Discord.';}catch{$('resultStatus').textContent='Clipboard unavailable. Select and copy the run code below.';$<HTMLTextAreaElement>('runCode').select();}}
$('copyCode').onclick=()=>{if(code)void copy(code);};$('copy').onclick=()=>{if(run)void copy(resultText(run,code));};
$('saveCard').onclick=()=>{if(!run)return;resultCard(run,game?renderer.assets.get(game.identity)?.portrait:undefined).toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='monster-mash-'+run!.name.replace(/[^a-z0-9]/gi,'-')+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},'image/png');};
function frame(stamp:number){const delta=Math.min(.1,(stamp-last)/1000||0);last=stamp;frameAverage=frameAverage*.97+delta*1000*.03;renderer.autoLow=frameAverage>23;
 if(game&&!game.ended&&!paused){input.x=joyX+(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0);input.y=joyY+(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);accumulator+=delta;let steps=0;while(accumulator>=1/60&&steps<6&&!game.ended){game.update(1/60,input);accumulator-=1/60;steps++;}if(game.ended)void finish('overwhelmed');}
 renderer.draw(game,game?game.time:stamp/1000);for(const [id,visible,identity] of [['resultPortrait',!$('result').hidden,game?.identity],['recordPortrait',!$('records').hidden,profile.identity]] as const){const canvas=$<HTMLCanvasElement>(id);const portrait=visible&&identity?renderer.assets.get(identity)?.portrait:null;canvas.hidden=!portrait;if(portrait){const c=canvas.getContext('2d')!;c.clearRect(0,0,256,256);c.drawImage(portrait,0,0,256,256);}}if(!$('menu').hidden)renderer.drawPreview($<HTMLCanvasElement>('preview'),stamp/1000);uiClock+=delta;if(uiClock>.1){uiClock=0;updateUI();$('performance').textContent=game&&!game.ended?`${game.alive} IN THE HORDE${renderer.autoLow?' · ADAPTIVE FX':''}`:'';}requestAnimationFrame(frame);
}requestAnimationFrame(frame);
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{/* Offline mode is optional; gameplay stays available. */});

