import {loadMapDraft,saveMapDraft} from './map-editor-storage.ts';
import {REALM_MAP_DATA} from './realm-map-data.ts';
import {validateMapDocument,documentWalkable,polygonContains,ellipseContains,type MapDocument} from './realm-map-document.ts';
import {AssetLibrary} from './assets.ts';
import {createIdentity} from './identity.ts';
import {MONSTERS} from './content-monsters.ts';
const $=(id:string)=>document.getElementById(id)!;
const select=(id:string)=>$(id) as HTMLSelectElement;
const canvas=$('map') as HTMLCanvasElement,c=canvas.getContext('2d')!,view=$('viewport');
const floorMask=document.createElement('canvas');let floorDirty=true,maskBounds=[0,0,0,0];
const KEY='monster-mash-map-editor-v1',copy=<T>(v:T):T=>JSON.parse(JSON.stringify(v));
let doc:MapDocument=validateMapDocument(REALM_MAP_DATA),draftMessage='';
try{const saved=localStorage.getItem(KEY);if(saved){doc=validateMapDocument(JSON.parse(saved));draftMessage='Restored your saved draft.';}}catch{draftMessage='Could not restore draft; current game map loaded.';}
try{const saved=await loadMapDraft();if(saved){doc=validateMapDocument(saved);draftMessage='Restored your saved draft.';}}catch{}
type Snapshot={json:string;background:MapDocument['background']};
const snapshot=():Snapshot=>({json:JSON.stringify({...doc,background:undefined}),background:doc.background});
let history:Snapshot[]=[],future:Snapshot[]=[],zoom=1,ox=0,oy=0,w=1,h=1,layer='floor',tool='edit',selected='',vertex=-1,space=false,dirty=true,drag:any=null,stroke:number[][]=[],cursor=[0,0],actor=[644,744],moving=false;
let identity=createIdentity({monsterId:'devourer'}),artReady=false;const assets=new AssetLibrary();
const overview=new Image();overview.onload=()=>{dirty=true;};overview.onerror=()=>message('Map art failed to load. Reload this page.');overview.src=doc.background?.dataUrl||'assets/stage3/map-editor-overview.webp';
const scale=()=>doc.unitsPerPixel||7.4;
function backgroundChanged(){overview.src=doc.background?.dataUrl||'assets/stage3/map-editor-overview.webp';select('scale').value=String(scale());document.querySelector('header small')!.textContent=doc.background?'Custom map': 'Mana Abyss';select('jump').replaceChildren(new Option('Choose a shrine…',''),...doc.rooms.map((r,i)=>new Option(r[1],String(i))));}

const tiles=new Map<string,HTMLImageElement>(),pending=new Set<string>();let loading=0;
const masterX=(x:number)=>x/7.4+632,masterY=(y:number)=>(y+38)/7.4+524;
function message(text:string){$('status').textContent=text;}
let saveRevision=0;
function saved(){floorDirty=true;dirty=true;const revision=++saveRevision;$('saved').textContent='Saving draft…';if(!doc.background){try{localStorage.setItem(KEY,JSON.stringify(doc));}catch{}}void saveMapDraft(doc).then(()=>{if(revision===saveRevision)$('saved').textContent='Draft saved on this device';}).catch(()=>{if(revision===saveRevision)$('saved').textContent='Draft could not save — export your map';});}

function checkpoint(){history.push(snapshot());if(history.length>60)history.shift();future=[];}
function undo(redo=false){const from=redo?future:history,to=redo?history:future;if(!from.length)return;to.push(snapshot());const old=from.pop()!;doc=validateMapDocument({...JSON.parse(old.json),background:old.background});backgroundChanged();refresh();saved();}
function fit(){const bw=doc.background?.width||1400,bh=doc.background?.height||1400;zoom=Math.min(w/bw,h/bh)*.95;ox=w/2-(doc.background?bw/2:632)*zoom;oy=h/2-(doc.background?bh/2:524)*zoom;dirty=true;}
function resize(){const r=view.getBoundingClientRect(),first=w===1;w=r.width;h=r.height;const d=Math.min(devicePixelRatio,2);canvas.width=Math.round(w*d);canvas.height=Math.round(h*d);if(first)fit();dirty=true;}
new ResizeObserver(resize).observe(view);
type Shape={id:string;name:string;points?:number[][];ellipse?:number[];point?:number[];depth?:number;structure?:any[];open?:boolean};
function shapes():Shape[]{if(layer==='floor')return [...doc.rooms.map(r=>({id:r[0],name:r[1],points:r[7]})),...doc.decks.map(r=>({id:r[0],name:r[0],points:r[3]})),{id:'arena',name:'Titan arena floor',ellipse:doc.arena},...doc.patches.map((p,i)=>({id:'paint-'+i,name:(p.add?'Painted floor ':'Painted block ')+(i+1),points:p.points}))];
 if(layer==='base'||layer==='foreground')return doc.structures.map(s=>({id:s[0],name:s[0],structure:s,...(layer==='base'?{ellipse:s[1]}:{points:s[2],depth:s[3]??s[1][1]+s[1][3]})}));
 if(layer==='route')return doc.decks.map(r=>({id:r[0],name:r[0],points:r[2],open:true}));
 return [...doc.rooms.flatMap(r=>[4,5,6].map((i)=>({id:r[0]+'-'+i,name:r[1]+' · '+({4:'interaction',5:'relic',6:'portal'} as any)[i],point:r[i]}))),...(doc.markers||[]).map(m=>({id:m.id,name:m.name,point:m.point}))];}
function current(){return shapes().find(s=>s.id===selected);}
function refresh(){floorDirty=true;const all=shapes();if(!all.some(s=>s.id===selected))selected=all[0]?.id||'';select('shapes').replaceChildren(...all.map(s=>new Option(s.name,s.id)));select('shapes').value=selected;properties();dirty=true;}
function properties(){const box=$('properties');box.replaceChildren();const s=current();if(!s)return;const number=(label:string,value:number,set:(v:number)=>void)=>{const l=document.createElement('label'),i=document.createElement('input');l.textContent=label;i.type='number';i.step='.25';i.value=value.toFixed(2);i.onchange=()=>{const v=Number(i.value);if(!Number.isFinite(v)||Math.abs(v)>20000){properties();return;}checkpoint();set(v);saved();properties();};l.append(i);box.append(l);};
 const marker=doc.markers?.find(m=>m.id===s.id),room=doc.rooms.find(r=>r[0]===s.id);if(marker||room){const l=document.createElement('label'),input=document.createElement('input');l.textContent='Name';input.value=marker?marker.name:room![1];input.style.width='145px';input.onchange=()=>{checkpoint();if(marker)marker.name=input.value.slice(0,100);else room![1]=input.value.slice(0,80);refresh();saved();};l.append(input);box.append(l);}
 if(s.ellipse)s.ellipse.forEach((v,i)=>number(['Center X','Center Y','Width radius','Depth radius'][i],v,n=>s.ellipse![i]=i>1?Math.max(0,Math.min(20000,n)):n));
 if(s.point)s.point.forEach((v,i)=>number(i?'Y':'X',v,n=>s.point![i]=n));
 if(s.points&&vertex>=0&&s.points[vertex])s.points[vertex].forEach((v,i)=>number('Point '+(vertex+1)+(i?' Y':' X'),v,n=>s.points![vertex][i]=n));
 if(s.depth!==undefined)number('Hide behind feet Y',s.depth,n=>s.structure![3]=n);
 $('add-point').hidden=!s.points;$('delete-point').hidden=!s.points;}
function path(points:number[][],close=true){c.beginPath();points.forEach((p,i)=>i?c.lineTo(p[0],p[1]):c.moveTo(p[0],p[1]));if(close)c.closePath();}
function shapePath(s:Shape){if(s.points)path(s.points,!s.open);else if(s.ellipse){c.beginPath();c.ellipse(s.ellipse[0],s.ellipse[1],Math.max(.01,s.ellipse[2]),Math.max(.01,s.ellipse[3]),0,0,Math.PI*2);}else if(s.point){c.beginPath();c.arc(s.point[0],s.point[1],5/zoom,0,Math.PI*2);}}
function handles(s:Shape){if(s.points)return s.points.map((p,i)=>({p,index:i,kind:'point'})).concat(s.depth===undefined?[]:[{p:[(Math.min(...s.points.map(p=>p[0]))+Math.max(...s.points.map(p=>p[0])))/2,s.depth],index:-1,kind:'depth'}]);if(s.ellipse){const [x,y,rx,ry]=s.ellipse;return[{p:[x,y],index:0,kind:'center'},{p:[x+rx,y],index:2,kind:'rx'},{p:[x,y+ry],index:3,kind:'ry'}];}return s.point?[{p:s.point,index:0,kind:'marker'}]:[];}
function drawTile(x:number,y:number){const key=x+'-'+y;let image=tiles.get(key);if(image){tiles.delete(key);tiles.set(key,image);c.drawImage(image,masterX(x*512-5121),masterY(y*512-5121),514/7.4,514/7.4);return;}if(pending.has(key)||loading>=4)return;pending.add(key);loading++;image=new Image();image.onload=()=>{loading--;pending.delete(key);tiles.set(key,image!);while(tiles.size>64)tiles.delete(tiles.keys().next().value!);dirty=true;};image.onerror=()=>{loading--;dirty=true;};image.src='assets/stage3/map-v43/'+key+'.webp';}
function drawActor(time:number){if(!artReady)return;const hidden=doc.structures.filter(s=>actor[1]<(s[3]??s[1][1]+s[1][3])-3/scale());const body=()=>{c.save();c.translate(actor[0],actor[1]);c.scale(1/scale(),1/scale());assets.drawGameplay(c,identity,0,-24,time,moving?'move':'idle',MONSTERS[identity.monsterId].visual.scale,1,false);c.restore();};
 c.save();for(const s of hidden){c.beginPath();c.rect(-2000,-2000,4000,4000);s[2].forEach((p:number[],i:number)=>i?c.lineTo(p[0],p[1]):c.moveTo(p[0],p[1]));c.closePath();c.clip('evenodd');}body();c.restore();
 if(hidden.length){c.save();c.beginPath();for(const s of hidden){s[2].forEach((p:number[],i:number)=>i?c.lineTo(p[0],p[1]):c.moveTo(p[0],p[1]));c.closePath();}c.clip();c.globalAlpha=.65;body();c.restore();}
 c.strokeStyle=documentWalkable(doc,...actor as [number,number])?'#8dffac':'#ff6868';c.lineWidth=1.5/zoom;c.beginPath();c.arc(actor[0],actor[1],30/scale(),0,Math.PI*2);c.stroke();}
function drawFloor(){
 if(floorDirty){floorDirty=false;const left=doc.background?0:masterX(-5120),top=doc.background?0:masterY(-5120),width=doc.background?.width||10240/7.4,height=doc.background?.height||10240/7.4,k=Math.min(2,2048/Math.max(width,height));maskBounds=[left,top,width,height];floorMask.width=Math.ceil(width*k);floorMask.height=Math.ceil(height*k);const m=floorMask.getContext('2d')!;m.scale(k,k);m.translate(-left,-top);m.fillStyle='#6fe0a2';const poly=(p:number[][])=>{m.beginPath();p.forEach((q,i)=>i?m.lineTo(q[0],q[1]):m.moveTo(q[0],q[1]));m.closePath();m.fill();};const ellipse=(e:number[])=>{m.beginPath();m.ellipse(e[0],e[1],e[2],e[3],0,0,Math.PI*2);m.fill();};ellipse(doc.arena);for(const r of doc.rooms)poly(r[7]);for(const r of doc.decks)poly(r[3]);for(const p of doc.patches){m.globalCompositeOperation=p.add?'source-over':'destination-out';poly(p.points);}m.globalCompositeOperation='destination-out';for(const s of doc.structures)ellipse(s[1]);
 }c.save();c.globalAlpha=Number(select('opacity').value)/100;c.drawImage(floorMask,...maskBounds as [number,number,number,number]);c.restore();
}
function render(time:number){const d=canvas.width/w;c.setTransform(d,0,0,d,0,0);c.fillStyle='#161824';c.fillRect(0,0,w,h);c.translate(ox,oy);c.scale(zoom,zoom);
 if(overview.complete&&overview.naturalWidth){if(doc.background)c.drawImage(overview,0,0,doc.background.width,doc.background.height);else c.drawImage(overview,masterX(-5120),masterY(-5120),10240/7.4,10240/7.4);}
 if(!doc.background&&zoom>1.5){const x0=Math.max(0,Math.floor((((-ox)/zoom-632)*7.4+5120)/512)),x1=Math.min(19,Math.floor((((w-ox)/zoom-632)*7.4+5120)/512)),y0=Math.max(0,Math.floor((((-oy)/zoom-524)*7.4-38+5120)/512)),y1=Math.min(19,Math.floor((((h-oy)/zoom-524)*7.4-38+5120)/512));for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++)drawTile(x,y);}
 if(($('overlays') as HTMLInputElement).checked){const alpha=Number(($('opacity') as HTMLInputElement).value)/100;
  if(layer==='floor')drawFloor();
  for(const s of shapes()){if(layer==='floor'&&s.id.startsWith('paint-')&&s.id!==selected)continue;const active=s.id===selected,color=layer==='base'?'#ff6969':layer==='foreground'?'#cb8cff':layer==='marker'?'#ffdc78':'#6fe0a2';shapePath(s);c.fillStyle=color;c.globalAlpha=active?alpha+.12:alpha;if(!s.open&&layer!=='floor')c.fill();c.globalAlpha=1;c.strokeStyle=active?'#fff':color;c.lineWidth=(active?2:1)/zoom;c.stroke();}
  if(layer==='floor'){c.fillStyle='#ff696975';for(const s of doc.structures){const e=s[1];c.beginPath();c.ellipse(e[0],e[1],e[2],e[3],0,0,Math.PI*2);c.fill();}}
  const s=current();if(s&&tool==='edit'){if(s.depth!==undefined&&s.points){c.strokeStyle='#ffd773';c.lineWidth=2/zoom;c.setLineDash([6/zoom,4/zoom]);c.beginPath();c.moveTo(Math.min(...s.points.map(p=>p[0]))-10,s.depth);c.lineTo(Math.max(...s.points.map(p=>p[0]))+10,s.depth);c.stroke();c.setLineDash([]);}for(const handle of handles(s)){c.fillStyle=handle.kind==='depth'?'#ffd773':handle.index===vertex?'#ffe09f':'#fff';c.strokeStyle='#171120';c.lineWidth=1/zoom;c.beginPath();c.arc(handle.p[0],handle.p[1],5/zoom,0,Math.PI*2);c.fill();c.stroke();}}
 }
 if(tool==='add'||tool==='remove'){c.strokeStyle=tool==='add'?'#aaffbb':'#ff8888';c.lineWidth=2/zoom;c.beginPath();c.arc(cursor[0],cursor[1],Number(select('brush').value)/2,0,Math.PI*2);c.stroke();if(stroke.length){path(stroke,false);c.lineWidth=Number(select('brush').value);c.lineCap=c.lineJoin='round';c.globalAlpha=.35;c.stroke();c.globalAlpha=1;}}
 if(tool==='walk')drawActor(time);}
function screen(e:PointerEvent|WheelEvent){const r=canvas.getBoundingClientRect();return[e.clientX-r.left,e.clientY-r.top];}
function at(e:PointerEvent|WheelEvent){const [x,y]=screen(e);return[(x-ox)/zoom,(y-oy)/zoom];}
function zoomAt(factor:number,x=w/2,y=h/2){const old=zoom;zoom=Math.min(18,Math.max(.02,zoom*factor));ox=x-(x-ox)*zoom/old;oy=y-(y-oy)*zoom/old;dirty=true;}
function closestEdge(points:number[][],p:number[],open=false){let best=Infinity,index=0;for(let i=0;i<points.length-(open?1:0);i++){const a=points[i],b=points[(i+1)%points.length],dx=b[0]-a[0],dy=b[1]-a[1],t=Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/(dx*dx+dy*dy||1))),d=Math.hypot(p[0]-a[0]-t*dx,p[1]-a[1]-t*dy);if(d<best){best=d;index=i;}}return index;}
function insert(p?:number[]){const s=current();if(!s?.points)return;checkpoint();const i=p?closestEdge(s.points,p,s.open):Math.max(0,vertex),a=s.points[i],b=s.points[(i+1)%s.points.length];s.points.splice(i+1,0,p||[(a[0]+b[0])/2,(a[1]+b[1])/2]);vertex=i+1;saved();properties();}
canvas.onpointerdown=e=>{if(e.button!==0&&e.button!==1&&e.button!==2)return;canvas.focus();canvas.setPointerCapture(e.pointerId);const p=at(e),q=screen(e);cursor=p;
 if(tool==='pan'||space||e.button!==0){drag={kind:'pan',q,ox,oy};return;}
 if(tool==='walk'){actor=p;dirty=true;return;}
 if(tool==='add'||tool==='remove'){checkpoint();stroke=[p];drag={kind:'paint'};dirty=true;return;}
 let s=current(),handle=s&&handles(s).find(h=>Math.hypot(h.p[0]-p[0],h.p[1]-p[1])*zoom<13);
 if(!handle){const hit=shapes().reverse().find(s=>s.points?(s.open?Math.hypot(...[s.points[closestEdge(s.points!,p,true)][0]-p[0],s.points[closestEdge(s.points!,p,true)][1]-p[1]] as [number,number])<20/zoom:polygonContains(s.points,p[0],p[1])):s.ellipse?ellipseContains(s.ellipse,p[0],p[1]):s.point&&Math.hypot(s.point[0]-p[0],s.point[1]-p[1])<15/zoom);if(hit){selected=hit.id;vertex=-1;refresh();}return;}
 checkpoint();vertex=handle.kind==='point'?handle.index:-1;drag={kind:handle.kind,index:handle.index};properties();dirty=true;};
canvas.onpointermove=e=>{cursor=at(e);if(drag)floorDirty=true;if(drag?.kind==='pan'){const q=screen(e);ox=drag.ox+q[0]-drag.q[0];oy=drag.oy+q[1]-drag.q[1];}else if(drag?.kind==='paint'){if(Math.hypot(cursor[0]-stroke.at(-1)![0],cursor[1]-stroke.at(-1)![1])>Number(select('brush').value)/5)stroke.push(cursor);}else if(drag){const s=current();if(s){const p=cursor.map(v=>Math.round(v*4)/4);if(drag.kind==='point')s.points![drag.index]=p;if(drag.kind==='depth')s.structure![3]=p[1];if(drag.kind==='center'){s.ellipse![0]=p[0];s.ellipse![1]=p[1];}if(drag.kind==='rx')s.ellipse![2]=Math.min(20000,Math.abs(p[0]-s.ellipse![0]));if(drag.kind==='ry')s.ellipse![3]=Math.min(400,Math.abs(p[1]-s.ellipse![1]));if(drag.kind==='marker'){s.point![0]=p[0];s.point![1]=p[1];}}}dirty=true;};
function finish(){if(!drag)return;if(drag.kind==='paint'){const r=Number(select('brush').value)/2;for(let i=0;i<stroke.length;i++){const a=stroke[Math.max(0,i-1)],b=stroke[i],angle=Math.atan2(b[1]-a[1],b[0]-a[0]),points:number[][]=[];for(let k=0;k<=8;k++){const t=angle-Math.PI/2+k*Math.PI/8;points.push([b[0]+Math.cos(t)*r,b[1]+Math.sin(t)*r]);}for(let k=0;k<=8;k++){const t=angle+Math.PI/2+k*Math.PI/8;points.push([a[0]+Math.cos(t)*r,a[1]+Math.sin(t)*r]);}doc.patches.push({add:tool==='add',points});}stroke=[];refresh();}if(drag.kind!=='pan')saved();drag=null;properties();dirty=true;}
canvas.onpointerup=finish;canvas.onpointercancel=finish;canvas.onlostpointercapture=finish;canvas.oncontextmenu=e=>e.preventDefault();canvas.ondblclick=e=>{if(tool==='edit')insert(at(e as any));};canvas.onwheel=e=>{e.preventDefault();zoomAt(Math.exp(-e.deltaY*.0015),...screen(e) as [number,number]);};
const keys=new Set<string>();window.addEventListener('keydown',e=>{if((e.target as HTMLElement).matches('input,select,button'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo(e.shiftKey);return;}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();undo(true);return;}if(e.code==='Space'){space=true;e.preventDefault();}if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD'].includes(e.code)){keys.add(e.code);e.preventDefault();}if(e.key==='Delete')$('delete-point').click();});window.addEventListener('keyup',e=>{keys.delete(e.code);if(e.code==='Space')space=false;});window.addEventListener('blur',()=>{keys.clear();space=false;finish();});
$('undo').onclick=()=>undo();$('redo').onclick=()=>undo(true);$('fit').onclick=fit;$('zoom-in').onclick=()=>zoomAt(1.4);$('zoom-out').onclick=()=>zoomAt(1/1.4);
select('layer').onchange=()=>{layer=select('layer').value;vertex=-1;refresh();};select('shapes').onchange=()=>{selected=select('shapes').value;vertex=-1;properties();dirty=true;};select('tool').onchange=()=>{tool=select('tool').value;$('walk-pad').hidden=tool!=='walk';keys.clear();dirty=true;message(tool==='walk'?'Click to place your champion. WASD / arrows to walk; green feet fit, red feet are blocked.':tool==='add'?'Paint floor to join or widen paths. Solid object bases still block movement.':tool==='remove'?'Paint to remove walkable ground. Later paint strokes replace earlier ones.':'Drag white handles. Hold Space and drag to pan. Scroll to zoom.');};
$('add-point').onclick=()=>insert();$('delete-point').onclick=()=>{const s=current();if(s?.points&&vertex>=0&&s.points.length>(s.open?2:3)){checkpoint();s.points.splice(vertex,1);vertex=-1;saved();properties();}};
$('new-object').onclick=()=>{checkpoint();const x=(w/2-ox)/zoom,y=(h/2-oy)/zoom;let id='new-object-'+doc.structures.length;while(doc.structures.some(s=>s[0]===id))id+='-x';layer='foreground';select('layer').value=layer;tool='edit';select('tool').value=tool;doc.structures.push([id,[x,y,0,0],[[x-15,y-50],[x+15,y-50],[x+15,y],[x-15,y]],y]);selected=id;refresh();saved();};
for(const id of ['opacity','overlays'])$(id).oninput=()=>{dirty=true;};$('brush').oninput=()=>{$('brush-size').textContent=select('brush').value;dirty=true;};
select('jump').append(...doc.rooms.map((r,i)=>new Option(r[1],String(i))));select('jump').onchange=()=>{if(select('jump').value==='')return;const r=doc.rooms[Number(select('jump').value)];zoom=Math.min(w/280,h/280);ox=w/2-r[2][0]*zoom;oy=h/2-r[2][1]*zoom;actor=copy(r[4]);selected=r[0];refresh();};
select('champion').append(...Object.values(MONSTERS).map(m=>new Option(m.archetype,m.id)));select('champion').value='devourer';async function prepareArt(){artReady=false;const chosen=identity;try{await assets.prepare(chosen,'gameplay',true);if(chosen===identity)artReady=true;dirty=true;}catch{message('Champion preview art could not load. Choose another champion to retry.');}}select('champion').onchange=()=>{identity=createIdentity({monsterId:select('champion').value});void prepareArt();};void prepareArt();
$('save').onclick=()=>{try{const valid=validateMapDocument(doc),url=URL.createObjectURL(new Blob([JSON.stringify(valid,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=doc.map+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);message('Map exported. Send this JSON file back to apply it to the game.');}catch(e){message(String(e));}};
$('import').onclick=()=>($('file') as HTMLInputElement).click();$('file').onchange=async()=>{const input=$('file') as HTMLInputElement,file=input.files?.[0];if(!file)return;try{if(file.size>20e6)throw Error('Map file is too large (20 MB maximum).');const next=validateMapDocument(JSON.parse(await file.text()));checkpoint();doc=next;backgroundChanged();refresh();fit();saved();message('Map imported. Your previous edits are available with Undo.');}catch(e){message(String(e));}input.value='';};
$('reset').onclick=()=>{if(!confirm('Replace this editor draft with the current game map? You can Undo this.'))return;checkpoint();doc=validateMapDocument(REALM_MAP_DATA);backgroundChanged();refresh();fit();saved();};
let last=performance.now();function frame(t:number){const dt=Math.min(.04,(t-last)/1000);last=t;moving=false;if(tool==='walk'){const dx=Number(keys.has('KeyD')||keys.has('ArrowRight'))-Number(keys.has('KeyA')||keys.has('ArrowLeft')),dy=Number(keys.has('KeyS')||keys.has('ArrowDown'))-Number(keys.has('KeyW')||keys.has('ArrowUp')),len=Math.hypot(dx,dy);if(len){const speed=MONSTERS[identity.monsterId].speed/scale()*dt/len,nx=actor[0]+dx*speed,ny=actor[1]+dy*speed;if(documentWalkable(doc,nx,ny))actor=[nx,ny];else if(documentWalkable(doc,nx,actor[1]))actor[0]=nx;else if(documentWalkable(doc,actor[0],ny))actor[1]=ny;moving=true;}dirty=true;}if(dirty){dirty=false;render(t/1000);}requestAnimationFrame(frame);}backgroundChanged();refresh();message(draftMessage||'Choose a shrine to zoom in. Edit its floor or choose Walk / hide preview.');requestAnimationFrame(frame);

$('new-map').onclick=()=>($('background-file') as HTMLInputElement).click();
$('background-file').onchange=async()=>{const input=$('background-file') as HTMLInputElement,file=input.files?.[0];if(!file)return;try{if(!['image/png','image/webp','image/jpeg'].includes(file.type)||file.size>10e6)throw Error('Choose a PNG, WebP or JPEG under 10 MB.');const dataUrl=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file);});const img=new Image();img.src=dataUrl;await img.decode();if(img.width>16384||img.height>16384)throw Error('Image dimensions must be below 16,384 pixels.');checkpoint();doc=validateMapDocument({version:1,map:'custom-'+Date.now(),rooms:[],decks:[],structures:[],arena:[0,0,0,0],patches:[],markers:[],unitsPerPixel:1,background:{dataUrl,width:img.width,height:img.height}});actor=[img.width/2,img.height/2];backgroundChanged();refresh();fit();saved();message('New map ready. Add floor areas or paint ground; set map scale to compare champion size. Export includes this image.');}catch(e){message(String(e));}input.value='';};
$('scale').onchange=()=>{if(doc.map==='mana-abyss-v43'){select('scale').value='7.4';message('The existing Titan map is fixed at 7.4. Custom maps can set their own scale.');return;}const v=Number(select('scale').value);if(!Number.isFinite(v)||v<.1||v>100)return;checkpoint();doc.unitsPerPixel=v;saved();};
$('new-area').onclick=()=>{const x=(w/2-ox)/zoom,y=(h/2-oy)/zoom,r=70/zoom;checkpoint();const points=[[x-r,y-r],[x+r,y-r],[x+r,y+r],[x-r,y+r]];if(doc.map==='mana-abyss-v43'){doc.patches.push({add:true,points});selected='paint-'+(doc.patches.length-1);}else{const id='floor-'+Date.now();doc.decks.push([id,false,[[x-r/2,y],[x+r/2,y]],points]);selected=id;}layer='floor';select('layer').value=layer;tool='edit';select('tool').value=tool;refresh();saved();};
$('new-marker').onclick=()=>{const name=prompt('Marker name (spawn, entrance, relic, portal…)','Spawn');if(!name)return;checkpoint();const id='marker-'+Date.now();(doc.markers??=[]).push({id,name:name.slice(0,100),point:[(w/2-ox)/zoom,(h/2-oy)/zoom]});selected=id;layer='marker';select('layer').value=layer;refresh();saved();};

$('delete-area').onclick=()=>{const s=current();if(!s)return;const patch=s.id.startsWith('paint-')?Number(s.id.slice(6)):-1,si=doc.structures.findIndex(x=>x[0]===s.id),di=doc.decks.findIndex(x=>x[0]===s.id),mi=doc.markers?.findIndex(x=>x.id===s.id)??-1;const allowed=patch>=0||mi>=0||((layer==='base'||layer==='foreground')&&si>=(doc.map==='mana-abyss-v43'?7:0))||(doc.map!=='mana-abyss-v43'&&di>=0);if(!allowed){message('This is a required game area. Edit its points or paint corrections instead.');return;}if(!confirm('Remove '+s.name+'? Undo can restore it.'))return;checkpoint();if(patch>=0)doc.patches.splice(patch,1);else if(mi>=0)doc.markers!.splice(mi,1);else if(si>=0)doc.structures.splice(si,1);else if(di>=0)doc.decks.splice(di,1);vertex=-1;refresh();saved();};

for(const button of document.querySelectorAll<HTMLButtonElement>('#walk-pad button')){button.onpointerdown=e=>{e.preventDefault();button.setPointerCapture(e.pointerId);keys.add(button.dataset.code!);};button.onpointerup=button.onpointercancel=button.onlostpointercapture=()=>keys.delete(button.dataset.code!);}

$('controls').onclick=()=>{document.body.classList.toggle('controls-hidden');};
