import {type Profile,type StorageLike} from './profile.ts';
import {STAGE_GATES,trialDays} from './stage-access.ts';
import {MAX_PROGRESS_BYTES,IMPORT_BACKUP_KEY,progressExport,parseProgressExport,mergeProgress,applyProgressImport,undoProgressImport} from './progress-transfer.ts';
export function mountProgressTransfer(profile:Profile,storage:StorageLike|undefined,busy:()=>boolean,onApplied:()=>void){
 const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
 const status=el('progressTransferStatus'),preview=el('progressImportPreview'),file=el<HTMLInputElement>('progressFile'),undo=el<HTMLButtonElement>('undoProgress');
 let pending:Profile|null=null,generation=0;
 const refreshUndo=()=>{try{undo.hidden=!storage?.getItem(IMPORT_BACKUP_KEY);}catch{undo.hidden=true;}};
 const clear=()=>{pending=null;preview.hidden=true;file.value='';generation++;};
 const ready=()=>{if(busy()){status.textContent='Finish your current run before transferring progress.';return false;}return true;};
 refreshUndo();
 el('exportProgress').onclick=()=>{if(!ready())return;const url=URL.createObjectURL(new Blob([progressExport(profile)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='monster-mash-progress-'+new Date().toISOString().slice(0,10)+'.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent='Backup downloaded. Import this file on your other device before playing there. A run code does not transfer progress.';};
 el('importProgress').onclick=()=>{if(!ready())return;clear();file.click();};
 file.onchange=async()=>{if(!ready())return;const selected=file.files?.[0];if(!selected)return;const ticket=++generation;pending=null;preview.hidden=true;try{if(selected.size>MAX_PROGRESS_BYTES)throw Error('This file is too large to be a progress backup.');const incoming=parseProgressExport(await selected.text());if(ticket!==generation)return;if(!ready())return;const merged=mergeProgress(profile,incoming),gate=STAGE_GATES[0];pending=incoming;el('progressImportSummary').textContent=`From ${incoming.identity.name}: your saved progress will keep ${merged.progress.total.runs||0} incarnations, ${(merged.progress.total.kills||0).toLocaleString()} lifetime kills and ${Object.keys(merged.progress.titles).length} earned titles.${gate?' '+gate.title+': '+trialDays(merged.progress.trials,gate)+' / '+gate.days+' days with one champion.':''} The backup’s name, equipped title and monster colors will be used. Current rewards and bests are retained. Sound and FX settings stay on this device.`;preview.hidden=false;status.textContent='Review the backup, then confirm to import. Nothing has changed yet.';}catch(error){if(ticket!==generation)return;clear();status.textContent=error instanceof Error?error.message:'Could not read the progress backup. Your progress has not changed.';}};
 el('cancelProgressImport').onclick=()=>{clear();status.textContent='Import cancelled. Your progress has not changed.';};
 el('confirmProgressImport').onclick=()=>{if(!ready()||!pending)return;if(!storage){status.textContent='Browser storage is unavailable. Import was not applied.';return;}try{applyProgressImport(profile,pending,storage);}catch{status.textContent='Browser storage could not save the import. Your current progress has not changed.';return;}clear();onApplied();refreshUndo();status.textContent='Progress imported and saved. Stage opening dates still apply. You can undo this import here.';};
 undo.onclick=()=>{if(!ready()||!storage)return;if(!confirm('Undo the last import? This restores your progress from before that import, including its name and colors. Any progress earned since that import will be removed.'))return;try{undoProgressImport(profile,storage);}catch{status.textContent='Could not restore the backup. Your current progress has not changed.';return;}clear();onApplied();refreshUndo();status.textContent='Previous progress restored and saved.';};
}
