import {pointOnRealmZone,type RealmZone} from './realm-zones.ts';
type Ribbon={canvas:HTMLCanvasElement;path:Path2D;x:number;y:number;width:number;height:number};
// Only visible borders are rasterized, at most two small textures. Reusing the
// artwork along one closed path removes rotated strip seams and corner spikes.
export class RealmZoneArt{
 readonly capacity=2;cache=new Map<string,Ribbon>();
 private ribbon(z:RealmZone,texture:HTMLImageElement){let hit=this.cache.get(z.id);if(hit){this.cache.delete(z.id);this.cache.set(z.id,hit);return hit;}const pad=65,x=z.left-pad,y=z.top-pad,width=z.right-z.left+pad*2,height=z.bottom-z.top+pad*2,scale=Math.min(.55,768/Math.max(width,height)),canvas=document.createElement('canvas');canvas.width=Math.ceil(width*scale);canvas.height=Math.ceil(height*scale);const c=canvas.getContext('2d')!,path=new Path2D();z.points.forEach((p,i)=>i?path.lineTo(p.x,p.y):path.moveTo(p.x,p.y));path.closePath();c.scale(scale,scale);c.translate(-x,-y);c.lineJoin=c.lineCap='round';const titan=z.id==='titan',color=titan?'#9bb9ff':'#bb9dff';c.strokeStyle=color;c.shadowColor=color;c.shadowBlur=18*scale;c.globalAlpha=.24;c.lineWidth=29;c.stroke(path);c.globalAlpha=.4;c.lineWidth=13;c.stroke(path);c.shadowBlur=0;const strip=document.createElement('canvas');strip.width=128;strip.height=64;strip.getContext('2d')!.drawImage(texture,0,0,128,64);c.globalAlpha=.85;c.strokeStyle=c.createPattern(strip,'repeat')!;c.lineWidth=21;c.stroke(path);c.globalAlpha=.8;c.strokeStyle=titan?'#c6eeff':'#ece0ff';c.lineWidth=3;c.stroke(path);hit={canvas,path,x,y,width,height};while(this.cache.size>=this.capacity){const key=this.cache.keys().next().value!,old=this.cache.get(key)!;old.canvas.width=old.canvas.height=1;this.cache.delete(key);}this.cache.set(z.id,hit);return hit;}
 draw(c:CanvasRenderingContext2D,z:RealmZone,texture:HTMLImageElement,time:number,cx:number,cy:number,halfW:number,halfH:number,intensity:number){if(z.left>cx+halfW+80||z.right<cx-halfW-80||z.top>cy+halfH+80||z.bottom<cy-halfH-80)return;const r=this.ribbon(z,texture);c.save();c.globalAlpha=intensity*(.88+.09*Math.sin(time*1.7+(z.id==='titan'?0:2)));c.drawImage(r.canvas,r.x,r.y,r.width,r.height);c.globalAlpha=intensity*.65;c.strokeStyle=z.id==='titan'?'#dcf7ff':'#f1dbff';c.lineWidth=2;c.setLineDash([8,88]);c.lineDashOffset=-time*21;c.stroke(r.path);c.setLineDash([]);const count=z.id==='titan'?10:7;for(let i=0;i<count;i++){const p=pointOnRealmZone(z,i*z.length/count+time*29);if(Math.abs(p.x-cx)>halfW+35||Math.abs(p.y-cy)>halfH+35)continue;c.save();c.globalAlpha=intensity*(.12+.12*(.5+.5*Math.sin(time*2+i)));c.translate(p.x,p.y-2-Math.sin(time*1.8+i)*2);c.rotate(p.angle);c.drawImage(texture,-32,-12,64,24);c.restore();}c.restore();}
}
