import {REALM_GROTTOS,type RealmPoint} from './realm-layout.ts';
export type RealmZone={id:string;points:RealmPoint[];lengths:number[];length:number;left:number;top:number;right:number;bottom:number};
export const TITAN_SEAL={x:0,y:-38,rx:791,ry:632.8};
function zone(id:string,points:RealmPoint[]):RealmZone{const lengths=[0];for(let i=0;i<points.length;i++){const a=points[i],b=points[(i+1)%points.length];lengths.push(lengths.at(-1)!+Math.hypot(a.x-b.x,a.y-b.y));}return {id,points,lengths,length:lengths.at(-1)!,left:Math.min(...points.map(p=>p.x)),top:Math.min(...points.map(p=>p.y)),right:Math.max(...points.map(p=>p.x)),bottom:Math.max(...points.map(p=>p.y))};}
// Rounded corners are authored once. Animation never moves this boundary.
export function roundRealmOutline(points:RealmPoint[]){const out:RealmPoint[]=[];for(let i=0;i<points.length;i++){const a=points[(i+points.length-1)%points.length],b=points[i],c=points[(i+1)%points.length],ab=Math.hypot(b.x-a.x,b.y-a.y),bc=Math.hypot(c.x-b.x,c.y-b.y),r=Math.min(65,ab*.26,bc*.26),p={x:b.x+(a.x-b.x)*r/ab,y:b.y+(a.y-b.y)*r/ab},q={x:b.x+(c.x-b.x)*r/bc,y:b.y+(c.y-b.y)*r/bc};for(let j=0;j<=8;j++){const t=j/8;out.push({x:(1-t)**2*p.x+2*(1-t)*t*b.x+t*t*q.x,y:(1-t)**2*p.y+2*(1-t)*t*b.y+t*t*q.y});}}return out;}
export const REALM_TITAN_ZONE=zone('titan',Array.from({length:192},(_,i)=>({x:Math.cos(i/192*Math.PI*2)*TITAN_SEAL.rx,y:TITAN_SEAL.y+Math.sin(i/192*Math.PI*2)*TITAN_SEAL.ry})));
export const REALM_GUARDIAN_ZONES=REALM_GROTTOS.map(s=>zone('guardian-'+s.id,roundRealmOutline(s.floor.map(([x,y])=>({x:s.x+x,y:s.y+y})))));
export function pointOnRealmZone(z:RealmZone,distance:number){const d=((distance%z.length)+z.length)%z.length;let lo=0,hi=z.points.length-1;while(lo<hi){const mid=Math.ceil((lo+hi)/2);if(z.lengths[mid]<=d)lo=mid;else hi=mid-1;}const a=z.points[lo],b=z.points[(lo+1)%z.points.length],t=(d-z.lengths[lo])/(z.lengths[lo+1]-z.lengths[lo]||1);return {x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,angle:Math.atan2(b.y-a.y,b.x-a.x)};}
