import type {Game} from './simulation.ts';
import type {AbilityDef} from './content-monsters.ts';
import {ENEMIES} from './data.ts';
export type ScytheWave={x:number;y:number;angle:number;remaining:number;width:number;damage:number;source:string;kills:number;hit:Set<number>};
export const REAPER={maxWaves:24,speed:850,leech:.035,healPerSecond:42,healPerRelease:5};
export function harvestLife(g:Game,damage:number){if(g.time>=g.soulWindow){g.soulWindow=g.time+1;g.soulBudget=REAPER.healPerSecond+REAPER.healPerRelease*g.release;}const healed=Math.min(g.soulBudget,damage*REAPER.leech);g.soulBudget-=healed;if(healed>0&&g.player.hp<g.player.maxHp)g.soulGlow=.45;g.heal(healed);}
export function scytheWave(g:Game,angle:number,range:number,width:number,damage:number,source='scythe'){if(g.scytheWaves.length>=REAPER.maxWaves)return;g.scytheWaves.push({x:g.player.x,y:g.player.y,angle,remaining:range,width,damage:damage*g.powerScale(),source,kills:0,hit:new Set()});}
export function reaperAim(g:Game,range:number){const enemy=g.nearestEnemy(range);return enemy?Math.atan2(enemy.y-g.player.y,enemy.x-g.player.x):g.movementAngle;}
export function reaperSweep(g:Game,p:AbilityDef){g.area(g.player.x,g.player.y,p.radius,p.damage,'reapersweep',800);g.effect(g.player.x,g.player.y,'reaper-sweep',p.radius,.45,g.movementAngle);}
export function reaperBlink(g:Game,p:AbilityDef){const prey=g.nearestEnemy(p.radius);if(!prey)return;const old={x:g.player.x,y:g.player.y},angle=Math.atan2(prey.y-old.y,prey.x-old.x),landing={x:prey.x-Math.cos(angle)*90,y:prey.y-Math.sin(angle)*90};g.slideArena(landing,23);if(!g.insideMap(landing.x,landing.y))return;g.effect(old.x,old.y,'reaper-blink',100,.4);g.player.x=landing.x;g.player.y=landing.y;g.dodgeInvuln=Math.max(g.dodgeInvuln,.28);g.dodgeDeflected=true;g.area(landing.x,landing.y,145*g.releaseStats.radius,p.damage,'graveshift',420);g.effect(landing.x,landing.y,'reaper-blink',145,.5,angle);}
export function reaperVolley(g:Game,p:AbilityDef){const angle=reaperAim(g,p.radius);for(const spread of [-.24,0,.24])scytheWave(g,angle+spread,p.radius,48*g.releaseStats.radius,p.damage,'reapingarc');g.effect(g.player.x,g.player.y,'reaper-volley',140,.4,angle);}
export function updateReaper(g:Game,dt:number){g.soulGlow=Math.max(0,g.soulGlow-dt);if(g.reaperStorm>0){g.reaperStorm=Math.max(0,g.reaperStorm-dt);g.reaperPulse-=dt;if(g.reaperPulse<=0){g.reaperPulse=.38;const power=g.powers[3],angle=reaperAim(g,power.radius*g.releaseStats.radius);for(const offset of [-.32,.32])scytheWave(g,angle+offset,power.radius*g.releaseStats.radius,55*g.releaseStats.radius,power.damage,'moonstorm');if(++g.reaperSweeps%3===0){g.area(g.player.x,g.player.y,180*g.releaseStats.radius,power.damage,'moonstorm',420);g.effect(g.player.x,g.player.y,'reaper-sweep',180*g.releaseStats.radius,.4,angle);}}}
 for(let i=g.scytheWaves.length-1;i>=0;i--){const w=g.scytheWaves[i],step=Math.min(w.remaining,REAPER.speed*dt),ax=Math.cos(w.angle),ay=Math.sin(w.angle),sx=w.x,sy=w.y;g.nearby(sx+ax*step/2,sy+ay*step/2,w.width+step/2+65,e=>{if(w.hit.has(e.serial))return;const dx=e.x-sx,dy=e.y-sy,along=Math.max(0,Math.min(step,dx*ax+dy*ay)),r=w.width+ENEMIES[e.kind].radius;if((dx-ax*along)**2+(dy-ay*along)**2>=r*r)return;w.hit.add(e.serial);if(g.damage(e,w.damage,w.source,{x:sx-ax*100,y:sy-ay*100}))w.kills++;});w.x+=ax*step;w.y+=ay*step;w.remaining-=step;if(w.remaining<=0){g.completeAttack(w.kills,{},w.source);g.scytheWaves.splice(i,1);}}
}
