import {COURT_FEATS} from './court-feats.ts';
import {TITAN_FISSURE_RULES} from './champion-kits.ts';
import type {Comparison} from './personal-bests.ts';
import {MONSTERS,type Palette} from './content-monsters.ts';
import {EVENT} from './data.ts';
import {COLOSSUS,colossusWindowForRules} from './ashen-colossus.ts';
import {releaseAt} from './unbound.ts';
import {COURT,COURT_RULES,COURT_TEST_RULES,REAPER_RULES,COURT_UPGRADES,courtCombatLimit,courtSpeedBonus,courtScorePolicy,type CourtMission,type CourtStats} from './stage-two.ts';
export type RunRecord={version:1|2|3|4;rules:string;phase:number;name:string;kit?:'fissure';title?:string;monsterId?:string;colors?:Palette;newRecords?:string[];newTitles?:string[];sources?:Record<string,number>;comparison?:Comparison;seed:number;duration:number;score:number;kills:number;wave:number;elites:number;titans:number;multi:number;peak:number;feats:Record<string,number>;ended:string;reason:'overwhelmed'|'retired'|'cleared';release?:number;build?:string;court?:CourtStats;mission?:CourtMission;testing?:boolean};
// Retain shipped MM4 rules even after EVENT.rules advances.
export const MM4_RULESETS=['2026.10-v6-tester','2026.10-v7-movement','2026.10-v8-pursuit','2026.10-v9-escape','2026.10-v10-aegis','2026.10-v11-claw-waves','2026.10-v12-feast-waves','2026.10-v13-moving-claws','2026.10-v14-undead-hunt','2026.10-v15-autotarget-squad',EVENT.rules,'2026.10-v16-court-hunts','2026.10-v16-court-test','2026.10-v17-court-hunts','2026.10-v17-court-test','2026.10-v18-court-hunts','2026.10-v18-court-test','2026.10-v19-court-hunts','2026.10-v19-court-test','2026.10-v20-court-hunts','2026.10-v20-court-test','2026.10-v21-court-hunts','2026.10-v21-court-test','2026.10-v22-court-hunts','2026.10-v22-court-test','2026.10-v23-court-hunts','2026.10-v23-court-test','2026.10-v24-court-hunts','2026.10-v24-court-test','2026.10-v25-court-hunts','2026.10-v25-court-test','2026.10-v25-reaper','2026.10-v26-reaper','2026.10-v26-court-hunts','2026.10-v26-court-test','2026.10-v27-court-hunts','2026.10-v27-court-test','2026.10-v27-reaper','2026.10-v28-court-hunts','2026.10-v28-court-test','2026.10-v29-court-hunts','2026.10-v29-court-test','2026.10-v30-court-hunts','2026.10-v30-court-test',TITAN_FISSURE_RULES,REAPER_RULES,COURT_RULES,COURT_TEST_RULES] as const;
export const KNOWN_RULESETS=['2026.10-v1','2026.10-v2','2026.10-v3','2026.10-v4-unbound','2026.10-v5-feast',...MM4_RULESETS] as const;
// Client-side deterrence only. Not authoritative anti-cheat: shipped source contains
// everything needed to reconstruct this seal, so a determined attacker can forge codes.
const a=[42,194,16,177,95,202,112,18,221,64,175,42,88,17,200,97,215,33,154,54,3,214,119,81,242,7,130,55,188,14,75,206];
const b=[138,17,97,43,222,70,23,202,48,159,12,234,2,197,65,18,75,170,29,192,113,40,201,6,49,156,7,183,60,238,100,22];
let keyPromise:Promise<CryptoKey>|null=null;
function sealKey(){return keyPromise??=crypto.subtle.digest('SHA-256',Uint8Array.from(a,(v,i)=>v^b[(i*7)%b.length])).then(raw=>crypto.subtle.importKey('raw',raw,'AES-GCM',false,['encrypt','decrypt']));}
const ad=new TextEncoder().encode('MM4');
async function digest(bytes:Uint8Array){return new Uint8Array(await crypto.subtle.digest('SHA-256',bytes));}
const hex=(bytes:Uint8Array)=>Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');
const encodeBytes=(bytes:Uint8Array)=>btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const decodeBytes=(payload:string)=>Uint8Array.from(atob(payload.replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0));
const palette=(p:Palette)=>[p.primary,p.secondary,p.accent,p.power,...(p.skin?[p.skin]:[])];
function compact(run:RunRecord){if(!run.colors)throw Error('Missing cosmetic identity.');const parts:unknown[]=[run.rules,run.phase,run.name,run.title,run.monsterId,palette(run.colors),run.seed,run.duration,run.score,run.kills,run.wave,run.elites,run.titans,run.multi,run.peak,run.feats,run.ended,run.reason,run.release,run.build];if(run.court)parts.push({court:run.court,testing:run.testing===true,...(run.mission?{mission:run.mission}:{})});if(run.kit)parts.push({kit:run.kit});return parts;}
export async function encodeRun(run:RunRecord){validateRun(run);const bytes=new TextEncoder().encode(JSON.stringify(run.version>=3?compact(run):run));if(run.version===4){const iv=crypto.getRandomValues(new Uint8Array(12)),cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:ad},await sealKey(),bytes));const packed=new Uint8Array(iv.length+cipher.length);packed.set(iv);packed.set(cipher,iv.length);return 'MM4.'+encodeBytes(packed);}return `MM${run.version}.${encodeBytes(bytes)}.${hex((await digest(bytes)).slice(0,12))}`;}
function expand(parts:unknown,version:3|4):RunRecord{if(!Array.isArray(parts)||![20,21].includes(parts.length)||version===3&&parts.length!==20)throw Error('Invalid compact payload.');const [rules,phase,name,title,monsterId,c,seed,duration,score,kills,wave,elites,titans,multi,peak,feats,ended,reason,release,build,extra]=parts;const colors=Array.isArray(c)&&[4,5].includes(c.length)?{primary:c[0],secondary:c[1],accent:c[2],power:c[3],...(c.length===5?{skin:c[4]}:{})}:undefined;if(parts.length===21&&(!extra||typeof extra!=='object'||Array.isArray(extra)||('court' in extra?typeof extra.testing!=='boolean':!('kit' in extra))))throw Error('Invalid stage statistics.');return {version,rules,phase,name,title,monsterId,colors,seed,duration,score,kills,wave,elites,titans,multi,peak,feats,ended,reason,release,build,...(extra&&'court' in extra?{court:extra.court,testing:extra.testing,...(extra.mission?{mission:extra.mission}:{})}:{}),...(extra&&'kit' in extra?{kit:extra.kit}:{})} as RunRecord;}
const integer=(v:unknown,max:number)=>typeof v==='number'&&Number.isSafeInteger(v)&&v>=0&&v<=max;
export function validateRun(run:RunRecord){
 if(!run||![1,2,3,4].includes(run.version)||typeof run.name!=='string'||Array.from(run.name).length<1||Array.from(run.name).length>32||!KNOWN_RULESETS.includes(run.rules as typeof KNOWN_RULESETS[number])||!['overwhelmed','retired','cleared'].includes(run.reason))throw Error('Invalid run metadata or unknown ruleset.');
 if(!integer(run.phase,3)||!integer(run.seed,4294967295)||!integer(run.duration,86400)||!integer(run.score,1e12)||!integer(run.kills,1e9)||!integer(run.wave,2882)||!integer(run.elites,1e9)||!integer(run.titans,1e9)||!integer(run.multi,1e9)||typeof run.peak!=='number'||!Number.isFinite(run.peak)||run.peak<1||run.peak>5)throw Error('Invalid run statistics.');
 if(Math.abs(run.wave-(Math.floor(run.duration/EVENT.waveSeconds)+1))>1||run.multi>run.kills||run.elites+run.titans>run.kills||run.kills>run.duration*160+1000)throw Error('Inconsistent run statistics.');
 if(typeof run.ended!=='string'||!Number.isFinite(Date.parse(run.ended))||Date.parse(run.ended)<Date.UTC(2020,0,1)||Date.parse(run.ended)>Date.UTC(2100,0,1))throw Error('Invalid completion date.');
 if(!run.feats||typeof run.feats!=='object'||Array.isArray(run.feats)||Object.keys(run.feats).length>100||Object.entries(run.feats).some(([key,value])=>!/^[-.a-zA-Z0-9_]{1,64}$/.test(key)||!integer(value,1e6)))throw Error('Invalid feats.');
 if(run.version>=2){if(!Object.hasOwn(MONSTERS,run.monsterId)||typeof run.title!=='string'||Array.from(run.title).length>32||!run.colors||!['primary','secondary','accent','power'].every(k=>/^#[0-9a-f]{6}$/i.test(run.colors![k as keyof Palette])))throw Error('Invalid monster identity.');if(run.colors.skin!==undefined&&(run.monsterId!=='reaper'||!/^#[0-9a-f]{6}$/i.test(run.colors.skin)))throw Error('Invalid skin color.');}
 if(run.version>=3){if(!integer(run.release,4)||typeof run.build!=='string'||!/^[0-9a-f]{16}$/.test(run.build))throw Error('Invalid release or build metadata.');if(!run.court&&(run.release!<releaseAt(Math.max(0,run.duration-.51))||run.release!>releaseAt(run.duration+.51)))throw Error('Inconsistent release stage.');}
 if(run.version===3&&!['2026.10-v4-unbound','2026.10-v5-feast'].includes(run.rules))throw Error('Invalid MM3 ruleset.');
 if(run.version===4&&!MM4_RULESETS.includes(run.rules as typeof MM4_RULESETS[number]))throw Error('Invalid MM4 ruleset.');
 if(run.kit!==undefined&&(run.kit!=='fissure'||run.monsterId!=='titan'||run.phase!==0||run.rules!==TITAN_FISSURE_RULES)||run.rules===TITAN_FISSURE_RULES&&(run.monsterId!=='titan'||run.phase!==0||run.kit!=='fissure'||run.version!==4))throw Error('Invalid Titan kit or ruleset.');
 if(run.monsterId==='reaper'&&!/-v(25|26|27|28|29|30|31)-(court-(hunts|test)|reaper)$/.test(run.rules))throw Error('Reaper requires its release ruleset.');
 const courtRules=/^2026\.10-v(16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31)-court-(hunts|test)$/.test(run.rules);
 if(courtRules){const policy=courtScorePolicy(run.rules),s=run.court;if(run.version!==4||run.phase!==1||!s||typeof s!=='object'||Array.isArray(s)||Object.keys(s).length!==8||!['hunts','captains','guards','impacts','close','seals','lost','bonus'].every(k=>integer(s[k as keyof CourtStats],1e9))||s.captains>s.hunts||s.captains>run.kills||s.guards>s.hunts*5||s.impacts>s.guards||s.close>s.captains||s.seals+s.lost>s.captains||s.bonus!==s.seals*policy.sealBonus+s.guards*policy.guardBonus+s.impacts*policy.impactBonus+s.close*policy.closeBonus||s.bonus>run.score||Boolean(run.testing)!==run.rules.endsWith('-court-test'))throw Error('Invalid Court hunt statistics.');}
 if(courtRules){const m=run.mission,s=run.court!;if(!m||m.total!==COURT.total||typeof m.cleared!=='boolean'||!Array.isArray(m.upgrades)||m.upgrades.length>Math.min(9,s.captains)||m.upgrades.some(id=>!COURT_UPGRADES.some(u=>u.id===id))||COURT_UPGRADES.some(u=>m.upgrades.filter(id=>id===u.id).length>3)||s.hunts>COURT.total||s.captains>COURT.total||m.cleared!==(run.reason==='cleared')||m.cleared!==(s.captains===COURT.total)||run.release!==(/-v(19|20|21|22|23|24|25|26|27|28|29|30|31)-/.test(run.rules)?COURT.startRelease:Math.min(4,Math.floor(m.upgrades.length/2))))throw Error('Invalid hunt mission progression.');}
 if(courtRules&&/-v(18|19|20|21|22|23|24|25|26|27|28|29|30|31)-/.test(run.rules)){const scoring=run.mission!.scoring,s=run.court!;if(!scoring||typeof scoring!=='object'||Array.isArray(scoring)||Object.keys(scoring).length!==3||!['combat','captain','speed'].every(k=>integer(scoring[k as keyof typeof scoring],1e9))||scoring.combat>courtCombatLimit(s.captains)||scoring.captain<s.captains*600||scoring.captain>s.captains*3000||scoring.speed!==(run.reason==='cleared'?courtSpeedBonus(run.duration,run.rules):0)||run.score!==scoring.combat+scoring.captain+s.bonus+scoring.speed+(run.mission!.colossus?.reward||0))throw Error('Invalid hunt score budget or clear-time bonus.');}
 else if(courtRules&&run.mission?.scoring)throw Error('Historical hunt rules do not record the new score budget.');
 if(courtRules&&/-v(29|30|31)-court-/.test(run.rules)&&Object.keys(run.feats).some(id=>!COURT_FEATS.some(f=>f.id===id)))throw Error('Invalid hunt feat for this stage.');
 const boss=run.mission?.colossus;if(boss!==undefined){if(!courtRules||!/-v(28|29|30|31)-court-/.test(run.rules)||!boss||typeof boss!=='object'||Array.isArray(boss)||Object.keys(boss).some(k=>!['spawnedAt','defeatedAt','reward'].includes(k))||!integer(boss.spawnedAt,COLOSSUS.lastArrival-1)||boss.spawnedAt>run.duration||run.court!.captains<COLOSSUS.captains||boss.reward!==(boss.defeatedAt===undefined?0:COLOSSUS.reward)||boss.defeatedAt!==undefined&&(!integer(boss.defeatedAt,run.duration)||boss.defeatedAt<boss.spawnedAt||boss.defeatedAt>boss.spawnedAt+colossusWindowForRules(run.rules)||run.titans<1))throw Error('Invalid Ashen Colossus reward or encounter window.');}
 if(!courtRules&&(run.court||run.testing||run.mission||run.reason==='cleared'))throw Error('Stage statistics require the Court ruleset.');
}
export async function decodeRun(code:string):Promise<RunRecord>{
 const value=code.trim();if(value.length>10000)throw Error('Run code is too long.');const [prefix,payload,checksum,...rest]=value.split('.');if(!payload||!/^[A-Za-z0-9_-]+$/.test(payload))throw Error('Unrecognized run code.');
 let bytes:Uint8Array;try{bytes=decodeBytes(payload);}catch{throw Error('Malformed run code.');}
 if(prefix==='MM4'){if(checksum||rest.length||bytes.length<29)throw Error('Unrecognized run code.');let plain:Uint8Array;try{plain=new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes.slice(0,12),additionalData:ad},await sealKey(),bytes.slice(12)));}catch{throw Error('INVALID / MODIFIED RUN CODE: authentication failed.');}let parsed:unknown;try{parsed=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(plain));}catch{throw Error('Malformed run data.');}const run=expand(parsed,4);validateRun(run);if(JSON.stringify(compact(run))!==new TextDecoder().decode(plain))throw Error('Noncanonical run data.');return run;}
 if(!['MM1','MM2','MM3'].includes(prefix)||!checksum||rest.length||!/^[0-9a-f]{24}$/.test(checksum))throw Error('Unrecognized run code.');
 if(hex((await digest(bytes)).slice(0,12))!==checksum)throw Error('INVALID / MODIFIED RUN CODE: integrity check failed.');
 let parsed:unknown;try{parsed=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes));}catch{throw Error('Malformed run data.');}
 const run=prefix==='MM3'?expand(parsed,3):parsed as RunRecord;if(prefix!=='MM'+run.version)throw Error('Format mismatch.');validateRun(run);
 if(prefix==='MM3'&&JSON.stringify(compact(run))!==new TextDecoder().decode(bytes))throw Error('Noncanonical run data.');return run;
}
