import {titanKitForStage,titanKitLabel} from './champion-kits.ts';
import {CHAMPION_TIPS,COURT_TIPS,scenarioText} from './player-guidance.ts';
import {bestKey} from './personal-bests.ts';
import {EVENT} from './data.ts';
import {rulesForStage} from './stage-two.ts';
import {MONSTERS,ABILITIES,abilitiesForStage,abilityLabel,SWATCHES,SKIN_SWATCHES,BASE_TITLES,type Channel} from './content-monsters.ts';
import {createIdentity} from './identity.ts';
import {availableTitles,type Profile} from './profile.ts';
import {ACHIEVEMENTS} from './content-records.ts';
import {STAGE_GATES} from './stage-access.ts';
import {TITLES,titleProgress} from './content-titles.ts';
import {featsForStage} from './court-feats.ts';
import {defaultContentAccess,titleVisible,titleLabelVisible,visibleIdentity,type ContentAccess} from './content-visibility.ts';
import {SUSTAIN_TEXT} from './balance.ts';
const el=(id:string)=>document.getElementById(id)!;
export function mountSelection(profile:Profile,onChange:()=>void,selectedPhase=()=>EVENT.phase,testing=false,access:ContentAccess=defaultContentAccess(testing)){
 const canSelect=access.champion;
 const name=el('name') as HTMLInputElement;name.maxLength=32;name.value=profile.identity.name;
 const roster=el('roster'),title=el('title') as HTMLSelectElement;
 const refresh=()=>{const identity=visibleIdentity(profile,access),m=MONSTERS[identity.monsterId],titanKit=titanKitForStage(selectedPhase(),profile.titanKit,access.stage(1));el('titanKitChoice').hidden=m.id!=='titan'||selectedPhase()!==0||!access.stage(1);(el('titanKit') as HTMLSelectElement).value=titanKit;el('selectionName').textContent=name.value.trim()||'Unnamed Calamity';el('className').textContent=m.archetype+' · '+m.rank;el('description').textContent=m.description;el('selectionTitle').textContent=identity.title||'Choose a title to carry with your legend';el('championTip').textContent=CHAMPION_TIPS[m.id]+(selectedPhase()===1?' '+COURT_TIPS[m.id]:'');const best=profile.personalBests[bestKey({monsterId:m.id,rules:rulesForStage(selectedPhase(),testing,m.id,titanKit),phase:selectedPhase(),reason:selectedPhase()===1?'cleared':'overwhelmed'})];el('menuPersonalBest').textContent=best?(selectedPhase()===1?'Your fastest clear · '+Math.floor(best.seconds/60)+':'+String(best.seconds%60).padStart(2,'0'):'Your best on this stage · '+best.score.toLocaleString()+' Dominance'):'Your first completed run will set a personal best for this champion and stage.';
 roster.replaceChildren();for(const monster of Object.values(MONSTERS)){if(!canSelect(monster.id))continue;const b=document.createElement('button');b.type='button';b.textContent=monster.archetype;b.title=monster.archetype;b.dataset.monster=monster.id;b.setAttribute('aria-pressed',String(m.id===monster.id));b.onclick=()=>{if(!canSelect(monster.id))return;profile.identity=createIdentity({...profile.identity,name:name.value,monsterId:monster.id,colors:profile.palettes[monster.id]});refresh();onChange();};roster.append(b);}
 title.replaceChildren();for(const [groupName,labels] of [['Starter titles',BASE_TITLES],['Earned prestige',availableTitles(profile).filter(t=>!BASE_TITLES.includes(t)&&titleLabelVisible(t,access))]] as [string,string[]][]){if(!labels.length)continue;const group=document.createElement('optgroup');group.label=groupName;for(const label of labels)group.append(new Option(label||'No title',label));title.append(group);}title.value=identity.title;
 el('kit').replaceChildren();for(const [label,description] of [[m.basic.name+' · BASIC',m.basic.description],...abilitiesForStage(m.id,selectedPhase(),titanKit).map((p,i)=>[abilityLabel(p)+(i===3?' · ULTIMATE':'')+' · '+p.cooldown+'s',p.description]),[m.passive.name+' · PASSIVE',m.passive.description],['SURVIVAL',SUSTAIN_TEXT[m.id]],...(selectedPhase()===1?[['ASHEN WILDS RULES','Captains grant boons and valuable seals. Healing is reduced here; use healing oases to recover. Flank guards or break their protection. Finish quickly for a larger clear bonus.']]:[])]){const row=document.createElement('div'),b=document.createElement('b'),p=document.createElement('p');b.textContent=label;p.textContent=description;row.append(b,p);el('kit').append(row);}
 el('colors').replaceChildren();for(const channel of m.channels){const group=document.createElement('fieldset'),legend=document.createElement('legend');legend.textContent=channel.label;group.append(legend);for(const color of channel.id==='skin'?SKIN_SWATCHES:SWATCHES){const b=document.createElement('button');b.type='button';b.className='swatch';b.style.background=color;b.dataset.channel=channel.id;b.dataset.color=color;b.setAttribute('aria-label',channel.label+' '+color);b.setAttribute('aria-pressed',String(identity.colors[channel.id]===color));b.onclick=()=>{if(!canSelect(m.id))return;profile.identity=createIdentity(identity);profile.identity.colors[channel.id as Channel]=color;profile.palettes[m.id]={...profile.identity.colors};refresh();onChange();};group.append(b);}el('colors').append(group);}
 for(const node of document.querySelectorAll<HTMLElement>('[data-unlock-stage]'))node.hidden=!access.stage(Number(node.dataset.unlockStage));
 };(el('titanKit') as HTMLSelectElement).onchange=()=>{if(selectedPhase()!==0||!access.stage(1))return;profile.titanKit=(el('titanKit') as HTMLSelectElement).value==='fissure'?'fissure':'throw';refresh();onChange();};name.addEventListener('input',()=>{profile.identity=createIdentity({...profile.identity,name:name.value});el('selectionName').textContent=profile.identity.name;onChange();});title.onchange=()=>{profile.identity.title=title.value;el('selectionTitle').textContent=title.value||'Choose a title to carry with your legend';onChange();};refresh();return refresh;
}
export function showRecords(profile:Profile,phase=EVENT.phase,testing=false,access:ContentAccess=defaultContentAccess(testing)){
 const identity=visibleIdentity(profile,access),titles=TITLES.filter(t=>titleVisible(t,access));
 el('recordIdentity').textContent=[identity.name,identity.title,MONSTERS[identity.monsterId].archetype].filter(Boolean).join(' · ');el('bestScope').textContent=scenarioText(phase)+' · '+(phase===0?'Separate champion and kit records':rulesForStage(phase,testing))+' · saved in this browser';el('personalBestList').replaceChildren();for(const monster of Object.values(MONSTERS)){if(!access.champion(monster.id))continue;const card=document.createElement('article');card.className='record';const h=document.createElement('h3');h.textContent=monster.archetype;card.append(h);for(const choice of (monster.id==='titan'&&phase===0&&access.stage(1)?['throw','fissure']:['throw']) as ('throw'|'fissure')[])for(const reason of (phase===1?['cleared','overwhelmed','retired']:['overwhelmed','retired']) as ('cleared'|'overwhelmed'|'retired')[]){const best=profile.personalBests[bestKey({monsterId:monster.id,rules:rulesForStage(phase,testing,monster.id,choice),phase,reason})],row=document.createElement('p');row.textContent=(titanKitLabel(monster.id,phase,choice)?titanKitLabel(monster.id,phase,choice)+' · ':'')+(reason==='cleared'?'Cleared hunts':reason==='retired'?'Practice':'Completed runs')+' · '+(best?best.score.toLocaleString()+' Dominance · '+(reason==='cleared'?'fastest clear ':'best survival ')+Math.floor(best.seconds/60)+':'+String(best.seconds%60).padStart(2,'0'):'No run yet');card.append(row);}el('personalBestList').append(card);}el('recordList').replaceChildren();el('titleList').replaceChildren();el('featList').replaceChildren();
 const p=profile.progress;el('recordSummary').textContent=(p.total.kills||0).toLocaleString()+' lifetime slain · '+Math.floor(p.total.dominance||0).toLocaleString()+' lifetime Dominance · '+(p.total.runs||0)+' incarnations ≥60s. Cosmetic records span all rulesets. Compare competition scores only within the same ruleset. Saved in this browser.';
 for(const a of ACHIEVEMENTS){if(a.metric.startsWith('court')&&!access.stage(1)||a.archetype&&!access.champion(a.archetype))continue;const r=profile.records[a.id],card=document.createElement('article');card.className='record '+(r?.unlockedAt?'unlocked':'');const h=document.createElement('h3');h.textContent=a.icon+' '+a.name;const state=document.createElement('span');state.textContent=r?.unlockedAt?'EARNED · '+new Date(r.unlockedAt).toLocaleDateString():'IN PROGRESS';const description=document.createElement('p');description.textContent=a.condition;const bar=document.createElement('progress');bar.max=a.target;bar.value=Math.min(a.target,r?.best||0);bar.setAttribute('aria-label',a.name+' progress');const best=document.createElement('p');best.textContent='Best: '+Math.floor(r?.best||0).toLocaleString()+' / '+a.target.toLocaleString();card.append(h,state,description,bar,best);el('recordList').append(card);}
 const earned=titles.filter(t=>p.titles[t.id]).length;el('titleSummary').textContent=earned+' / '+titles.length+' prestige titles earned. Every listed condition is required. The Gatebreaker grants Stage 2 access for every champion once it opens; other titles are cosmetic.'+(p.legacyTitles.length?' Legacy rewards preserved: '+p.legacyTitles.filter(t=>titleLabelVisible(t,access)).join(', ')+'.':'');
 for(const family of new Set(['Stage passage',...titles.map(t=>t.family)])){const section=document.createElement('details'),summary=document.createElement('summary'),grid=document.createElement('div'),group=titles.filter(t=>t.family===family);section.className='record-family';section.dataset.family=family;summary.textContent=family+' · '+group.filter(t=>p.titles[t.id]).length+' / '+group.length+' earned';grid.className='record-grid';section.append(summary,grid);el('titleList').append(section);for(const t of group){const card=document.createElement('details'),name=document.createElement('summary');card.className='record '+(p.titles[t.id]?'unlocked':'');card.dataset.title=t.id;name.textContent=t.name+' · '+(p.titles[t.id]?'EARNED':'IN PROGRESS');card.append(name);const gate=STAGE_GATES.find(g=>g.titleId===t.id);if(gate){const explanation=document.createElement('p');explanation.textContent='Complete '+gate.days+' different days with one champion. Each day: '+Math.floor(gate.minSeconds/60)+':'+String(gate.minSeconds%60).padStart(2,'0')+' and '+gate.minKills.toLocaleString()+' kills in Stage '+(gate.sourcePhase+1)+'. Any one completed line earns the title; Stage '+(gate.phase+1)+' access opens for everyone in your roster on its opening date.';card.append(explanation);for(const monster of Object.values(MONSTERS).filter(m=>m.unlockStage===undefined||gate.sourcePhase>0&&access.champion(m.id))){const days=p.trials[gate.titleId]?.[monster.id]??[],label=document.createElement('p'),bar=document.createElement('progress');label.textContent=monster.archetype+' · '+days.length+' / '+gate.days+' qualifying days';label.dataset.trialChampion=monster.id;bar.max=gate.days;bar.value=days.length;bar.setAttribute('aria-label',gate.title+' · '+monster.archetype+' progress');card.append(label,bar);}}else for(const r of titleProgress(p,t)){const label=document.createElement('p'),bar=document.createElement('progress');label.textContent=Math.floor(r.value).toLocaleString()+' / '+r.target.toLocaleString()+' '+r.label;bar.max=r.target;bar.value=Math.min(r.target,r.value);bar.setAttribute('aria-label',t.name+' '+r.label);card.append(label,bar);}grid.append(card);}}
 el('featStageDescription').textContent=phase===1?'STAGE 2 · Hunt feats: every champion can earn these.':'STAGE 1 · Arena feats';
 for(const f of featsForStage(phase)){const card=document.createElement('details'),h=document.createElement('summary'),description=document.createElement('p');card.className='record';card.dataset.feat=f.id;h.textContent=f.name;description.textContent=f.condition+' +'+f.bonus+' Dominance. '+(phase===1?'Once per captain; feat bonuses share the capped combat score budget.':'Repeat cooldown: '+f.cooldown+'s.');card.append(h,description);el('featList').append(card);}
 el('records').hidden=false;el('records').scrollTop=0;
}
