import {CHAMPION_TIPS,scenarioText} from './player-guidance.ts';
import {bestKey} from './personal-bests.ts';
import {EVENT} from './data.ts';
import {MONSTERS,ABILITIES,abilityLabel,SWATCHES,BASE_TITLES,type Channel} from './content-monsters.ts';
import {createIdentity} from './identity.ts';
import {availableTitles,type Profile} from './profile.ts';
import {ACHIEVEMENTS,FEAT_CONDITIONS} from './content-records.ts';
import {TITLES,titleProgress} from './content-titles.ts';
import {FEATS} from './data.ts';
import {SUSTAIN_TEXT} from './balance.ts';
const el=(id:string)=>document.getElementById(id)!;
export function mountSelection(profile:Profile,onChange:()=>void){
 const name=el('name') as HTMLInputElement;name.maxLength=32;name.value=profile.identity.name;
 const roster=el('roster'),title=el('title') as HTMLSelectElement;
 const refresh=()=>{const m=MONSTERS[profile.identity.monsterId];el('selectionName').textContent=name.value.trim()||'Unnamed Calamity';el('className').textContent=m.archetype+' · '+m.rank;el('description').textContent=m.description;el('selectionTitle').textContent=profile.identity.title||'Choose a title to carry with your legend';el('championTip').textContent=CHAMPION_TIPS[m.id];const best=profile.personalBests[bestKey({monsterId:m.id,rules:EVENT.rules,phase:EVENT.phase,reason:'overwhelmed'})];el('menuPersonalBest').textContent=best?'Your best this week · '+best.score.toLocaleString()+' Dominance':'Your first completed run will set a personal best for this champion and week.';
 roster.replaceChildren();for(const monster of Object.values(MONSTERS)){const b=document.createElement('button');b.type='button';b.textContent=monster.archetype;b.dataset.monster=monster.id;b.setAttribute('aria-pressed',String(m.id===monster.id));b.onclick=()=>{profile.identity=createIdentity({...profile.identity,name:name.value,monsterId:monster.id,colors:profile.palettes[monster.id]});refresh();onChange();};roster.append(b);}
 title.replaceChildren();for(const [groupName,labels] of [['Starter titles',BASE_TITLES],['Earned prestige',availableTitles(profile).filter(t=>!BASE_TITLES.includes(t))]] as [string,string[]][]){if(!labels.length)continue;const group=document.createElement('optgroup');group.label=groupName;for(const label of labels)group.append(new Option(label||'No title',label));title.append(group);}title.value=profile.identity.title;
 el('kit').replaceChildren();for(const [label,description] of [[m.basic.name+' · BASIC',m.basic.description],...m.abilities.map((id,i)=>[abilityLabel(ABILITIES[id])+(i===3?' · ULTIMATE':'')+' · '+ABILITIES[id].cooldown+'s',ABILITIES[id].description]),[m.passive.name+' · PASSIVE',m.passive.description],['SURVIVAL',SUSTAIN_TEXT[m.id]]]){const row=document.createElement('div'),b=document.createElement('b'),p=document.createElement('p');b.textContent=label;p.textContent=description;row.append(b,p);el('kit').append(row);}
 el('colors').replaceChildren();for(const channel of m.channels){const group=document.createElement('fieldset'),legend=document.createElement('legend');legend.textContent=channel.label;group.append(legend);for(const color of SWATCHES){const b=document.createElement('button');b.type='button';b.className='swatch';b.style.background=color;b.dataset.channel=channel.id;b.dataset.color=color;b.setAttribute('aria-label',channel.label+' '+color);b.setAttribute('aria-pressed',String(profile.identity.colors[channel.id]===color));b.onclick=()=>{profile.identity.colors[channel.id as Channel]=color;profile.palettes[m.id]={...profile.identity.colors};refresh();onChange();};group.append(b);}el('colors').append(group);}
 };name.addEventListener('input',()=>{profile.identity=createIdentity({...profile.identity,name:name.value});el('selectionName').textContent=profile.identity.name;onChange();});title.onchange=()=>{profile.identity.title=title.value;el('selectionTitle').textContent=title.value||'Choose a title to carry with your legend';onChange();};refresh();return refresh;
}
export function showRecords(profile:Profile){
 el('recordIdentity').textContent=[profile.identity.name,profile.identity.title,MONSTERS[profile.identity.monsterId].archetype].filter(Boolean).join(' · ');el('bestScope').textContent=scenarioText()+' · '+EVENT.rules+' · saved in this browser';el('personalBestList').replaceChildren();for(const monster of Object.values(MONSTERS)){const card=document.createElement('article');card.className='record';const h=document.createElement('h3');h.textContent=monster.archetype;card.append(h);for(const reason of ['overwhelmed','retired'] as const){const best=profile.personalBests[bestKey({monsterId:monster.id,rules:EVENT.rules,phase:EVENT.phase,reason})],row=document.createElement('p');row.textContent=(reason==='retired'?'Practice':'Completed runs')+' · '+(best?best.score.toLocaleString()+' Dominance · best survival '+Math.floor(best.seconds/60)+':'+String(best.seconds%60).padStart(2,'0'):'No run yet');card.append(row);}el('personalBestList').append(card);}el('recordList').replaceChildren();el('titleList').replaceChildren();el('featList').replaceChildren();
 const p=profile.progress;el('recordSummary').textContent=(p.total.kills||0).toLocaleString()+' lifetime slain · '+Math.floor(p.total.dominance||0).toLocaleString()+' lifetime Dominance · '+(p.total.runs||0)+' incarnations ≥60s. Cosmetic records span all rulesets. Compare competition scores only within the same ruleset. Saved in this browser.';
 for(const a of ACHIEVEMENTS){const r=profile.records[a.id],card=document.createElement('article');card.className='record '+(r?.unlockedAt?'unlocked':'');const h=document.createElement('h3');h.textContent=a.icon+' '+a.name;const state=document.createElement('span');state.textContent=r?.unlockedAt?'EARNED · '+new Date(r.unlockedAt).toLocaleDateString():'IN PROGRESS';const description=document.createElement('p');description.textContent=a.condition;const bar=document.createElement('progress');bar.max=a.target;bar.value=Math.min(a.target,r?.best||0);bar.setAttribute('aria-label',a.name+' progress');const best=document.createElement('p');best.textContent='Best: '+Math.floor(r?.best||0).toLocaleString()+' / '+a.target.toLocaleString();card.append(h,state,description,bar,best);el('recordList').append(card);}
 const earned=TITLES.filter(t=>p.titles[t.id]).length;el('titleSummary').textContent=earned+' / '+TITLES.length+' prestige titles earned. Every listed condition is required. Titles are cosmetic.'+(p.legacyTitles.length?' Legacy rewards preserved: '+p.legacyTitles.join(', ')+'.':'');
 for(const family of new Set(TITLES.map(t=>t.family))){const section=document.createElement('section'),h=document.createElement('h3'),grid=document.createElement('div');h.textContent=family;grid.className='record-grid';section.append(h,grid);el('titleList').append(section);for(const t of TITLES.filter(t=>t.family===family)){const card=document.createElement('article'),name=document.createElement('h4'),state=document.createElement('span');card.className='record '+(p.titles[t.id]?'unlocked':'');name.textContent=t.name;state.textContent=p.titles[t.id]?'EARNED · '+new Date(p.titles[t.id]).toLocaleDateString():'LOCKED';card.append(name,state);for(const r of titleProgress(p,t)){const label=document.createElement('p'),bar=document.createElement('progress');label.textContent=Math.floor(r.value).toLocaleString()+' / '+r.target.toLocaleString()+' '+r.label;bar.max=r.target;bar.value=Math.min(r.target,r.value);bar.setAttribute('aria-label',t.name+' '+r.label);card.append(label,bar);}grid.append(card);}}
 for(const f of FEATS){const card=document.createElement('article'),h=document.createElement('h3'),description=document.createElement('p');card.className='record';h.textContent=f.name;description.textContent=FEAT_CONDITIONS[f.id]+' +'+f.bonus+' Dominance. Repeat cooldown: '+f.cooldown+'s.';card.append(h,description);el('featList').append(card);}
 el('records').hidden=false;el('records').scrollTop=0;
}
