import {updateRelicPowers,type RelicPulse} from './relic-powers.ts';
import {updateLycanthrope,parkourLanding} from './lycanthrope.ts';
import {createTitanRealm,seedTitanRealm,updateTitanRealm,realmDamage,realmKill,realmEnemyMotion,realmScoreCredit,castRealmPower,activeRealmNature,sourceNature,type TitanRealmState,type RealmUnit} from './stage-three.ts';
import {insideRealm,slideRealm,moveRealm,REALM_START,inTitanArena} from './titan-realm-map.ts';
import {titanKitForStage,type TitanKit} from './champion-kits.ts';
import {courtFeatHit,courtSlamStart,courtSlamEnd} from './court-feats.ts';
import {harvestLife,scytheWave,updateReaper,reaperTarget,reaperTappedEnemy,type ScytheWave} from './reaper.ts';
import {releaseAt,releaseStats,releasedPower} from './unbound.ts';
import {slideTorches} from './arena.ts';
import {COURT_RADIUS,insideCourt,slideCourt,courtSteer} from './court-map.ts';
import {fissureMotion,updateFissures,type TitanFissure} from './titan-fissure.ts';
import {checkColossusArrival,finishColossus,colossusMotion,colossusDamage,dismissColossus} from './ashen-colossus.ts';
import { ENEMIES, EVENT, PHASES, type EnemyKind } from './data.ts';
import { Score } from './scoring.ts';
import {ABILITIES,MONSTERS,abilitiesForStage} from './content-monsters.ts';
import {createIdentity,type Identity} from './identity.ts';
import {POWER_HANDLERS} from './powers.ts';
import {MASSACRES,SCORING} from './content-records.ts';
const DESCENDING_MASSACRES=[...MASSACRES].reverse();
import {createServants,updateServants} from './servants.ts';
import {threatAt,INTRODUCTIONS,OPENING,SUSTAIN,CLAW_WAVE,enemyMovementSpeed} from './balance.ts';
import {COURT,createCourt,courtDamage,courtKill,courtEnemyMotion,courtContactScale,updateCourt,courtScoreCredit,courtRelease,upgradeRank,type CourtState,type CourtUnit} from './stage-two.ts';
export type Enemy={active:boolean;kind:EnemyKind;x:number;y:number;hp:number;maxHp:number;vx:number;vy:number;timer:number;windup:number;flash:number;serial:number;corruptUntil?:number;rushing?:boolean;court?:CourtUnit;colossus?:{expiresAt:number};snaredUntil?:number;fearedUntil?:number;realm?:RealmUnit};
export type DeathArt={source:string;sprite:string};
export type Effect={x:number;y:number;kind:string;life:number;max:number;radius:number;angle:number;death?:DeathArt};
export type Shot={x:number;y:number;vx:number;vy:number;life:number;damage:number};
export type ClawWave={x:number;y:number;angle:number;remaining:number;width:number;damage:number;kills:number;hit:Set<number>};
export type Input={x:number;y:number;aimX:number;aimY:number;aiming:boolean};
export class Game {
 relicPulses:RelicPulse[]=[];release=0;releaseTime=0;vault:{from:{x:number;y:number};to:{x:number;y:number};elapsed:number;duration:number;power:typeof ABILITIES.wolfbound}|null=null;moonFuryTarget:Enemy|null=null;moonFuryHits=new Set<number>();moonFury=0;moonFuryPulse=0;moonFuryVisited=new Set<number>();moonFuryOrigin={x:0,y:0};moonFuryView={x:640,y:360};moonFuryPower=ABILITIES.moonfury;
 private releaseCache=releaseStats('sovereign',0);private cachedStage=-1;private cachedBoonCount=-1;
 get releaseStats(){const count=this.court?.upgrades.length??0;if(this.cachedStage!==this.release||this.cachedBoonCount!==count){this.cachedStage=this.release;this.cachedBoonCount=count;const base=releaseStats(this.monster.id,this.release);this.releaseCache=this.court?{...base,damage:base.damage*(1+.18*upgradeRank(this,'power')),move:base.move*(1+.12*upgradeRank(this,'haste')),radius:base.radius*(1+.12*upgradeRank(this,'reach')),cooldown:base.cooldown*Math.pow(.9,upgradeRank(this,'recharge'))}:base;}return this.releaseCache;}

 seed:number; rng:number; phase:number; time=0; wave=0; ended=false; score=new Score();
 player={x:0,y:0,hp:1000,maxHp:1000,angle:0,invuln:0,rage:0};
 enemies:Enemy[]=Array.from({length:EVENT.maxEnemies},()=>({active:false,kind:'thrall' as EnemyKind,x:0,y:0,hp:0,maxHp:0,vx:0,vy:0,timer:0,windup:0,flash:0,serial:0}));
 effects:Effect[]=[];shots:Shot[]=[]; cooldowns=[0,0,0,0];beam=0;beamTick=0;attack=0;spawnBank=0;alive=0;serial=0;
 grid=new Map<number,Enemy[]>(); freeBuckets:Enemy[][]=[];
 notice='THE HORDE IS YOURS.';noticeTime=4;shake=0;massacreNoticeAt=-10;lastCarnageTier=1;sound:(kind:string)=>void=()=>{};
 surrounded=0;passiveTimer=0;healBudget=250;beamKills=0;beamPower=ABILITIES.beam;ultimateTime=0;activationBest=0;
 frenzy=0;frenzyHealing=0;frenzyKills=0;frenzyGuard=0;shield=0;shieldTime=0;sustainCooldown=0;siphonBudget=SUSTAIN.overlord.perSecond;siphonWindow=0;pressure=threatAt(0);pressureTime=0;sustainStats={healed:0,absorbed:0};
 moving=false;movementAngle=0;facingX=1;momentum=0;momentumGrace=0;lungeCharges=1;lungeRecharge=0;dodgeInvuln=0;dodgeDeflected=false;resonance=0;targetPoint:{x:number;y:number}|null=null;servants=createServants();corruptionTick=0;chains:{x:number;y:number}[]=[];
 fields:{kind:string;x:number;y:number;life:number;radius:number;damage:number;tick:number;kills:number;nature?:string}[]=[];
 bolts:{x:number;y:number;vx:number;vy:number;life:number;damage:number;source:string}[]=[];
 targetView={x:640,y:360};scytheWaves:ScytheWave[]=[];reaperFocus=0;reaperStorm=0;soulGlow=0;reaperPulse=0;reaperSweeps=0;soulBudget=0;soulWindow=0;
 fissures:TitanFissure[]=[];clawWaves:ClawWave[]=[];court:CourtState|null=null;realm:TitanRealmState|null=null;relicOwners:string[]=[];
 debris:{x:number;y:number;vx:number;vy:number;life:number;kills:number;death?:DeathArt}[]=[];
 dash:{remaining:number;speed:number;damage:number;kills:number;angle:number;radius:number;source:string}|null=null;
 titanKit:TitanKit='throw';identity:Identity;monster=MONSTERS.sovereign;powers=MONSTERS.sovereign.abilities.map(id=>ABILITIES[id]);
 constructor(seed:number,identity:Partial<Identity>={},phase=EVENT.phase,titanKit:TitanKit='throw'){this.seed=seed>>>0;this.rng=this.seed||1;this.phase=Number.isInteger(phase)&&phase>=0&&phase<PHASES.length?phase:0;this.identity=createIdentity(identity);this.monster=MONSTERS[this.identity.monsterId];this.titanKit=titanKitForStage(this.phase,titanKit,true);this.powers=abilitiesForStage(this.monster.id,this.phase,this.titanKit);this.player.hp=this.player.maxHp=this.monster.hp;this.relicOwners=this.powers.map(()=>this.monster.id);if(this.phase===2){this.realm=createTitanRealm(()=>this.random());this.release=4;this.lungeCharges=this.maxLungeCharges();this.player.x=REALM_START.x;this.player.y=REALM_START.y;this.score.setAwardLimit((amount,objective)=>realmScoreCredit(this,amount,objective));}if(this.phase===1){this.court=createCourt();this.release=COURT.startRelease;this.lungeCharges=this.maxLungeCharges();this.score.setAwardLimit((amount,objective)=>courtScoreCredit(this,amount,objective));}}
 insideMap(x:number,y:number){return this.realm?insideRealm(x,y):this.court?insideCourt(x,y):Math.hypot(x,y)<=EVENT.arenaRadius;}
 get arenaRadius(){return this.realm?2500:this.court?COURT_RADIUS:EVENT.arenaRadius;}
 slideArena(body:{x:number;y:number},radius:number){if(this.realm)slideRealm(body,radius);else if(this.court)slideCourt(body,radius);else slideTorches(body,radius);}
 random(){let x=this.rng;x^=x<<13;x^=x>>>17;x^=x<<5;this.rng=x>>>0;return this.rng/4294967296;}
 notifications:string[]=[];
 announce(text:string){if(text.startsWith('RECORD')||text.startsWith('TITLE')){if(this.notifications.length>=10)this.notifications.pop();this.notifications.unshift(text);return;}if(this.noticeTime<=0){this.notice=text;this.noticeTime=2.8;}else if(this.notifications.length<10&&!this.notifications.includes(text))this.notifications.push(text);}
 effect(x:number,y:number,kind:string,radius:number,life=.5,angle=0,death?:DeathArt){if(this.effects.length<180)this.effects.push({x,y,kind,radius,life,max:life,angle,...(death?{death}:{})});}
 hasTrait(nature:string){return activeRealmNature(this,nature);}
 seedOpening(){if(this.realm){seedTitanRealm(this);return;}for(let i=0;i<OPENING.count;i++)this.spawn('thrall',true);this.rebuildGrid();}
 heal(amount:number,recovery=false){if(this.ended||amount<=0)return;const gained=Math.min(amount*(this.court&&!recovery?(this.monster.id==='devourer'?COURT.devourerHealScale:COURT.healScale):1),this.player.maxHp-this.player.hp);this.player.hp+=gained;this.sustainStats.healed+=gained;if(gained>0)this.sound('heal');}
 ward(amount:number,cap:number,seconds:number){this.shield=Math.min(cap*(this.court?COURT.shieldCapScale:1),this.shield+amount*(this.court?COURT.shieldScale:1));this.shieldTime=seconds*(1+.2*upgradeRank(this,'duration'));this.sound('shield');}
 spawn(kind:EnemyKind,opening=false){
  if(this.alive>=EVENT.maxEnemies-24&&kind!=='elite'&&kind!=='titan')return;
  const e=this.enemies.find(e=>!e.active);if(!e)return;
  const facing=this.time<60?0:this.time*.045;const a=facing+(this.random()-.5)*this.pressure.arc,r=opening?OPENING.distance+this.random()*OPENING.spread:this.pressure.distance+this.random()*160,def=ENEMIES[kind];
  const hpScale=this.court?1+this.court.stats.captains*.07:(1+Math.max(0,this.wave-4)*.045)*(1+Math.max(0,this.time-540)*.0015)*(kind==='elite'?1+this.release*.18:kind==='titan'?1+this.release*.3:1);
  Object.assign(e,{active:true,kind,x:this.player.x+Math.cos(a)*r,y:this.player.y+Math.sin(a)*r,hp:def.hp*hpScale,maxHp:def.hp*hpScale,vx:0,vy:0,timer:1+this.random()*2,windup:0,flash:0,serial:++this.serial,corruptUntil:0,fearedUntil:undefined,rushing:true,court:undefined,colossus:undefined,snaredUntil:undefined,realm:undefined});this.alive++;if(kind==='titan')this.sound('titanArrival');return e;
 }
 rebuildGrid(){
  for(const bucket of this.grid.values()){bucket.length=0;this.freeBuckets.push(bucket);}this.grid.clear();
  for(const e of this.enemies)if(e.active){const key=this.cell(e.x,e.y);let bucket=this.grid.get(key);if(!bucket){bucket=this.freeBuckets.pop()||[];this.grid.set(key,bucket);}bucket.push(e);}
 }
 cell(x:number,y:number){return (Math.floor(x/80)+4096)*8192+Math.floor(y/80)+4096;}
 nearby(x:number,y:number,r:number,visit:(e:Enemy)=>void){
  for(let ix=Math.floor((x-r)/80);ix<=Math.floor((x+r)/80);ix++)for(let iy=Math.floor((y-r)/80);iy<=Math.floor((y+r)/80);iy++){
   const bucket=this.grid.get((ix+4096)*8192+iy+4096);if(bucket)for(const e of bucket)if(e.active)visit(e);
  }
 }
 hurt(damage:number){if(this.moonFury>0||this.vault)return;if(this.court&&(this.court.pending||this.court.cleared))return;if(this.dodgeInvuln>0){if(!this.dodgeDeflected){this.dodgeInvuln=Math.max(this.dodgeInvuln,.32);this.dodgeDeflected=true;}return;}if(this.player.invuln>0)return;const raw=damage*this.monster.armor*(this.hasTrait('titan')&&this.surrounded>=3?.85:1)*(this.hasTrait('sovereign')&&this.player.rage>0?.75:1),s=SUSTAIN.devourer,guard=this.hasTrait('devourer')&&this.frenzyGuard>0?s.guardBaseReduction+s.guardReductionPerRelease*this.release:0,incoming=raw*(1-guard),blocked=Math.min(this.shield,incoming);this.shield-=blocked;this.sustainStats.absorbed+=raw-incoming+blocked;this.player.hp=Math.max(0,this.player.hp-incoming+blocked);this.player.invuln=.32;this.score.noHitKills=0;this.shake=7;this.sound('hurt');if(this.player.hp>0&&this.player.hp/this.player.maxHp<.25)this.sound('lowHealth');if(this.player.hp<=0){this.ended=true;this.fissures.length=0;if(this.court){dismissColossus(this,true);}this.sound('defeat');}}
 damage(e:Enemy,amount:number,source:string,origin?:{x:number;y:number}){
  if(!e.active||this.court?.cleared||e.colossus&&this.time>=e.colossus.expiresAt)return false;
  if(this.realm&&e.realm?.role==='boss'&&origin&&(!this.realm.engaged||!inTitanArena(origin.x,origin.y)))return false;if(source==='vortex'||source.endsWith(':vortex')){if(e.kind==='titan'||e.kind==='elite'||e.court?.role==='captain'||e.realm?.role==='guardian')amount=Math.min(amount,e.maxHp*.015);}const actual=this.realm?realmDamage(this,e,amount,source):e.colossus?colossusDamage(this,amount,source):e.court?courtDamage(this,e,amount,source,origin):amount;if(this.court&&this.monster.id==='devourer'&&source==='devour'&&e.court?.role==='captain'&&actual>0){const drain=Math.min(this.healBudget,Math.max(this.player.maxHp*COURT.devourMinimum,Math.max(0,Math.min(e.hp,actual))*COURT.devourDrain));this.healBudget-=drain;this.heal(drain);}if(this.realm&&['devour','relic:devourer:devour','relic:sovereign:devour'].includes(source)&&e.realm?.role==='boss'&&actual>0){const drain=Math.min(this.healBudget,Math.min(e.hp,actual)*.22);this.healBudget-=drain;this.heal(drain);}if(this.hasTrait('reaper')&&['scythe','reapersweep','graveshift','reapingarc','moonstorm'].includes(source))harvestLife(this,Math.max(0,Math.min(e.hp,actual)),this.realm&&source!=='scythe'?.12:undefined);if(e.court)courtFeatHit(this,e,actual);e.hp-=actual;if(actual>0)e.flash=.1;
  if(this.realm&&actual<=0)return false;if(this.realm&&e.realm?.role==='boss'&&this.frenzy>0&&actual>0){const heal=Math.min(this.frenzyHealing,Math.max(0,Math.min(e.hp+actual,actual))*.08,this.player.maxHp-this.player.hp);this.frenzyHealing-=heal;this.heal(heal);}if(e.hp>0)return false;
  e.active=false;this.alive--;this.score.kill(e.colossus?0:this.court?(e.court?.role==='captain'?600:e.kind==='elite'||e.kind==='titan'?ENEMIES[e.kind].score:Math.round(ENEMIES[e.kind].score*.7)):ENEMIES[e.kind].score,e.kind,this.time,source,e.court?.role==='captain');if(e.court)courtKill(this,e);if(e.colossus)finishColossus(this,e);if(this.realm)realmKill(this,e);this.sound(e.kind==='titan'?'titanDeath':e.kind==='elite'?'eliteDeath':e.kind==='brute'?'heavyDeath':'enemyDeath.'+e.kind);if(source==='collision')this.sound('collision');if(source==='devour')this.sound('devour');if(source==='chain')this.sound('corruption');if(source==='ultimate')this.sound('ultimateImpact');
  if(this.hasTrait('overlord')&&(source==='controlled'||source==='summoned')){const amount=Math.min(SUSTAIN.overlord.perKill,this.siphonBudget);this.siphonBudget-=amount;this.heal(amount);}
  const death:DeathArt={source,sprite:e.colossus?'ashen-colossus':e.court?'court-'+e.court.role:e.kind};
  this.effect(e.x,e.y,'blood',ENEMIES[e.kind].radius*2,.5,0,death);
  if(this.frenzy>0){const s=SUSTAIN.devourer;this.frenzyKills++;const heal=Math.min(s.frenzyHealBase+s.frenzyHealPerRelease*this.release,this.frenzyHealing,this.player.maxHp-this.player.hp);this.frenzyHealing-=heal;this.heal(heal);if(this.frenzyKills%s.guardKills===0){if(this.frenzyGuard<=0)this.announce('FEAST GUARD · KEEP FEEDING');this.frenzyGuard=Math.max(this.frenzyGuard,s.guardBaseSeconds+s.guardSecondsPerRelease*this.release);this.effect(this.player.x,this.player.y,'feast',90,.35);}}
  if((e.corruptUntil||0)>this.time&&this.chains.length<128)this.chains.push({x:e.x,y:e.y});
  if(Math.hypot(e.vx,e.vy)>100&&this.debris.length<80)this.debris.push({x:e.x,y:e.y,vx:e.vx,vy:e.vy,life:.6,kills:0,death});
  if(source==='devour'){const heal=Math.min(this.healBudget,e.kind==='elite'?120:18);this.healBudget-=heal;this.heal(heal);}
  return true;
 }
 resolveFeats(extra:Parameters<Score['evaluate']>[1]){if(this.court||this.realm)return;const earned=this.score.evaluate(this.time,extra);if(earned.length){this.announce(earned[0]+(earned.length>1?' · +'+(earned.length-1)+' feats':''));this.sound('feat');}}
 completeAttack(kills:number,extra:Parameters<Score['evaluate']>[1]={},source=''){if(this.hasTrait('sovereign')&&kills>0&&(source==='devour'||source==='beam'||source==='ultimate')){const s=SUSTAIN.sovereign,magic=source!=='devour',amount=magic?Math.min(kills*(s.magicPerKill+s.magicPerRelease*this.release),s.magicCastCap+s.magicCapPerRelease*this.release):kills*(s.wardPerKill+s.wardPerRelease*this.release);this.ward(amount,s.wardCap+s.wardCapPerRelease*this.release,s.wardSeconds);}if(this.sustainCooldown<=0){if(this.hasTrait('titan')&&kills>=SUSTAIN.titan.kills){const s=SUSTAIN.titan;this.heal(s.heal);this.ward(s.shield*(.5+.5*this.momentum),s.cap,s.seconds);this.sustainCooldown=s.cooldown;}if(this.hasTrait('calamity')&&kills>=SUSTAIN.calamity.kills){const s=SUSTAIN.calamity;this.ward(s.shield,s.cap,s.seconds);this.sustainCooldown=s.cooldown;}}if(this.hasTrait('calamity')&&kills>=20&&this.resonance<=0){this.resonance=1;this.score.carnage=Math.min(5,this.score.carnage+.15);this.score.peak=Math.max(this.score.peak,this.score.carnage);this.cooldowns=this.cooldowns.map(n=>Math.max(0,n-.75));}this.score.multikill(kills);this.activationBest=Math.max(this.activationBest,kills);this.resolveFeats({multi:kills,...extra});const tier=DESCENDING_MASSACRES.find(t=>kills>=t.kills);if(tier){this.sound(kills>=100?'multikill.extinction':kills>=60?'multikill.annihilation':kills>=30?'multikill.bloodbath':'multikill');if(this.time-this.massacreNoticeAt>=2.8){this.massacreNoticeAt=this.time;const message=tier.name+' · '+kills+' SLAIN';const queued=this.notifications.findIndex(n=>/^(MASSACRE|BLOODBATH|ANNIHILATION|EXTINCTION EVENT)/.test(n));if(queued>=0)this.notifications[queued]=message;else this.announce(message);}}}
 area(x:number,y:number,radius:number,damage:number,source:string,knockback=0,settle=true){let kills=0,overkill=0,apex=0;this.nearby(x,y,radius+65,e=>{const dx=e.x-x,dy=e.y-y,d=Math.hypot(dx,dy);if(d>radius+ENEMIES[e.kind].radius)return;if(damage*this.powerScale()>e.hp*4)overkill++;if(knockback){const resistance=e.kind==='titan'?.15:e.kind==='elite'?.4:e.court?.role==='captain'?.2:1;e.vx=dx/(d||1)*knockback*this.releaseStats.knockback*resistance;e.vy=dy/(d||1)*knockback*this.releaseStats.knockback*resistance;}if(this.damage(e,damage*this.powerScale(),source,{x,y})){kills++;if(e.kind==='elite'&&source==='devour')apex++;}});if(settle)this.completeAttack(kills,{overkill,eliteDevoured:apex},source);return kills;}
 setMovementDirection(x:number,y:number){if(Number.isFinite(x)&&Number.isFinite(y)&&(x!==0||y!==0)){this.movementAngle=Math.atan2(y,x);if(x<-.05)this.facingX=-1;else if(x>.05)this.facingX=1;}}
 maxLungeCharges(){return this.realm?(this.powers.some(p=>p.effect==='lunge')?3:1):this.monster.id==='devourer'?1+(this.release>=2?1:0)+(this.release>=4?1:0):1;}
 cast(index:number,point?:{x:number;y:number}){if(this.realm)return castRealmPower(this,index,point);if(this.ended||this.court?.pending||this.cooldowns[index]>0&&!(this.monster.id==='devourer'&&index===0&&this.lungeCharges>0))return false;const base=this.powers[index];if(!base)return false;const power=releasedPower(base,this.monster.id,this.release);if(this.court){power.radius*=1+.12*upgradeRank(this,'reach');power.cooldown*=Math.pow(.9,upgradeRank(this,'recharge'));if(power.duration&&!['lunge','charge','meteor'].includes(power.effect))power.duration*=1+.2*upgradeRank(this,'duration');}const handler=power&&POWER_HANDLERS[power.effect];if(!handler)return false;if(power.effect==='parkour'&&!parkourLanding(this,point))return false;if(point){if(!Number.isFinite(point.x)||!Number.isFinite(point.y))return false;if(power.effect==='parkour'){if(Math.abs(point.x-this.player.x)>this.targetView.x||Math.abs(point.y-this.player.y)>this.targetView.y)return false;}else if(this.monster.id==='reaper'&&['reaperblink','reapervolley'].includes(power.effect)){if(Math.abs(point.x-this.player.x)>this.targetView.x||Math.abs(point.y-this.player.y)>this.targetView.y)return false;if(power.effect==='reaperblink'&&!reaperTappedEnemy(this,point))return false;}else if(this.monster.id!=='calamity'||!['meteor','vortex'].includes(power.effect)||Math.hypot(point.x-this.player.x,point.y-this.player.y)>750||!this.insideMap(point.x,point.y))return false;}if(this.monster.id==='devourer'&&index===0){if(this.lungeCharges<=0)return false;this.lungeCharges--;if(this.lungeRecharge<=0)this.lungeRecharge=power.cooldown;this.cooldowns[index]=this.lungeCharges>0?0:this.lungeRecharge;}else this.cooldowns[index]=power.cooldown;this.sound('ability.'+power.id);if(index===3)this.sound('ultimateStart');this.shake=index===3?18:8;if(this.monster.id!=='lycanthrope'&&(this.monster.id!=='reaper'||index===3)&&power.effect!=='fissure')this.effect(this.player.x,this.player.y,this.monster.id==='lycanthrope'?'lycanthrope-'+(power.effect==='wolffury'?'fury':power.effect==='wolfhowl'?'howl':'claw'):this.monster.id==='reaper'?'reaper-eclipse':power.effect==='shockwave'?'rupture':power.effect,this.monster.id==='reaper'?190:power.radius,index===3?1:.5);if(index===3)this.ultimateTime=.85;this.targetPoint=point||null;handler(this,power);this.targetPoint=null;return true;}
 nearestEnemy(range:number){const p=this.player;let best:Enemy|null=null,bestDistance=range*range;this.nearby(p.x,p.y,range,e=>{if(this.realm&&e.realm?.role==='boss'&&!this.realm.engaged)return;const dx=e.x-p.x,dy=e.y-p.y,distance=dx*dx+dy*dy;if(this.realm&&distance>range*range)return;const ranked=this.realm&&e.realm?.role==='boss'?distance*.01:distance;if(ranked<bestDistance){best=e;bestDistance=ranked;}});return best;}
 findBasicTarget(range:number,ranged:boolean){if(ranged)return this.nearestEnemy(range);const p=this.player;let best:Enemy|null=null,bestScore=Infinity;this.nearby(p.x,p.y,range+65,e=>{if(this.realm&&e.realm?.role==='boss'&&!this.realm.engaged)return;const distance=Math.hypot(e.x-p.x,e.y-p.y);if(distance>range+ENEMIES[e.kind].radius)return;const score=distance-(e.windup>0?30:0)-(['elite','titan'].includes(e.kind)?Math.min(35,distance*.1):0);if(score<bestScore){best=e;bestScore=score;}});return best;}
 powerScale(){return this.releaseStats.damage*(this.player.rage>0?1.4:1)*(this.frenzy>0?1.5:1)*(this.hasTrait('devourer')?1+Math.min(.25,this.score.recent.length*.005):1);}
 update(dt:number,input:Input){
  if(this.ended)return;if(this.court?.pending){checkColossusArrival(this);return;}
  this.time+=dt;this.releaseTime=Math.max(0,this.releaseTime-dt);const release=this.realm?4:this.court?courtRelease(this):releaseAt(this.time);if(release!==this.release){const oldMax=this.maxLungeCharges();this.release=release;this.lungeCharges=Math.min(this.maxLungeCharges(),this.lungeCharges+this.maxLungeCharges()-oldMax);this.releaseTime=2.8;this.sound('ultimateStart');this.shake=12;this.effect(this.player.x,this.player.y,'release',320,1);}this.sustainCooldown=Math.max(0,this.sustainCooldown-dt);this.shieldTime-=dt;if(this.shieldTime<=0)this.shield=0;this.siphonWindow+=dt;if(this.siphonWindow>=1){this.siphonWindow-=1;this.siphonBudget=SUSTAIN.overlord.perSecond;}this.pressureTime-=dt;if(this.pressureTime<=0){this.pressureTime=.5;this.pressure=threatAt(this.court?60+this.court.stats.captains*35:this.time);}this.score.update(dt,this.time);const tier=Math.floor(this.score.carnage);if(tier>this.lastCarnageTier)this.sound('carnage');this.lastCarnageTier=tier;this.noticeTime-=dt;if(this.noticeTime<=0&&this.notifications.length){this.notice=this.notifications.shift()!;this.noticeTime=2.8;}this.shake=Math.max(0,this.shake-dt*25);
  this.resonance=Math.max(0,this.resonance-dt);this.frenzy=Math.max(0,this.frenzy-dt);this.frenzyGuard=Math.max(0,this.frenzyGuard-dt);this.dodgeInvuln=Math.max(0,this.dodgeInvuln-dt);this.ultimateTime=Math.max(0,this.ultimateTime-dt);const p=this.player;p.invuln=Math.max(0,p.invuln-dt);p.rage=Math.max(0,p.rage-dt);
  for(let i=0;i<4;i++)this.cooldowns[i]=Math.max(0,this.cooldowns[i]-dt);if(this.realm){const slot=this.powers.findIndex(p=>p.effect==='lunge');if(slot>=0){if(this.lungeCharges<3){this.lungeRecharge-=dt;if(this.lungeRecharge<=0){this.lungeCharges++;this.lungeRecharge=this.lungeCharges<3?releasedPower(this.powers[slot],this.relicOwners[slot],4).cooldown:0;}}this.cooldowns[slot]=this.lungeCharges>0?0:this.lungeRecharge;}}if(!this.realm&&this.monster.id==='devourer'){if(this.lungeCharges<this.maxLungeCharges()){this.lungeRecharge-=dt;if(this.lungeRecharge<=0){this.lungeCharges++;this.lungeRecharge=this.lungeCharges<this.maxLungeCharges()?this.powers[0].cooldown*this.releaseStats.cooldown:0;}}this.cooldowns[0]=this.lungeCharges>0?0:this.lungeRecharge;}
  updateRelicPowers(this,dt);const specialMotion=!!this.vault||this.moonFury>0;updateLycanthrope(this,dt);if(!specialMotion)this.setMovementDirection(input.x,input.y);const startX=p.x,startY=p.y;this.moving=!!(input.x||input.y||this.dash);const length=Math.hypot(input.x,input.y)||1;if(!specialMotion){p.x+=input.x/Math.max(1,length)*this.monster.speed*this.releaseStats.move*(this.hasTrait('devourer')?1+Math.min(.15,this.score.recent.length*.003):1)*dt;p.y+=input.y/Math.max(1,length)*this.monster.speed*this.releaseStats.move*(this.hasTrait('devourer')?1+Math.min(.15,this.score.recent.length*.003):1)*dt;
  if(this.dash){const d=this.dash;p.x+=Math.cos(d.angle)*d.speed*dt;p.y+=Math.sin(d.angle)*d.speed*dt;d.remaining-=dt;}
  }const intendedX=p.x,intendedY=p.y;if(!specialMotion){if(this.realm)moveRealm(p,{x:startX,y:startY},23);else this.slideArena(p,23);}
  if(this.court&&this.dash){const blocked=(intendedX-p.x)*Math.cos(this.dash.angle)+(intendedY-p.y)*Math.sin(this.dash.angle);if(blocked>1)this.dash.remaining=0;}
  const fromCenter=Math.hypot(p.x,p.y);if(!this.court&&!this.realm&&fromCenter>this.arenaRadius){p.x*=this.arenaRadius/fromCenter;p.y*=this.arenaRadius/fromCenter;}
  if(this.hasTrait('titan')){const s=SUSTAIN.titan,distance=Math.hypot(p.x-startX,p.y-startY);if(distance>=.7){this.momentum=Math.min(1,this.momentum+distance/s.momentumDistance);this.momentumGrace=s.momentumGrace;if(this.momentum>.1){this.shield=Math.min(s.cap*(this.court?COURT.shieldCapScale:1),this.shield+s.movingRegen*this.momentum*dt*(this.court?COURT.shieldScale:1));this.shieldTime=Math.max(this.shieldTime,2.5*(1+.2*upgradeRank(this,'duration')));}}else{this.momentumGrace=Math.max(0,this.momentumGrace-dt);if(this.momentumGrace===0){this.momentum=Math.max(0,this.momentum-dt/s.momentumDecay);this.shield=Math.max(0,this.shield-s.idleDrain*(1-this.momentum)*dt);}}}
  if(input.aiming)p.angle=Math.atan2(input.aimY-p.y,input.aimX-p.x);
  else if(length>.1&&(input.x||input.y))p.angle=Math.atan2(input.y,input.x);
  else {let nearest:Enemy|null=null,best=500;for(const e of this.enemies)if(e.active){const d=Math.hypot(e.x-p.x,e.y-p.y);if(d<best){nearest=e;best=d;}}if(nearest)p.angle=Math.atan2(nearest.y-p.y,nearest.x-p.x);}
  const nextWave=Math.floor(this.time/EVENT.waveSeconds)+1,phase=PHASES[this.phase];
  if(nextWave!==this.wave){this.wave=nextWave;if(this.wave>1&&!this.realm){this.score.award(this.wave*SCORING.waveBonus);if(!this.court){this.announce(`WAVE ${this.wave} · THE HORDE GROWS`);this.sound('wave');}}if(!this.court&&!this.realm&&this.time>=INTRODUCTIONS.elite&&this.wave%phase.eliteEvery===0)this.spawn('elite');if(!this.court&&!this.realm&&this.time>=INTRODUCTIONS.titan&&this.wave%phase.titanEvery===0)this.spawn('titan');}
  this.spawnBank+=dt*(this.realm?0:this.pressure.rate)*phase.pressure*(this.court?COURT.spawnRate:1);
  const kinds:EnemyKind[]=['thrall','hound','spitter','wing','brute'];const heavy=Math.min(12,Math.max(0,this.time-420)*.04),weights=phase.weights.map((v,i)=>v+(i===0?-heavy:i===4?heavy:0));
  while(this.spawnBank>=1){this.spawnBank--;let roll=this.random()*100,index=0;while(index<4&&roll>=weights[index]){roll-=weights[index];index++;}if(this.alive<this.pressure.cap*(this.court?COURT.crowdCap:1))this.spawn(this.time>=INTRODUCTIONS[kinds[index]]?kinds[index]:'thrall');}
  if(this.court)updateCourt(this,dt);if(this.realm)updateTitanRealm(this,dt);
  const threat=this.court?1+this.court.stats.captains*.04:1+Math.max(0,this.wave-12)*.10+Math.max(0,this.time-540)*.004+Math.max(0,this.time-660)*.025;
  for(const e of this.enemies){if(!e.active)continue;const def=ENEMIES[e.kind];let dx=p.x-e.x,dy=p.y-e.y,d=Math.hypot(dx,dy)||1;e.timer-=dt;e.flash=Math.max(0,e.flash-dt);if((e.fearedUntil||0)>this.time){const from={x:e.x,y:e.y};e.x-=dx/d*125*dt;e.y-=dy/d*125*dt;e.windup=0;if(this.realm)moveRealm(e,from,24);else this.slideArena(e,def.radius);continue;}if(e.realm){realmEnemyMotion(this,e,dt);continue;}
   // Escaped ordinary foes leave without kill credit. Bosses persist in place;
   // never teleport a pursuer closer and undo the player's earned separation.
   if(d>1150&&e.kind!=='elite'&&e.kind!=='titan'&&!e.court){e.active=false;this.alive--;continue;}
   if(d>430)e.rushing=true;if(d<140)e.rushing=false;
   let speed=enemyMovementSpeed(e.kind,this.court?3+this.court.stats.captains*2:this.wave,this.pressure.pursuit,!!e.rushing);
   if(def.behavior==='ranged'&&d<380){speed=d<250?-def.speed:0;if(e.timer<=0&&this.shots.length<180){this.shots.push({x:e.x,y:e.y,vx:dx/d*220,vy:dy/d*220,life:4,damage:def.damage*threat});e.timer=2.5;}}
   if(!e.colossus&&(def.behavior==='slam'||e.court?.role==='captain')&&d<220&&e.timer<=0&&e.windup<=0){if(e.court)courtSlamStart(this,e,d<COURT.slamRadius+20);e.windup=e.court?.role==='captain'?COURT.slamWarning:1.2;e.timer=e.court?.role==='captain'?COURT.slamCycle:e.kind==='titan'?4:5;}
   if(e.windup>0){speed=0;e.windup-=dt;if(e.windup<=0){const r=e.court?.role==='captain'?COURT.slamRadius:e.kind==='titan'?240:140;this.effect(e.x,e.y,e.court?.role==='captain'?'court-slam':e.kind==='titan'?'slam-titan':'slam-elite',r,.45);if(e.court)courtSlamEnd(this,e,d<r+20);if(d<r+20)this.hurt(e.court?.role==='captain'?COURT.slamDamage*(1+.07*(e.court.tier||0)):def.damage*threat);}}
   const weave=def.behavior==='weave'?Math.sin(this.time*5+e.serial)*45:0;
   const courtMotion=e.colossus?colossusMotion(this,e):e.court?courtEnemyMotion(this,e,dt):this.court?(()=>{const v=courtSteer(e.x,e.y,p.x,p.y);return {dx:v.x,dy:v.y,speed};})():null;
   if(this.fissures.length){const factor=fissureMotion(this,e);if(courtMotion)courtMotion.speed*=factor;else speed*=factor;}if(courtMotion&&e.windup>0)courtMotion.speed=0;
   e.x+=((courtMotion?courtMotion.dx*courtMotion.speed:dx/d*speed)-dy/d*weave+e.vx)*dt;e.y+=((courtMotion?courtMotion.dy*courtMotion.speed:dy/d*speed)+dx/d*weave+e.vy)*dt;
   this.slideArena(e,def.radius);
   e.vx*=Math.exp(-dt*4);e.vy*=Math.exp(-dt*4);
   if(d<def.radius+23){this.hurt(def.damage*courtContactScale(e)*threat*(e.kind==='titan'?.4:e.kind==='elite'?.6:1));e.x-=dx/d*12;e.y-=dy/d*12;this.slideArena(e,def.radius);}
  }
  this.rebuildGrid();
  if(this.fissures.length)updateFissures(this,dt);
  updateServants(this,dt);
  this.passiveTimer-=dt;if(this.passiveTimer<=0){this.passiveTimer=.2;this.surrounded=0;this.nearby(p.x,p.y,130,e=>{if(Math.hypot(e.x-p.x,e.y-p.y)<130)this.surrounded++;});}
  if(this.dash){const d=this.dash;this.nearby(p.x,p.y,d.radius+60,e=>{if(Math.hypot(e.x-p.x,e.y-p.y)<d.radius+ENEMIES[e.kind].radius&&this.damage(e,d.damage*this.powerScale()*dt*12,d.source))d.kills++;});if(d.remaining<=0){this.completeAttack(d.kills);this.dash=null;}}
  for(let i=this.debris.length-1;i>=0;i--){const b=this.debris[i];b.life-=dt;b.x+=b.vx*dt;b.y+=b.vy*dt;this.nearby(b.x,b.y,35,e=>{if(Math.hypot(e.x-b.x,e.y-b.y)<ENEMIES[e.kind].radius+18&&this.damage(e,100*this.powerScale(),'collision'))b.kills++;});if(b.life<=0){this.resolveFeats({chain:b.kills});this.debris.splice(i,1);}}
  for(const e of this.enemies)if(e.active&&Math.hypot(e.vx,e.vy)>180){let chain=0;this.nearby(e.x,e.y,40,other=>{if(other!==e&&other.active&&Math.hypot(e.x-other.x,e.y-other.y)<ENEMIES[e.kind].radius+ENEMIES[other.kind].radius&&this.damage(other,80*this.powerScale(),'collision'))chain++;});if(chain){this.score.multikill(chain);this.resolveFeats({chain});}}
  for(let i=this.fields.length-1;i>=0;i--){const f=this.fields[i];f.life-=dt;f.tick-=dt;if(f.kind==='vortex'){this.nearby(f.x,f.y,f.radius+60,e=>{const dx=f.x-e.x,dy=f.y-e.y,d=Math.hypot(dx,dy);if(d<f.radius&&d>8&&e.kind!=='titan'&&e.kind!=='elite'&&e.court?.role!=='captain'&&e.realm?.role!=='guardian'){e.vx=dx/d*140;e.vy=dy/d*140;}});if(f.tick<=0){f.tick=.25;f.kills+=this.area(f.x,f.y,f.radius,f.damage,f.nature?'relic:'+f.nature+':vortex':'vortex',0,false);}}if(f.life<=0){if(f.kind==='meteor'){f.kills+=this.area(f.x,f.y,f.radius,f.damage,f.nature?'relic:'+f.nature+':meteor':'meteor',0,false);this.effect(f.x,f.y,'catastrophe',f.radius,.8);this.sound('meteorImpact');}this.completeAttack(f.kills);this.fields.splice(i,1);}}
  for(let i=this.bolts.length-1;i>=0;i--){const b=this.bolts[i];b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;let hit=false;this.nearby(b.x,b.y,65,e=>{if(!hit&&Math.hypot(e.x-b.x,e.y-b.y)<ENEMIES[e.kind].radius+10*this.releaseStats.radius){this.damage(e,b.damage,b.source,{x:b.x-b.vx*.03,y:b.y-b.vy*.03});hit=true;}});if(hit||b.life<=0)this.bolts.splice(i,1);}
  // Piercing claw waves sweep the travelled segment, including at low frame rates.
  for(let i=this.clawWaves.length-1;i>=0;i--){const w=this.clawWaves[i],step=Math.min(w.remaining,CLAW_WAVE.speed*dt),ax=Math.cos(w.angle),ay=Math.sin(w.angle),startX=w.x,startY=w.y;
   this.nearby(startX+ax*step/2,startY+ay*step/2,w.width+step/2+65,e=>{if(w.hit.has(e.serial))return;const dx=e.x-startX,dy=e.y-startY,along=Math.max(0,Math.min(step,dx*ax+dy*ay)),rx=dx-ax*along,ry=dy-ay*along,r=w.width+ENEMIES[e.kind].radius;if(rx*rx+ry*ry<r*r){w.hit.add(e.serial);if(this.damage(e,w.damage,'clawwave',{x:startX-ax*100,y:startY-ay*100}))w.kills++;}});
   w.x+=ax*step;w.y+=ay*step;w.remaining-=step;if(w.remaining<=0){this.completeAttack(w.kills,{},'clawwave');this.clawWaves.splice(i,1);}
  }
  if(this.monster.id==='reaper'||this.realm&&this.scytheWaves.length||this.realm&&this.reaperStorm>0)updateReaper(this,dt);
  this.attack-=dt;
  if(this.attack<=0){const basic={...this.monster.basic,radius:this.monster.basic.radius*this.releaseStats.radius},waveActive=this.monster.id==='devourer'&&this.release>=CLAW_WAVE.unlock&&this.frenzy>0,target=this.monster.id==='reaper'?reaperTarget(this,basic.radius,true):this.findBasicTarget(basic.radius,basic.ranged);if(target||(this.court&&waveActive)){this.sound('basic.'+this.monster.id);this.attack=basic.interval*this.releaseStats.attack*(this.frenzy>0?.5:1)/(this.court?1+.18*upgradeRank(this,'tempo'):1);let kills=0;if(basic.ranged){p.angle=Math.atan2(target.y-p.y,target.x-p.x);if(this.monster.id==='reaper')scytheWave(this,p.angle,basic.radius,28*this.releaseStats.radius,basic.damage,'scythe',target);else if(this.bolts.length<80)this.bolts.push({x:p.x,y:p.y,vx:Math.cos(p.angle)*800,vy:Math.sin(p.angle)*800,life:basic.radius/800,damage:basic.damage*this.powerScale(),source:this.realm&&this.frenzy>0?'relic:devourer:direct':'direct'});}else this.nearby(p.x,p.y,basic.radius+65,e=>{if(Math.hypot(e.x-p.x,e.y-p.y)<basic.radius+ENEMIES[e.kind].radius&&this.damage(e,basic.damage*this.powerScale(),'direct'))kills++;});if(waveActive&&this.clawWaves.length<CLAW_WAVE.maxActive)this.clawWaves.push({x:p.x,y:p.y,angle:this.movementAngle,remaining:CLAW_WAVE.range+CLAW_WAVE.rangePerRelease*this.release,width:CLAW_WAVE.halfWidth+CLAW_WAVE.widthPerRelease*this.release,damage:basic.damage*this.powerScale()*CLAW_WAVE.damage,kills:0,hit:new Set()});if(!basic.ranged)this.effect(p.x,p.y,this.monster.id==='lycanthrope'?'lycanthrope-claw':'claw',basic.radius+15,.22,waveActive?this.movementAngle:p.angle);if(kills){this.completeAttack(kills);if(this.frenzy>0)this.sound('ultimateImpact');}}else this.attack=0;}
  if(this.beam>0){if(this.realm||this.monster.id==='calamity'||this.monster.id==='sovereign'){const target=this.nearestEnemy(this.beamPower.radius);if(target)p.angle=Math.atan2(target.y-p.y,target.x-p.x);}this.beam-=dt;this.beamTick-=dt;if(this.beamTick<=0){this.beamTick=.08;let kills=0;const ax=Math.cos(p.angle),ay=Math.sin(p.angle);this.nearby(p.x,p.y,this.beamPower.radius+65,e=>{const dx=e.x-p.x,dy=e.y-p.y,along=dx*ax+dy*ay,side=Math.abs(dx*ay-dy*ax);if(along>0&&along<this.beamPower.radius&&side<(this.monster.id==='calamity'?11:13)*this.releaseStats.beam+ENEMIES[e.kind].radius&&this.damage(e,this.beamPower.damage*this.powerScale(),'beam'))kills++;});this.beamKills+=kills;}if(this.beam<=0)this.completeAttack(this.beamKills,{},'beam');}
  for(let i=this.shots.length-1;i>=0;i--){const s=this.shots[i];s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;if(Math.hypot(s.x-p.x,s.y-p.y)<28){this.hurt(s.damage);s.life=0;}if(s.life<=0)this.shots.splice(i,1);}
  for(let i=this.effects.length-1;i>=0;i--){this.effects[i].life-=dt;if(this.effects[i].life<=0)this.effects.splice(i,1);}
  this.resolveFeats({});
 }
}
