import {REALM_FEATS} from './realm-feats.ts';
import {FIFTH_POWERS} from './relic-powers.ts';
import {parkourLanding} from './lycanthrope.ts';
import {fissureMotion} from './titan-fissure.ts';
import {ABILITIES,MONSTERS,abilitiesForStage,type AbilityDef} from './content-monsters.ts';
import {reaperTappedEnemy} from './reaper.ts';
import {releasedPower} from './unbound.ts';
import {POWER_HANDLERS} from './powers.ts';
import {REALM_GROTTOS,REALM_START,REALM_RING,inTitanArena,realmSteer,slideRealm} from './titan-realm-map.ts';
import type {Game,Enemy} from './simulation.ts';
export const LYCANTHROPE_RULES='2026.10-v35-lycanthrope';
export const SWARM_TEST_RULES='2026.10-v34-swarm-test';
export const TITAN_REALM_RULES='2026.10-v35-titan-realm',TITAN_REALM_TEST_RULES='2026.10-v35-titan-test';
export const TITAN_REALM={hp:125000,combatPool:200000,guardianReward:700000,layerReward:600000,clearReward:3200000,resetDelay:3,maxCrowd:64};
export const LEGACY_RELIC_POOLS:Record<string,string[]>={overlord:['command','legion','throne','curse'],calamity:['oblivion','meteor','vortex','crimson'],devourer:['maw','execution','frenzy','rendlunge'],titan:['worldbreaker','stampede','faultline','heavenfall'],sovereign:['devour','beam','catastrophe','rupture'],reaper:['soulsweep','graveshift','reapingarc','moonstorm']};
export const RELIC_POOLS=Object.fromEntries(Object.entries(FIFTH_POWERS).map(([nature,id])=>[nature,[id]]));
export type RealmUnit={role:'boss'|'guardian'|'attendant';shrine?:number;homeX:number;homeY:number;variant:number;hintNature?:string;marked?:boolean;exposedUntil?:number};
export type Relic={id:string;nature:string;ability:string;known:boolean;shrine:number};
export type TitanRealmState={relics:Relic[];shrines:{id:number;cleared:boolean;claimed:boolean;decor:string;spawned:boolean}[];pattern:string[];boss:Enemy|null;layer:number;open:boolean;engaged:boolean;away:number;attempts:number;resets:number;breaches:number;rewardedLayers:number;guardians:number;combat:number;objective:number;cleared:boolean;interaction:number|null;wrongAt:number;spawnTimer:number;zones:{x:number;y:number;radius:number;warning:number;life:number;damage:number;hit:boolean}[];appearance:{head:number;mantle:number;body:string;power:string};beamNature:string;castNature:string;castAbility:string;firstWrong:number;brokenNatures:string[];stormPower:AbilityDef|null;cutinPower:AbilityDef|null;};
const shuffle=<T>(items:T[],random:()=>number)=>{const out=[...items];for(let i=out.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out;};
export function viableRelicSolution(relics:Relic[],pattern:string[]){return new Set(pattern).size===4&&pattern.every(n=>relics.some(r=>r.nature===n&&r.ability===FIFTH_POWERS[n]));}
export function createTitanRealm(random:()=>number):TitanRealmState{
 const natures=Object.keys(RELIC_POOLS),positions=shuffle([0,1,2,3,4,5,6],random);
 const relics=natures.map((nature,i)=>({id:'relic-'+nature,nature,ability:FIFTH_POWERS[nature],known:false,shrine:positions[i]}));
 const colors=['#b86889','#60aba5','#a38ad2','#bf9b68','#7299c0','#8ca879'];
 return {relics,shrines:REALM_GROTTOS.map(s=>({id:s.id,cleared:false,claimed:false,decor:'unknown',spawned:false})),pattern:shuffle(natures,random).slice(0,4),boss:null,layer:0,open:false,engaged:false,away:0,attempts:0,resets:0,breaches:0,rewardedLayers:0,guardians:0,combat:0,objective:0,cleared:false,interaction:null,wrongAt:-10,firstWrong:0,brokenNatures:[],spawnTimer:2,zones:[],appearance:{head:Math.floor(random()*3),mantle:Math.floor(random()*2),body:colors[Math.floor(random()*colors.length)],power:colors[Math.floor(random()*colors.length)]},beamNature:'',castNature:'',castAbility:'',stormPower:null,cutinPower:null};
}
export function awardRealmFeat(g:Game,id:keyof typeof REALM_FEATS){const feat=REALM_FEATS[id],count=g.score.feats[id]||0;if(count>=feat.max)return;g.score.feats[id]=count+1;g.score.award(feat.bonus,true);g.announce('RUN FEAT · '+feat.name.toUpperCase());g.sound('feat');}
function nativeGuardianHit(g:Game,source:string){
 const s=g.realm!,id=g.monster.id,native=abilitiesForStage(id,g.phase,g.titanKit).map(p=>p.id);
 if(s.castAbility)return s.castNature===id&&native.includes(s.castAbility);
 if(source.startsWith('relic:')){const [,owner,ability]=source.split(':');return owner===id&&native.includes(ability);}
 if(id==='overlord'&&['controlled','summoned','dot','chain','curse'].includes(source))return g.powers.some(p=>native.includes(p.id));
 if(id==='reaper'&&['reapersweep','graveshift','reapingarc','moonstorm'].includes(source))return g.powers.some(p=>native.includes(p.id));
 if(id==='devourer'&&['clawwave','execute','lunge'].includes(source))return g.powers.some(p=>native.includes(p.id));
 if(id==='devourer'&&source==='direct'&&g.frenzy>0)return g.powers.some(p=>p.id==='frenzy');
 if(id==='titan'&&['fissure','fissure-impact'].includes(source))return g.powers.some(p=>p.id==='faultline');
 if(id==='titan'&&['trample','shockwave','launch'].includes(source))return g.powers.some(p=>native.includes(p.id));
 return source==='beam'&&s.beamNature===id&&g.powers.some(p=>p.effect==='beam'&&native.includes(p.id));
}
export function powerNature(g:Game,index:number){return g.realm?g.relicOwners[index]||g.monster.id:g.monster.id;}
export function activeRealmNature(g:Game,nature:string){return g.realm?g.relicOwners.includes(nature):g.monster.id===nature;}
export function sourceNature(g:Game,source:string){if(!g.realm)return g.monster.id;if(g.realm.castNature)return g.realm.castNature;if(source.startsWith('relic:'))return source.split(':')[1];if(['controlled','summoned','dot','chain','curse'].includes(source))return 'overlord';if(['scythe','reapersweep','graveshift','reapingarc','moonstorm'].includes(source))return 'reaper';if(['fissure','fissure-impact','collision'].includes(source))return 'titan';if(['clawwave','execute','lunge'].includes(source)||source==='direct'&&g.frenzy>0)return 'devourer';if(['launch','shockwave','trample'].includes(source))return 'titan';if(source==='beam')return g.realm.beamNature;return '';}
export function realmScoreCredit(g:Game,amount:number,objective:boolean){const s=g.realm!;if(objective){s.objective+=amount;return amount;}const credit=Math.max(0,Math.min(amount,TITAN_REALM.combatPool-s.combat));s.combat+=credit;return credit;}
export function seedTitanRealm(g:Game){const s=g.realm!;if(s.boss)return;g.player.x=REALM_START.x;g.player.y=REALM_START.y;const boss=g.spawn('titan');if(!boss)throw Error('Titan encounter could not start');Object.assign(boss,{x:0,y:0,hp:TITAN_REALM.hp,maxHp:TITAN_REALM.hp,timer:2.5,realm:{role:'boss',homeX:0,homeY:0,variant:0}});s.boss=boss;g.rebuildGrid();g.notice='Explore the grottos. Claim relics. Break the titan’s four defenses.';}
export function realmDamage(g:Game,e:Enemy,amount:number,source:string){const s=g.realm!;if(s.cleared)return 0;if(e.realm?.role!=='boss'){if(e.realm?.role==='guardian'){if(nativeGuardianHit(g,source)){if((e.realm.exposedUntil||0)<g.time)g.effect(e.x,e.y,'realm-breach',110,.55);e.realm.exposedUntil=g.time+5;}if((e.realm.exposedUntil||0)<=g.time)return Math.min(amount*.12,Math.max(0,e.hp-e.maxHp*.1));}if(e.realm?.hintNature&&sourceNature(g,source)===e.realm.hintNature){e.realm.marked=true;g.effect(e.x,e.y,'realm-breach',85,.35);}return amount;}
 if(!s.engaged||!inTitanArena(g.player.x,g.player.y))return 0;
 if(!s.open){if((s.castAbility||source.split(':')[2])!==FIFTH_POWERS[s.pattern[s.layer]]){if(Object.values(FIFTH_POWERS).includes(s.castAbility||source.split(':')[2]))s.firstWrong|=1<<s.layer;if(g.time-s.wrongAt>1.5){s.wrongAt=g.time;g.effect(e.x,e.y,'realm-block',230,.35);g.sound('shield');g.announce('The defense absorbs your power.');}return 0;}s.open=true;s.breaches++;if(!(s.firstWrong&(1<<s.layer)))awardRealmFeat(g,'insight');if(!s.brokenNatures.includes(s.pattern[s.layer])){s.brokenNatures.push(s.pattern[s.layer]);awardRealmFeat(g,'adaptation');}g.sound('achievement');g.effect(e.x,e.y,'realm-breach',340,.8);g.announce('DEFENSE SHATTERED');}
 const floor=e.maxHp*(3-s.layer)/4,actual=Math.min(Math.max(0,amount),Math.max(0,e.hp-floor));
 if(e.hp-actual<=floor+.001&&s.layer<3){if(!(s.rewardedLayers&(1<<s.layer))){s.rewardedLayers|=1<<s.layer;g.score.award(TITAN_REALM.layerReward,true);}s.layer++;s.open=false;g.announce('A NEW DEFENSE AWAKENS');g.effect(e.x,e.y,'realm-boundary',280,.6);}
 return actual;
}
export function realmKill(g:Game,e:Enemy){const s=g.realm!;if(e.realm?.role==='boss'){s.cleared=true;s.rewardedLayers|=8;if(s.resets===0)awardRealmFeat(g,'resolve');g.score.award(TITAN_REALM.layerReward+TITAN_REALM.clearReward,true);g.ended=true;g.sound('achievement');return;}if(e.realm?.role==='guardian'){s.guardians++;const shrine=e.realm.shrine!;if(!g.enemies.some(other=>other.active&&other.realm?.role==='guardian'&&other.realm.shrine===shrine)){s.shrines[shrine].cleared=true;g.score.award(TITAN_REALM.guardianReward,true);g.announce('GROTTO CLEARED · THE RELIC IS YOURS');g.heal(g.player.maxHp*.3,true);}}}
export function claimRelic(g:Game,shrine:number){const s=g.realm;if(!s||g.ended||s.engaged||!s.shrines[shrine]?.cleared)return false;const spot=REALM_GROTTOS[shrine];if(Math.hypot(g.player.x-spot.x,g.player.y-(spot.y-150))>240)return false;const relic=s.relics.find(r=>r.shrine===shrine)!;relic.known=true;s.shrines[shrine].claimed=true;s.shrines[shrine].decor=relic.nature;g.sound('achievement');return true;}
export function equipRelic(g:Game,relicId:string,index:number){const s=g.realm,r=s?.relics.find(r=>r.id===relicId);if(!s||g.ended||s.engaged||!r?.known||!Number.isInteger(index)||index<0||index>3||nearClearedShrine(g)?.id!==r.shrine)return false;if(g.powers.some((p,i)=>i!==index&&p.id===r.ability))return false;g.powers[index]=ABILITIES[r.ability];g.relicOwners[index]=r.nature;g.cooldowns[index]=g.powers[index].cooldown*.8;clearRelicEffects(g);s.shrines[nearClearedShrine(g)!.id].decor=r.nature;return true;}
export function restoreNativePower(g:Game,index:number){if(!g.realm||g.ended||g.realm.engaged||!nearClearedShrine(g)||index<0||index>3)return false;const id=abilitiesForStage(g.monster.id,g.phase,g.titanKit)[index].id;if(g.powers.some((p,i)=>i!==index&&p.id===id))return false;g.powers[index]=ABILITIES[id];g.relicOwners[index]=g.monster.id;g.cooldowns[index]=g.powers[index].cooldown*.8;clearRelicEffects(g);return true;}
function clearRelicEffects(g:Game){g.servants.forEach(s=>s.active=false);g.fields.length=g.bolts.length=g.scytheWaves.length=g.fissures.length=g.clawWaves.length=g.chains.length=0;g.enemies.forEach(e=>e.corruptUntil=0);g.relicPulses.length=0;g.moonFury=0;g.beam=g.reaperStorm=g.frenzy=g.frenzyGuard=g.player.rage=g.shield=g.momentum=0;g.dash=null;g.lungeCharges=g.maxLungeCharges();g.lungeRecharge=0;const lunge=g.powers.findIndex(p=>p.effect==='lunge');if(lunge>=0)g.cooldowns[lunge]=0;}
export function nearClearedShrine(g:Game){return REALM_GROTTOS.find(s=>g.realm?.shrines[s.id].cleared&&Math.hypot(g.player.x-s.x,g.player.y-(s.y-150))<240);}
export function realmTraits(g:Game){return [...new Set(g.relicOwners)].map(id=>({id,name:id==='overlord'?(g.powers.some(p=>['dominate','summon','dominion'].includes(p.effect))?'Servant Siphon':'Soul Writ Recovery'):MONSTERS[id].passive.name,description:id==='overlord'?(g.powers.some(p=>['dominate','summon','dominion'].includes(p.effect))?'Servant kills restore health within one shared recovery limit.':'Spectral pulses steal life within their recovery reserve.'):MONSTERS[id].passive.description}));}
export function castRealmPower(g:Game,index:number,point?:{x:number;y:number}){const s=g.realm!,base=g.powers[index];if(g.ended||!base||g.cooldowns[index]>0&&!(base.effect==='lunge'&&g.lungeCharges>0))return false;const nature=powerNature(g,index),p=releasedPower(base,nature,4);if(point&&(!Number.isFinite(point.x)||!Number.isFinite(point.y)||!g.insideMap(point.x,point.y)||Math.abs(point.x-g.player.x)>g.targetView.x||Math.abs(point.y-g.player.y)>g.targetView.y))return false;
 if(p.effect==='parkour'&&!parkourLanding(g,point))return false;if(p.effect==='reaperblink'&&point&&!reaperTappedEnemy(g,point))return false;if(p.effect==='reaperstorm')s.stormPower=p;const original=g.monster,oldFields=g.fields.length;s.castNature=nature;s.castAbility=base.id;if(p.effect==='lunge'){if(g.lungeCharges<=0){s.castNature='';s.castAbility='';return false;}g.lungeCharges--;if(g.lungeRecharge<=0)g.lungeRecharge=p.cooldown;g.cooldowns[index]=g.lungeCharges>0?0:g.lungeRecharge;}else g.cooldowns[index]=p.cooldown;g.targetPoint=point||null;if(p.effect==='beam')s.beamNature=nature;try{g.monster=MONSTERS[nature];POWER_HANDLERS[p.effect](g,p);}finally{g.monster=original;s.castNature='';s.castAbility='';g.targetPoint=null;}
 for(let i=oldFields;i<g.fields.length;i++)g.fields[i].nature=nature;g.sound('ability.'+p.id);if(!['realmrelic','parkour','wolfhowl','wolfravage','wolffury'].includes(p.effect))g.effect(g.player.x,g.player.y,'relic-cast-'+nature,p.radius,.45);if(['blast','dominion','frenzy','reaperstorm','wolffury'].includes(p.effect)){s.cutinPower=base;g.ultimateTime=.85;g.sound('ultimateStart');}return true;
}
function addUnit(g:Game,kind:'thrall'|'brute'|'spitter'|'hound'|'wing',x:number,y:number,role:'guardian'|'attendant',shrine?:number){const e=g.spawn(kind);if(!e)return;slideRealm({x,y},24);const hp=role==='guardian'?(kind==='brute'?12000:kind==='spitter'?4000:4000):(kind==='brute'?300:kind==='spitter'?110:70);Object.assign(e,{x,y,hp,maxHp:hp,realm:{role,shrine,homeX:x,homeY:y,variant:kind==='brute'?0:kind==='spitter'?1:kind==='hound'?2:kind==='wing'?3:4,hintNature:role==='attendant'?g.realm!.pattern[Math.min(3,g.realm!.layer)]:undefined}});g.slideArena(e,25);}
export function updateTitanRealm(g:Game,dt:number){const s=g.realm!,p=g.player;if(!s.boss)seedTitanRealm(g);const inside=inTitanArena(p.x,p.y);if(inside&&!s.engaged){s.engaged=true;s.attempts++;if(s.attempts===1&&s.relics.filter(r=>r.known).length>=4)awardRealmFeat(g,'prepared');s.away=0;g.announce('THE TITAN ACKNOWLEDGES YOUR CHALLENGE');g.sound('titanArrival');}if(s.engaged){s.away=inside?0:s.away+dt;if(s.away>=TITAN_REALM.resetDelay){s.engaged=false;s.away=0;s.resets++;s.layer=0;s.open=false;s.boss!.hp=s.boss!.maxHp;s.zones.length=0;g.shots.length=0;g.fields.length=0;g.bolts.length=0;g.beam=0;g.announce('THE TITAN REFORMS · ALL DEFENSES RESTORED');}}
 for(const shrine of s.shrines)if(!shrine.spawned){const spot=REALM_GROTTOS[shrine.id];if(Math.hypot(p.x-spot.x,p.y-spot.y)<680){const retire=g.enemies.filter(e=>e.active&&e.realm?.role==='attendant').sort((a,b)=>Math.hypot(b.x-p.x,b.y-p.y)-Math.hypot(a.x-p.x,a.y-p.y));while(g.alive>TITAN_REALM.maxCrowd-3&&retire.length){retire.shift()!.active=false;g.alive--;}shrine.spawned=true;addUnit(g,'brute',spot.x,spot.y+40,'guardian',shrine.id);addUnit(g,'spitter',spot.x-170,spot.y+80,'guardian',shrine.id);addUnit(g,'hound',spot.x+170,spot.y+120,'guardian',shrine.id);}}
 s.interaction=REALM_GROTTOS.find(spot=>Math.hypot(p.x-spot.x,p.y-(spot.y-150))<240)?.id??null;if(!inside&&nearClearedShrine(g))g.heal(p.maxHp*.045*dt,true);
 s.spawnTimer-=dt;if(s.spawnTimer<=0){s.spawnTimer=Math.max(1.2,2.5-g.time/400);const common=g.enemies.filter(e=>e.active&&e.realm?.role==='attendant').length;if(common<Math.min(48,20+Math.floor(g.time/45))){for(let spawn=0;spawn<3&&common+spawn<Math.min(48,20+Math.floor(g.time/45))&&g.alive<TITAN_REALM.maxCrowd;spawn++){const a=g.random()*Math.PI*2;let x=p.x+Math.cos(a)*420,y=p.y+Math.sin(a)*420;const q={x,y};g.slideArena(q,25);x=q.x;y=q.y;const kinds=['thrall','hound','spitter','wing','brute'] as const;addUnit(g,kinds[Math.floor(g.random()*kinds.length)],x,y,'attendant');}}}
 for(let i=s.zones.length-1;i>=0;i--){const z=s.zones[i];z.warning-=dt;if(z.warning<=0){z.life-=dt;if(!z.hit){z.hit=true;g.effect(z.x,z.y,'realm-slam',z.radius,.6);g.sound('titanImpact');}if(inside&&Math.hypot(p.x-z.x,p.y-z.y)<z.radius+20&&z.life>.12){g.hurt(z.damage);z.life=.12;}if(z.life<=0)s.zones.splice(i,1);}}
}
export function realmEnemyMotion(g:Game,e:Enemy,dt:number){const s=g.realm!,p=g.player,u=e.realm!,distance=Math.hypot(p.x-e.x,p.y-e.y);if(u.role==='boss'){if(!s.engaged){const angle=g.time*.08;e.x=Math.cos(angle)*170;e.y=Math.sin(angle)*130;return;}if(!inTitanArena(p.x,p.y))return;const dx=p.x-e.x,dy=p.y-e.y,d=Math.hypot(dx,dy)||1,speed=(distance>180?46:0)*(g.fissures.length?fissureMotion(g,e):1);e.x+=dx/d*speed*dt;e.y+=dy/d*speed*dt;const r=Math.hypot(e.x,e.y);if(r>REALM_RING-100){e.x*= (REALM_RING-100)/r;e.y*= (REALM_RING-100)/r;}if(distance<125&&e.timer<=0){g.hurt(190);e.timer=1.4;}if(e.timer<=0&&s.zones.length<12){const radius=110+(s.layer*8);for(let i=0;i<4&&s.zones.length<12;i++){const a=i*Math.PI/2+g.time*.6,offset=i?135:0,x=p.x+Math.cos(a)*offset,y=p.y+Math.sin(a)*offset;if(inTitanArena(x,y))s.zones.push({x,y,radius:i?radius:145,warning:1.25,life:.55,damage:160+s.layer*22,hit:false});}if(distance<270&&s.zones.length<12)s.zones.push({x:e.x,y:e.y,radius:285,warning:1.55,life:.5,damage:240,hit:false});e.timer=3.7-s.layer*.25;}return;}
 if(u.role==='guardian'&&u.variant!==1){if(e.windup>0){e.windup-=dt;if(e.windup<=0){if(u.variant===0){g.effect(e.x,e.y,'realm-slam',170,.6);g.sound('titanImpact');if(distance<190)g.hurt(165);}else{e.vx=(p.x-e.x)/Math.max(1,distance)*420;e.vy=(p.y-e.y)/Math.max(1,distance)*420;g.effect(e.x,e.y,'realm-breach',100,.4);}}}else if(distance<(u.variant===0?210:300)&&e.timer<=0){e.windup=u.variant===0?1.15:.7;e.timer=u.variant===0?4.3:3.8;}}
 const chase=u.role==='attendant'||distance<550,tx=chase?p.x:u.homeX,ty=chase?p.y:u.homeY;if(distance>1200&&u.role==='attendant'){e.active=false;g.alive--;return;}let speed=u.variant===2?110:u.variant===3?95:u.variant===4?70:u.variant===1?50:55;if(u.variant===1&&distance<350){speed=distance<210?-45:0;if(e.timer<=0&&g.shots.length<48){const d=Math.max(1,distance);const angle=Math.atan2(p.y-e.y,p.x-e.x);for(const offset of u.role==='guardian'?[-.18,0,.18]:[0])g.shots.push({x:e.x,y:e.y,vx:Math.cos(angle+offset)*240,vy:Math.sin(angle+offset)*240,life:3,damage:u.role==='guardian'?55:24});e.timer=2.4;}}
 if((e.snaredUntil||0)>g.time)speed*=.18;if(g.fissures.length)speed*=fissureMotion(g,e);const v=realmSteer(e.x,e.y,tx,ty);e.x+=(v.x*speed+e.vx)*dt;e.y+=(v.y*speed+e.vy)*dt;g.slideArena(e,24);e.vx*=Math.exp(-dt*4);e.vy*=Math.exp(-dt*4);if(distance<58&&e.timer<=0){g.hurt(u.role==='guardian'?90:24);e.timer=.8;}}
export function realmSummary(g:Game){const s=g.realm!;return {guardians:s.guardians,shrines:s.shrines.filter(s=>s.cleared).length,layers:[0,1,2,3].filter(i=>s.rewardedLayers&(1<<i)).length,relics:s.relics.filter(r=>r.known).length,attempts:s.attempts,resets:s.resets,breaches:s.breaches,cleared:s.cleared,combat:s.combat,objective:s.objective,loadout:g.powers.map((p,i)=>({ability:p.id,nature:g.relicOwners[i]}))};}

export type RealmResult=ReturnType<typeof realmSummary>;

export function realmProgress(g:Game,finished=false){const s=g.realm;if(!s)return {metrics:{},values:{}};const summary=realmSummary(g),clear=finished&&s.cleared?1:0,clean=clear&&s.resets===0?1:0;return {metrics:{realmGuardians:s.guardians,realmShrines:summary.shrines,realmLayers:summary.layers,realmRelics:summary.relics,realmClear:clear,realmClean:clean,realmInsight:g.score.feats.insight||0},values:{realmGuardians:s.guardians,realmShrines:summary.shrines,realmLayers:summary.layers,realmRelics:summary.relics,realmClears:clear,realmCleanClears:clean,realmInsights:g.score.feats.insight||0,...Object.fromEntries(Object.keys(FIFTH_POWERS).map(id=>['realmRelic'+id[0].toUpperCase()+id.slice(1)+'Clear',clear&&s.brokenNatures.includes(id)?1:0]))}};}
