import {EVENT} from './data.ts';
import {COURT_SITE_GROUPS,COURT_SHRINES,slideCourt,courtSteer} from './court-map.ts';
import type {Game,Enemy} from './simulation.ts';
export const COURT_RULES='2026.10-v21-court-hunts',COURT_TEST_RULES='2026.10-v21-court-test';
export const rulesForStage=(phase:number,testing=false)=>phase===1?(testing?COURT_TEST_RULES:COURT_RULES):EVENT.rules;
export const COURT={total:10,activationRadius:1000,hintStart:720,hintTrail:900,hintPeriod:30,hintLife:8,sealLife:120,sealRadius:60,sealBonus:15000,guardBonus:400,impactBonus:1500,closeBonus:6000,closeRange:220,spawnRate:.28,crowdCap:.4,startRelease:4,captainHp:32000,hpPerCaptain:.4,slamRadius:170,slamWarning:1.4,slamCycle:4.6,slamDamage:115,healScale:.4,devourerHealScale:.75,devourDrain:.1,devourMinimum:.18,shieldScale:.4,shieldCapScale:.55,combatPerCaptain:50000,speedMax:1000000,speedFullAt:600,speedZeroAt:900};
export const COURT_UPGRADES=[
 {id:'haste',name:'Wayfarer',description:'+12% movement speed. Reach the next captain and escape pursuit.'},
 {id:'power',name:'Kingslayer',description:'+18% attack and ability damage. Cut through tougher captains.'},
 {id:'reach',name:'Far Reach',description:'+12% attack and ability reach. Strike more prey in each attack.'},
 {id:'recharge',name:'Relentless',description:'Ability cooldowns are 10% shorter. Use your signature powers more often.'},
 {id:'tempo',name:'Rending Rhythm',description:'+18% basic attack speed. Strike more often between abilities.'},
 {id:'duration',name:'Enduring Power',description:'+20% duration for spells, servants and protective states. Dash distance and meteor timing stay precise.'},
 {id:'vitality',name:'Second Heart',description:'+15% maximum health; recover 30% health instead of 15%.'}
] as const;
export type CourtUpgrade=typeof COURT_UPGRADES[number]['id'];
export type CourtScoring={combat:number;captain:number;speed:number};
export type CourtMission={upgrades:CourtUpgrade[];cleared:boolean;total:number;scoring?:CourtScoring};
export type CourtUnit={role:'captain'|'vanguard';guard:number;maxGuard:number;facing:number;broken:boolean;homeX:number;homeY:number;homeAngle:number;site?:number;tier?:number;collisionAt?:number};
export type CourtStats={hunts:number;captains:number;guards:number;impacts:number;close:number;seals:number;lost:number;bonus:number};
export type CourtSeal={x:number;y:number;life:number;serial:number};
export type CourtCamp={x:number;y:number;visited:boolean;spawned:boolean;slain:boolean};
export type CourtState={seals:CourtSeal[];stats:CourtStats;camps:CourtCamp[];upgrades:CourtUpgrade[];pending:number;cleared:boolean;initialized:boolean;scoring:CourtScoring;scoreLimitedAt:number;shrines:{x:number;y:number;readyAt:number}[];healingVisits:number;hint:{site:number;life:number;trail:boolean}|null;nextHintAt:number;hintAnnounced:boolean};
export const createCourt=():CourtState=>({seals:[],stats:{hunts:0,captains:0,guards:0,impacts:0,close:0,seals:0,lost:0,bonus:0},camps:[],upgrades:[],pending:0,cleared:false,initialized:false,scoring:{combat:0,captain:0,speed:0},scoreLimitedAt:-1,shrines:COURT_SHRINES.map(p=>({...p,readyAt:0})),healingVisits:0,hint:null,nextHintAt:COURT.hintStart,hintAnnounced:false});
export function initializeCourt(g:Game){const state=g.court!;if(state.initialized)return;state.initialized=true;const sites=COURT_SITE_GROUPS.map(group=>group[Math.floor(g.random()*group.length)]);for(let i=sites.length-1;i>0;i--){const j=Math.floor(g.random()*(i+1));[sites[i],sites[j]]=[sites[j],sites[i]];}state.camps=sites.map(s=>({...s,visited:false,spawned:false,slain:false}));g.notice='THE ASHEN WILDS · HUNT ALL TEN CAPTAINS';g.noticeTime=4;}
export const upgradeRank=(g:Game,id:CourtUpgrade)=>g.court?.upgrades.filter(u=>u===id).length||0;
export const courtRelease=(_g:Game)=>COURT.startRelease;
export function chooseCourtUpgrade(g:Game,id:CourtUpgrade){const state=g.court;if(!state||state.pending<=0||state.cleared||!COURT_UPGRADES.some(u=>u.id===id)||upgradeRank(g,id)>=3)return false;state.upgrades.push(id);state.pending--;if(id==='vitality')g.player.maxHp=g.monster.hp*(1+.15*upgradeRank(g,id));g.heal(g.player.maxHp*(id==='vitality'?.30:.15),true);g.player.invuln=Math.max(g.player.invuln,1.5);g.announce('HUNT BOON · '+COURT_UPGRADES.find(u=>u.id===id)!.name.toUpperCase());return true;}
export const courtMission=(g:Game):CourtMission=>({upgrades:[...g.court!.upgrades],cleared:g.court!.cleared,total:COURT.total,scoring:{...g.court!.scoring}});
export const courtContactScale=(e:Enemy)=>e.court?.role==='vanguard'?.45:e.court?.role==='captain'?.48*(1+.07*(e.court.tier||0)):1;
function bonus(g:Game,amount:number){g.score.dominance+=amount;g.court!.stats.bonus+=amount;}
export function breakCourtGuard(g:Game,e:Enemy,impact=false){const unit=e.court;if(!unit||unit.broken)return;unit.guard=0;unit.broken=true;g.court!.stats.guards++;if(impact)g.court!.stats.impacts++;bonus(g,COURT.guardBonus+(impact?COURT.impactBonus:0));g.effect(e.x,e.y,'court-break',65,.4);}
export function courtDamage(g:Game,e:Enemy,amount:number,source:string,origin?:{x:number;y:number}){const unit=e.court;if(!unit)return amount;if(unit.role==='captain'){if(source==='beam')amount*=g.monster.id==='sovereign'?1:.6;if(source==='collision'){if(g.time<(unit.collisionAt??-1))return 0;unit.collisionAt=g.time+.12;}if(source==='collision')amount*=4.5;else if(['launch','shockwave','trample'].includes(source))amount*=g.monster.id==='titan'?18:15;if(Math.hypot(g.player.x-e.x,g.player.y-e.y)<=COURT.closeRange)amount*=1.25;if(['controlled','summoned'].includes(source))amount*=1.3;if(source==='execute')amount=Math.max(amount*3.5,e.maxHp*.055);}if(unit.guard<=0)return amount;if(['launch','shockwave','collision','trample','lunge'].includes(source)){breakCourtGuard(g,e,true);return amount;}const point=origin??g.player,dx=point.x-e.x,dy=point.y-e.y,front=dx*Math.cos(unit.facing)+dy*Math.sin(unit.facing),distance=Math.hypot(dx,dy),flanked=distance>0&&front/distance<Math.cos(Math.PI*.44),absorbed=flanked?0:Math.min(unit.guard,amount*.6);unit.guard=Math.max(0,unit.guard-(flanked?amount*.25:absorbed));if(unit.guard===0)breakCourtGuard(g,e);return amount-absorbed;}
export function courtKill(g:Game,e:Enemy){if(!e.court)return;breakCourtGuard(g,e);if(e.court.role!=='captain')return;const state=g.court!;state.stats.captains++;state.hint=null;state.nextHintAt=Math.min(state.nextHintAt,g.time+3);if(e.court.site!==undefined)state.camps[e.court.site].slain=true;if(Math.hypot(g.player.x-e.x,g.player.y-e.y)<=COURT.closeRange){state.stats.close++;bonus(g,COURT.closeBonus);}const point={x:e.x,y:e.y};slideCourt(point,22);state.seals.push({...point,life:COURT.sealLife,serial:e.serial});g.announce('CAPTAIN '+state.stats.captains+' / '+COURT.total+' SLAIN');if(state.stats.captains===COURT.total){state.seals.pop();state.stats.seals++;bonus(g,COURT.sealBonus);state.scoring.speed=courtSpeedBonus(g.time);g.score.dominance+=state.scoring.speed;state.cleared=true;state.pending=0;g.ended=true;g.sound('achievement');}else state.pending++;for(const other of g.enemies)if(other.active&&other.court?.role==='captain'){const ratio=(1+state.stats.captains*COURT.hpPerCaptain)/(1+(other.court.tier||0)*COURT.hpPerCaptain);other.hp*=ratio;other.maxHp*=ratio;other.court.guard*=ratio;other.court.maxGuard*=ratio;other.court.tier=state.stats.captains;}}
export function courtEnemyMotion(g:Game,e:Enemy,dt:number){const unit=e.court;if(!unit)return null;const desired=Math.atan2(g.player.y-e.y,g.player.x-e.x),turn=Math.atan2(Math.sin(desired-unit.facing),Math.cos(desired-unit.facing));unit.facing+=Math.max(-dt*.8,Math.min(dt*.8,turn));const near=Math.hypot(g.player.x-unit.homeX,g.player.y-unit.homeY)<420,angle=unit.homeAngle+g.time*.22,tx=near?g.player.x:unit.homeX+(unit.role==='captain'?Math.cos(angle)*65:0),ty=near?g.player.y:unit.homeY+(unit.role==='captain'?Math.sin(angle)*65:0),direction=courtSteer(e.x,e.y,tx,ty);return {dx:direction.x,dy:direction.y,speed:near?(unit.role==='captain'?92:100):Math.min(55,Math.hypot(tx-e.x,ty-e.y)*2)};}
export function spawnCourtHunt(g:Game,siteIndex?:number){const state=g.court;if(!state)return false;initializeCourt(g);const index=siteIndex??state.camps.findIndex(c=>!c.spawned&&!c.slain);if(index<0||state.camps[index].spawned||g.alive>EVENT.maxEnemies-50)return false;const site=state.camps[index],{x,y}=site,facing=Math.atan2(g.player.y-y,g.player.x-x),tier=state.stats.captains,scale=1+tier*COURT.hpPerCaptain,captain=g.spawn('brute');if(!captain)return false;site.spawned=site.visited=true;Object.assign(captain,{x,y,hp:COURT.captainHp*scale,maxHp:COURT.captainHp*scale,court:{role:'captain',guard:900*scale,maxGuard:900*scale,facing,broken:false,homeX:x,homeY:y,homeAngle:g.random()*Math.PI*2,site:index,tier}});slideCourt(captain,24);for(let i=0;i<4;i++){const e=g.spawn('brute');if(!e)break;const side=(i-1.5)*62;Object.assign(e,{x:x+Math.cos(facing)*85-Math.sin(facing)*side,y:y+Math.sin(facing)*85+Math.cos(facing)*side,hp:170*scale,maxHp:170*scale,court:{role:'vanguard',guard:150*scale,maxGuard:150*scale,facing,broken:false,homeX:x,homeY:y,homeAngle:0}});slideCourt(e,21);e.court!.homeX=e.x;e.court!.homeY=e.y;}for(let i=0;i<16;i++){const e=g.spawn(i===14?'spitter':i===15?'hound':'thrall');if(!e)break;const angle=i*Math.PI*2/16;e.x=x+Math.cos(angle)*170;e.y=y+Math.sin(angle)*170;slideCourt(e,12);}state.stats.hunts++;return true;}
export function updateCourt(g:Game,dt:number){const state=g.court;if(!state)return;for(const shrine of state.shrines)if(g.time>=shrine.readyAt&&g.player.hp<g.player.maxHp*.8&&Math.hypot(g.player.x-shrine.x,g.player.y-shrine.y)<80){g.heal(g.player.maxHp*.45,true);shrine.readyAt=g.time+90;state.healingVisits++;g.announce('OASIS RECOVERY · SHRINE RESTS FOR 90 SECONDS');}initializeCourt(g);updateCourtHint(g,dt);for(let i=0;i<state.camps.length;i++){const camp=state.camps[i];if(!camp.slain&&Math.hypot(camp.x-g.player.x,camp.y-g.player.y)<COURT.activationRadius){camp.visited=true;if(!camp.spawned)spawnCourtHunt(g,i);}}for(let i=state.seals.length-1;i>=0;i--){const seal=state.seals[i];seal.life-=dt;if(Math.hypot(g.player.x-seal.x,g.player.y-seal.y)<=COURT.sealRadius){state.stats.seals++;bonus(g,COURT.sealBonus);g.sound('achievement');state.seals.splice(i,1);}else if(seal.life<=0){state.stats.lost++;state.seals.splice(i,1);}}}


export function courtProgress(g:Game,finished=false){if(!g.court)return {values:{},best:{},metrics:{}};const s=g.court.stats,clear=finished&&g.court.cleared?1:0,fast=clear&&g.time<=720?1:0,swift=clear&&g.time<=600?1:0;
 const values={courtCaptains:s.captains,courtGuards:s.guards,courtClears:clear};
 const best={courtGuardRun:s.guards,courtCloseClear:clear?s.close:0,courtFastClear:fast,courtSwiftClear:swift,courtHasteClear:clear&&upgradeRank(g,'haste')===3?1:0,courtTempoClear:clear&&upgradeRank(g,'tempo')===3?1:0,courtDurationClear:clear&&upgradeRank(g,'duration')===3?1:0};
 return {values,best,metrics:{courtCaptains:s.captains,courtGuards:s.guards,courtClear:clear,courtFast:fast,courtImpact:s.impacts}};
}

export const courtElapsedSeconds=(time:number)=>Math.max(0,Math.ceil(time-1e-7));
export const courtCombatLimit=(captains:number)=>COURT.combatPerCaptain*Math.min(COURT.total,captains+1);
export const courtSpeedBonus=(time:number)=>Math.max(0,Math.round(COURT.speedMax*(1-Math.max(0,courtElapsedSeconds(time)-COURT.speedFullAt)/(COURT.speedZeroAt-COURT.speedFullAt))));
export function courtScoreCredit(g:Game,amount:number,objective:boolean){const state=g.court!;if(state.cleared)return 0;if(objective){state.scoring.captain+=amount;return amount;}const limit=courtCombatLimit(state.stats.captains),credited=Math.min(amount,Math.max(0,limit-state.scoring.combat));state.scoring.combat+=credited;if(state.scoring.combat>=limit&&state.scoreLimitedAt!==limit){state.scoreLimitedAt=limit;g.announce('MINION SCORE LIMIT · HUNT THE NEXT CAPTAIN');}return credited;}

// Clues use game time, so boon deliberation cannot unlock them or extend a bonus.
// Early pulses give a bearing; the continuous trail arrives after speed score is zero.
export function courtHintTarget(g:Game){const hint=g.court?.hint;if(g.time<COURT.hintStart||!hint||hint.life<=0)return null;const camp=g.court!.camps[hint.site];if(!camp||camp.slain)return null;return g.enemies.find(e=>e.active&&e.court?.role==='captain'&&e.court.site===hint.site)??camp;}
export function updateCourtHint(g:Game,dt:number){const state=g.court;if(!state)return;if(state.hint)state.hint.life=Math.max(0,state.hint.life-dt);if(g.time<COURT.hintStart||state.cleared){state.hint=null;return;}if(g.time<state.nextHintAt)return;if(!state.hintAnnounced){state.hintAnnounced=true;g.announce('ASH TRACES · THE WILDS REVEAL SURVIVING CAPTAINS');}let site=-1,distance=Infinity;state.camps.forEach((c,i)=>{if(c.slain)return;const d=Math.hypot(c.x-g.player.x,c.y-g.player.y);if(d<distance){site=i;distance=d;}});const trail=g.time>=COURT.hintTrail;state.hint=site<0?null:{site,life:trail?1:COURT.hintLife,trail};state.nextHintAt=g.time+(trail?.25:COURT.hintPeriod);}

export function courtHintPath(g:Game){const target=courtHintTarget(g);if(!target)return [];const points=[],p={x:g.player.x,y:g.player.y},count=g.court!.hint!.trail?5:1;for(let i=0;i<count;i++){const distance=Math.hypot(target.x-p.x,target.y-p.y);if(distance<90)break;const dir=courtSteer(p.x,p.y,target.x,target.y),step=Math.min(i===0?110:140,distance-40);p.x+=dir.x*step;p.y+=dir.y*step;slideCourt(p,25);points.push({x:p.x,y:p.y,angle:Math.atan2(dir.y,dir.x)});}return points;}
