import {TITAN_FISSURE_RULES,type TitanKit} from './champion-kits.ts';
import {createCourtFeats,courtFeatGuard,courtFeatCaptain,courtFeatClaim,type CourtFeatState} from './court-feats.ts';
import {createColossus,colossusResult,updateColossus,dismissColossus,type ColossusEncounter,type ColossusResult} from './ashen-colossus.ts';
import {FISSURE} from './titan-fissure.ts';
import {EVENT} from './data.ts';
import {COURT_SITE_GROUPS,COURT_SHRINES,slideCourt,courtSteer,courtWaypoint} from './court-map.ts';
import type {Game,Enemy} from './simulation.ts';
export const COURT_RULES='2026.10-v30-court-hunts',COURT_TEST_RULES='2026.10-v30-court-test';
export const REAPER_RULES='2026.10-v29-reaper';
export const rulesForStage=(phase:number,testing=false,monsterId='',titanKit:TitanKit='throw')=>phase===1?(testing?COURT_TEST_RULES:COURT_RULES):monsterId==='reaper'?REAPER_RULES:phase===0&&monsterId==='titan'&&titanKit==='fissure'?TITAN_FISSURE_RULES:EVENT.rules;
export const COURT={total:10,activationRadius:1200,hintStart:720,hintTrail:900,hintPeriod:30,hintLife:8,sealLife:120,sealRadius:60,sealBonus:500000,guardBonus:10000,impactBonus:20000,closeBonus:25000,closeRange:220,spawnRate:.28,crowdCap:.4,startRelease:4,captainHp:32000,hpPerCaptain:.4,slamRadius:170,slamWarning:1.4,slamCycle:4.6,slamDamage:115,healScale:.4,devourerHealScale:.75,devourDrain:.1,devourMinimum:.18,shieldScale:.4,shieldCapScale:.55,combatPerCaptain:50000,speedMax:3200000,speedFullAt:600,speedZeroAt:900};
export const LEGACY_COURT_SCORE={sealBonus:15000,guardBonus:400,impactBonus:1500,closeBonus:6000,combatPerCaptain:50000,speedMax:1000000,speedFullAt:600,speedZeroAt:900};
export const courtScorePolicy=(rules=COURT_RULES)=>/-v(16|17|18|19|20|21|22|23)-court-/.test(rules)?LEGACY_COURT_SCORE:COURT;
export const COURT_UPGRADES=[
 {id:'haste',name:'Wayfarer',description:'Move 12% faster.'},
 {id:'power',name:'Kingslayer',description:'Deal 18% more damage.'},
 {id:'reach',name:'Far Reach',description:'Gain 12% more attack and ability reach.'},
 {id:'recharge',name:'Relentless',description:'Abilities recharge 10% faster.'},
 {id:'tempo',name:'Rending Rhythm',description:'Basic attacks are 18% faster.'},
 {id:'duration',name:'Enduring Power',description:'Spells, servants and protective states last 20% longer.'},
 {id:'vitality',name:'Second Heart',description:'+15% maximum health; recover 30% health instead of 15%.'}
] as const;
export type CourtUpgrade=typeof COURT_UPGRADES[number]['id'];
export type CourtScoring={combat:number;captain:number;speed:number};
export type CourtMission={upgrades:CourtUpgrade[];cleared:boolean;total:number;scoring?:CourtScoring;colossus?:ColossusResult};
export type CourtUnit={role:'captain'|'vanguard';guard:number;maxGuard:number;facing:number;broken:boolean;homeX:number;homeY:number;homeAngle:number;site?:number;tier?:number;collisionAt?:number;slamThreatened?:boolean;formation?:number;steerAt?:number;targetX?:number;targetY?:number};
export type CourtStats={hunts:number;captains:number;guards:number;impacts:number;close:number;seals:number;lost:number;bonus:number};
export type CourtSeal={x:number;y:number;life:number;serial:number;fallenAt?:number};
export type CourtCamp={x:number;y:number;visited:boolean;spawned:boolean;slain:boolean};
export type CourtState={colossus:ColossusEncounter;feats:CourtFeatState;seals:CourtSeal[];stats:CourtStats;leaders:Map<number,Enemy>;camps:CourtCamp[];upgrades:CourtUpgrade[];pending:number;cleared:boolean;initialized:boolean;scoring:CourtScoring;scoreLimitedAt:number;shrines:{x:number;y:number;readyAt:number}[];healingVisits:number;hint:{site:number;life:number;trail:boolean}|null;nextHintAt:number;hintAnnounced:boolean};
export const createCourt=():CourtState=>({colossus:createColossus(),feats:createCourtFeats(),seals:[],stats:{hunts:0,captains:0,guards:0,impacts:0,close:0,seals:0,lost:0,bonus:0},leaders:new Map(),camps:[],upgrades:[],pending:0,cleared:false,initialized:false,scoring:{combat:0,captain:0,speed:0},scoreLimitedAt:-1,shrines:COURT_SHRINES.map(p=>({...p,readyAt:0})),healingVisits:0,hint:null,nextHintAt:COURT.hintStart,hintAnnounced:false});
export function initializeCourt(g:Game){const state=g.court!;if(state.initialized)return;state.initialized=true;const sites=COURT_SITE_GROUPS.flatMap(group=>{const choices=[...group];for(let i=choices.length-1;i>0;i--){const j=Math.floor(g.random()*(i+1));[choices[i],choices[j]]=[choices[j],choices[i]];}return choices.slice(0,2);});for(let i=sites.length-1;i>0;i--){const j=Math.floor(g.random()*(i+1));[sites[i],sites[j]]=[sites[j],sites[i]];}state.camps=sites.map(s=>({...s,visited:false,spawned:false,slain:false}));g.notice='THE ASHEN WILDS · HUNT ALL TEN CAPTAINS';g.noticeTime=4;}
export const upgradeRank=(g:Game,id:CourtUpgrade)=>g.court?.upgrades.filter(u=>u===id).length||0;
export const courtRelease=(_g:Game)=>COURT.startRelease;
export function chooseCourtUpgrade(g:Game,id:CourtUpgrade){const state=g.court;if(!state||state.pending<=0||state.cleared||!COURT_UPGRADES.some(u=>u.id===id)||upgradeRank(g,id)>=3)return false;state.upgrades.push(id);state.pending--;if(id==='vitality')g.player.maxHp=g.monster.hp*(1+.15*upgradeRank(g,id));g.heal(g.player.maxHp*(id==='vitality'?.30:.15),true);g.player.invuln=Math.max(g.player.invuln,1.5);g.announce('HUNT BOON · '+COURT_UPGRADES.find(u=>u.id===id)!.name.toUpperCase());return true;}
export const courtMission=(g:Game):CourtMission=>{if(g.ended){g.fissures.length=0;dismissColossus(g,true);}return {upgrades:[...g.court!.upgrades],cleared:g.court!.cleared,total:COURT.total,scoring:{...g.court!.scoring},...(colossusResult(g)?{colossus:colossusResult(g)}:{})};};
export const courtContactScale=(e:Enemy)=>e.court?.role==='vanguard'?.45:e.court?.role==='captain'?.48*(1+.07*(e.court.tier||0)):1;
function bonus(g:Game,amount:number){g.score.dominance+=amount;g.court!.stats.bonus+=amount;}
export function breakCourtGuard(g:Game,e:Enemy,impact=false){const unit=e.court;if(!unit||unit.broken)return;unit.guard=0;unit.broken=true;courtFeatGuard(g,e);g.court!.stats.guards++;if(impact)g.court!.stats.impacts++;bonus(g,COURT.guardBonus+(impact?COURT.impactBonus:0));g.effect(e.x,e.y,'court-break',65,.4);}
export function courtGuardCover(g:Game,e:Enemy,point:{x:number;y:number}){const dx=point.x-e.x,dy=point.y-e.y,d=Math.hypot(dx,dy);if(d<130)return false;let cover=false;g.nearby(e.x,e.y,260,guard=>{if(cover||guard.court?.role!=='vanguard'||guard.court.guard<=0)return;const gx=guard.x-e.x,gy=guard.y-e.y,along=(gx*dx+gy*dy)/d,across=Math.abs(gx*dy-gy*dx)/d;if(along>25&&along<Math.min(d,230)&&across<60)cover=true;});return cover;}
export function courtDamage(g:Game,e:Enemy,amount:number,source:string,origin?:{x:number;y:number}){const unit=e.court;if(!unit)return amount;if(unit.role==='captain'){if(g.monster.id==='reaper'&&['scythe','reapingarc','moonstorm'].includes(source))amount*=1.8;if(source==='beam')amount*=g.monster.id==='sovereign'?1:.6;if((['beam','clawwave','scythe','reapingarc','moonstorm'].includes(source)||source==='direct'&&g.monster.basic.ranged)&&courtGuardCover(g,e,origin??g.player))amount*=.65;if(source==='collision'){if(g.time<(unit.collisionAt??-1))return 0;unit.collisionAt=g.time+.12;}if(source==='collision')amount*=4.5;else if(source==='fissure-impact')amount*=FISSURE.captainImpact;else if(source==='fissure')amount*=FISSURE.captainTick;else if(['launch','shockwave','trample'].includes(source))amount*=g.monster.id==='titan'?18:15;if(Math.hypot(g.player.x-e.x,g.player.y-e.y)<=COURT.closeRange)amount*=1.25;if(['controlled','summoned'].includes(source))amount*=1.1;if(source==='execute')amount=Math.max(amount*3.5,e.maxHp*.055);}if(unit.guard<=0)return amount;if(['launch','shockwave','collision','trample','lunge','reapersweep','graveshift','fissure-impact'].includes(source)){breakCourtGuard(g,e,true);return amount;}const point=origin??g.player,dx=point.x-e.x,dy=point.y-e.y,front=dx*Math.cos(unit.facing)+dy*Math.sin(unit.facing),distance=Math.hypot(dx,dy),flanked=distance>0&&front/distance<Math.cos(Math.PI*.44),absorbed=flanked?0:Math.min(unit.guard,amount*(unit.role==='vanguard'?.85:.6));unit.guard=Math.max(0,unit.guard-(flanked?amount*.25:absorbed));if(unit.guard===0)breakCourtGuard(g,e);return amount-absorbed;}
export function courtKill(g:Game,e:Enemy){if(!e.court)return;breakCourtGuard(g,e);if(e.court.role!=='captain')return;const state=g.court!;courtFeatCaptain(g,e);state.stats.captains++;state.hint=null;state.nextHintAt=Math.min(state.nextHintAt,g.time+3);if(e.court.site!==undefined)state.camps[e.court.site].slain=true;updateCourtHint(g,0);if(Math.hypot(g.player.x-e.x,g.player.y-e.y)<=COURT.closeRange){state.stats.close++;bonus(g,COURT.closeBonus);}const point={x:e.x,y:e.y};slideCourt(point,22);state.seals.push({...point,life:COURT.sealLife,serial:e.serial,fallenAt:g.time});g.announce('CAPTAIN '+state.stats.captains+' / '+COURT.total+' SLAIN');if(state.stats.captains===COURT.total){state.seals.pop();courtFeatClaim(g,e.serial,g.time);state.stats.seals++;bonus(g,COURT.sealBonus);state.scoring.speed=courtSpeedBonus(g.time);g.score.dominance+=state.scoring.speed;state.cleared=true;state.pending=0;g.fissures.length=0;dismissColossus(g,true);g.ended=true;g.sound('achievement');}else state.pending++;for(const other of g.enemies)if(other.active&&other.court?.role==='captain'){const ratio=(1+state.stats.captains*COURT.hpPerCaptain)/(1+(other.court.tier||0)*COURT.hpPerCaptain);other.hp*=ratio;other.maxHp*=ratio;other.court.guard*=ratio;other.court.maxGuard*=ratio;other.court.tier=state.stats.captains;}}
export function courtEnemyMotion(g:Game,e:Enemy,dt:number){const unit=e.court;if(!unit)return null;const desired=Math.atan2(g.player.y-e.y,g.player.x-e.x),turn=Math.atan2(Math.sin(desired-unit.facing),Math.cos(desired-unit.facing));unit.facing+=Math.max(-dt*.8,Math.min(dt*.8,turn));const leader=unit.role==='vanguard'&&unit.site!==undefined?g.court!.leaders.get(unit.site):undefined;if(leader?.active&&unit.guard>0&&Math.hypot(g.player.x-leader.x,g.player.y-leader.y)<720){if(g.time>=(unit.steerAt??-1)){const a=Math.atan2(g.player.y-leader.y,g.player.x-leader.x),side=((unit.formation??0)-1.5)*62,point={x:leader.x+Math.cos(a)*110-Math.sin(a)*side,y:leader.y+Math.sin(a)*110+Math.cos(a)*side};slideCourt(point,24);unit.targetX=point.x;unit.targetY=point.y;unit.steerAt=g.time+.25;}const tx=unit.targetX!,ty=unit.targetY!,direction=courtSteer(e.x,e.y,tx,ty),distance=Math.hypot(tx-e.x,ty-e.y);return {dx:direction.x,dy:direction.y,speed:Math.min(145,distance*3)};}const near=Math.hypot(g.player.x-unit.homeX,g.player.y-unit.homeY)<420,angle=unit.homeAngle+g.time*.22,tx=near?g.player.x:unit.homeX+(unit.role==='captain'?Math.cos(angle)*65:0),ty=near?g.player.y:unit.homeY+(unit.role==='captain'?Math.sin(angle)*65:0),direction=courtSteer(e.x,e.y,tx,ty);return {dx:direction.x,dy:direction.y,speed:near?(unit.role==='captain'?92:100):Math.min(55,Math.hypot(tx-e.x,ty-e.y)*2)};}
export function spawnCourtHunt(g:Game,siteIndex?:number){const state=g.court;if(!state)return false;initializeCourt(g);const index=siteIndex??state.camps.findIndex(c=>!c.spawned&&!c.slain);if(index<0||state.camps[index].spawned||g.alive>EVENT.maxEnemies-50)return false;const site=state.camps[index],{x,y}=site,facing=Math.atan2(g.player.y-y,g.player.x-x),tier=state.stats.captains,scale=1+tier*COURT.hpPerCaptain,captain=g.spawn('brute');if(!captain)return false;site.spawned=site.visited=true;Object.assign(captain,{x,y,hp:COURT.captainHp*scale,maxHp:COURT.captainHp*scale,court:{role:'captain',guard:900*scale,maxGuard:900*scale,facing,broken:false,homeX:x,homeY:y,homeAngle:g.random()*Math.PI*2,site:index,tier}});slideCourt(captain,24);state.leaders.set(index,captain);for(let i=0;i<4;i++){const e=g.spawn('brute');if(!e)break;const side=(i-1.5)*62;Object.assign(e,{x:x+Math.cos(facing)*85-Math.sin(facing)*side,y:y+Math.sin(facing)*85+Math.cos(facing)*side,hp:1600*scale,maxHp:1600*scale,court:{role:'vanguard',guard:2200*scale,maxGuard:2200*scale,facing,broken:false,homeX:x,homeY:y,homeAngle:0,site:index,formation:i}});slideCourt(e,21);e.court!.homeX=e.x;e.court!.homeY=e.y;}for(let i=0;i<16;i++){const e=g.spawn(i===14?'spitter':i===15?'hound':'thrall');if(!e)break;const angle=i*Math.PI*2/16;e.x=x+Math.cos(angle)*170;e.y=y+Math.sin(angle)*170;slideCourt(e,12);}state.stats.hunts++;return true;}
export function updateCourt(g:Game,dt:number){const state=g.court;if(!state)return;for(const shrine of state.shrines)if(g.time>=shrine.readyAt&&g.player.hp<g.player.maxHp*.8&&Math.hypot(g.player.x-shrine.x,g.player.y-shrine.y)<80){g.heal(g.player.maxHp*.45,true);shrine.readyAt=g.time+90;state.healingVisits++;g.announce('OASIS RECOVERY · SHRINE RESTS FOR 90 SECONDS');}initializeCourt(g);updateColossus(g);updateCourtHint(g,dt);for(let i=0;i<state.camps.length;i++){const camp=state.camps[i];if(!camp.slain&&Math.hypot(camp.x-g.player.x,camp.y-g.player.y)<COURT.activationRadius){camp.visited=true;if(!camp.spawned)spawnCourtHunt(g,i);}}for(let i=state.seals.length-1;i>=0;i--){const seal=state.seals[i];seal.life-=dt;if(Math.hypot(g.player.x-seal.x,g.player.y-seal.y)<=COURT.sealRadius){courtFeatClaim(g,seal.serial,seal.fallenAt);state.stats.seals++;bonus(g,COURT.sealBonus);g.sound('achievement');state.seals.splice(i,1);}else if(seal.life<=0){state.stats.lost++;state.seals.splice(i,1);}}}


export function courtProgress(g:Game,finished=false){if(!g.court)return {values:{},best:{},metrics:{}};const s=g.court.stats,clear=finished&&g.court.cleared?1:0,fast=clear&&g.time<=720?1:0,swift=clear&&g.time<=600?1:0;
 const values={courtCaptains:s.captains,courtGuards:s.guards,courtClears:clear,courtColossusClears:clear&&g.court.colossus.status==='defeated'?1:0};
 const best={courtGuardRun:s.guards,courtCloseClear:clear?s.close:0,courtFastClear:fast,courtSwiftClear:swift,courtHasteClear:clear&&upgradeRank(g,'haste')===3?1:0,courtTempoClear:clear&&upgradeRank(g,'tempo')===3?1:0,courtDurationClear:clear&&upgradeRank(g,'duration')===3?1:0};
 return {values,best,metrics:{courtCaptains:s.captains,courtGuards:s.guards,courtClear:clear,courtFast:fast,courtImpact:s.impacts}};
}

export const courtElapsedSeconds=(time:number)=>Math.max(0,Math.ceil(time-1e-7));
export const courtCombatLimit=(captains:number)=>COURT.combatPerCaptain*Math.min(COURT.total,captains+1);
export const courtSpeedBonus=(time:number,rules=COURT_RULES)=>{const p=courtScorePolicy(rules);return Math.max(0,Math.round(p.speedMax*(1-Math.max(0,courtElapsedSeconds(time)-p.speedFullAt)/(p.speedZeroAt-p.speedFullAt))));};
export function courtScoreCredit(g:Game,amount:number,objective:boolean){const state=g.court!;if(state.cleared)return 0;if(objective){state.scoring.captain+=amount;return amount;}const limit=courtCombatLimit(state.stats.captains),credited=Math.min(amount,Math.max(0,limit-state.scoring.combat));state.scoring.combat+=credited;if(state.scoring.combat>=limit&&state.scoreLimitedAt!==limit){state.scoreLimitedAt=limit;g.announce('MINION SCORE LIMIT · HUNT THE NEXT CAPTAIN');}return credited;}

// Clues use game time, so boon deliberation cannot unlock them or extend a bonus.
// A continuous bearing begins at twelve minutes; route embers arrive after speed score is zero.
export function courtHintTarget(g:Game){const hint=g.court?.hint;if(g.time<COURT.hintStart||g.court?.cleared||!hint)return null;const camp=g.court!.camps[hint.site];if(!camp||camp.slain)return null;return g.enemies.find(e=>e.active&&e.court?.role==='captain'&&e.court.site===hint.site)??camp;}
export function updateCourtHint(g:Game,_dt:number){const state=g.court;if(!state)return;if(g.time<COURT.hintStart||state.cleared){state.hint=null;return;}if(!state.hintAnnounced){state.hintAnnounced=true;g.announce('ASH TRACE · A BEARING TO THE NEXT CAPTAIN');}const current=state.hint&&state.camps[state.hint.site];if(current&&!current.slain){state.hint!.life=1;state.hint!.trail=g.time>=COURT.hintTrail;return;}let site=-1,distance=Infinity;state.camps.forEach((c,i)=>{if(c.slain)return;const d=Math.hypot(c.x-g.player.x,c.y-g.player.y);if(d<distance){site=i;distance=d;}});state.hint=site<0?null:{site,life:1,trail:g.time>=COURT.hintTrail};state.nextHintAt=g.time;}

export function courtHintPath(g:Game){const target=courtHintTarget(g);if(!target)return [];const points=[],p={x:g.player.x,y:g.player.y},count=g.court!.hint!.trail?5:1;for(let i=0;i<count;i++){const distance=Math.hypot(target.x-p.x,target.y-p.y);if(distance<90)break;const next=courtWaypoint(p.x,p.y,target.x,target.y),n=Math.hypot(next.x-p.x,next.y-p.y);if(n<.01)break;const dir={x:(next.x-p.x)/n,y:(next.y-p.y)/n},step=Math.min(i===0?110:140,distance-40,n);p.x+=dir.x*step;p.y+=dir.y*step;slideCourt(p,25);points.push({x:p.x,y:p.y,angle:Math.atan2(dir.y,dir.x)});}return points;}

// The edge compass gives the captain's true bearing, independent of route turns.
export function courtHintMarker(g:Game,width:number,height:number,viewWidth:number,_points:{angle:number}[]=[]){const target=courtHintTarget(g);if(!target)return null;const dx=target.x-g.player.x,dy=target.y-g.player.y;return {x:(width+viewWidth)/2-95,y:height/2+20,angle:Math.atan2(dy,dx),direction:Math.hypot(dx,dy)<1?'HERE':(dy<-Math.abs(dx)*.414?'N':dy>Math.abs(dx)*.414?'S':'')+(dx<-Math.abs(dy)*.414?'W':dx>Math.abs(dy)*.414?'E':'')};}
