import {claimRelic,equipRelic,restoreNativePower,realmTraits,powerNature,nearClearedShrine} from './stage-three.ts';
import {MONSTERS,abilityLabel,ABILITIES} from './content-monsters.ts';
import {REALM_GROTTOS} from './titan-realm-map.ts';
import type {Game} from './simulation.ts';
export function mountRealmRelics(getGame:()=>Game|null,pause:(value:boolean)=>void,changed:()=>Promise<void>,sound:()=>void){
 const root=document.getElementById('realmRelics')!,inventory=document.getElementById('relicInventory')!,slots=document.getElementById('relicSlots')!,trigger=document.getElementById('realmInteract')!;let selected='',busy=false,needsArtwork=false;
 async function prepareChange(){busy=true;needsArtwork=true;const close=document.getElementById('closeRelics') as HTMLButtonElement,status=document.getElementById('relicArtStatus')!,retry=document.getElementById('retryRelicArt') as HTMLButtonElement;close.disabled=true;retry.hidden=true;status.hidden=false;status.textContent='Preparing power…';try{await changed();needsArtwork=false;status.hidden=true;render();}catch(error){status.textContent=String(error);retry.hidden=false;}finally{busy=false;close.disabled=needsArtwork;}}
 document.getElementById('retryRelicArt')!.onclick=()=>{if(!busy)void prepareChange();};
 function render(){const g=getGame();if(!g?.realm)return;const spot=nearClearedShrine(g);document.getElementById('relicHeading')!.textContent=(spot?REALM_GROTTOS[spot.id].name:'')+' Grotto';slots.replaceChildren();inventory.replaceChildren();
  for(const [i,p] of g.powers.entries()){const card=document.createElement('div'),button=document.createElement('button'),restore=document.createElement('button');card.className='relic-slot';button.type=restore.type='button';button.dataset.relicSlot=String(i);button.textContent=(i+1)+' · '+abilityLabel(p)+' · '+MONSTERS[powerNature(g,i)].archetype;button.disabled=!selected;button.onclick=async()=>{if(busy)return;if(equipRelic(g,selected,i)){sound();selected='';await prepareChange();}};restore.textContent='Restore native power';restore.className='small';restore.onclick=async()=>{if(busy)return;if(restoreNativePower(g,i)){sound();selected='';await prepareChange();}};card.append(button,restore);slots.append(card);}
  for(const relic of g.realm.relics.filter(r=>r.known)){const button=document.createElement('button'),image=document.createElement('img'),name=document.createElement('b'),description=document.createElement('span');button.type='button';button.dataset.relic=relic.id;const home=spot?.id===relic.shrine;button.disabled=!home||g.powers.some(p=>p.id===relic.ability);button.title=!home?'Return to '+REALM_GROTTOS[relic.shrine].name+' Grotto':button.disabled?'Already equipped':'';button.setAttribute('aria-pressed',String(selected===relic.id));image.src='assets/stage3/relic-'+relic.nature+'.webp';image.alt='';name.textContent=MONSTERS[relic.nature].archetype+' · '+abilityLabel(ABILITIES[relic.ability]);description.textContent=!home?'Equip at '+REALM_GROTTOS[relic.shrine].name+' Grotto':ABILITIES[relic.ability].description;button.append(image,name,description);button.onclick=()=>{sound();selected=relic.id;render();slots.querySelector<HTMLButtonElement>('button')?.focus();};inventory.append(button);}
  const traits=document.getElementById('relicTraits')!;traits.replaceChildren();for(const trait of realmTraits(g)){const line=document.createElement('details'),title=document.createElement('summary'),description=document.createElement('p');title.textContent=trait.name;description.textContent=trait.description;line.append(title,description);traits.append(line);}
 }
 function close(){if(busy||needsArtwork)return;root.hidden=true;selected='';pause(false);}
 trigger.onclick=()=>{const g=getGame();if(!g?.realm||g.ended)return;const spot=nearClearedShrine(g);if(!spot)return;claimRelic(g,spot.id);pause(true);root.hidden=false;selected='';render();document.getElementById('closeRelics')!.focus();};document.getElementById('closeRelics')!.onclick=close;root.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();close();}});
 return {close,update(){const g=getGame(),spot=g?.realm?nearClearedShrine(g):null;trigger.hidden=!root.hidden||!g?.realm||g.ended||!spot;trigger.textContent=spot&&!g!.realm!.shrines[spot.id].claimed?'INSPECT MYSTERIOUS RELIC':'REARRANGE RELICS';}};
}
