import {realmInscription} from './realm-guidance.ts';
import {claimRelic,equipRelic,restoreNativePower,realmTraits,powerNature,nearClearedShrine,localRelic,teleportRealm,nearbyRealmClue,readRealmClue} from './stage-three.ts';
import {MONSTERS,abilityLabel,ABILITIES,abilitiesForStage} from './content-monsters.ts';
import {REALM_GROTTOS} from './titan-realm-map.ts';
import type {Game} from './simulation.ts';
export function mountRealmRelics(getGame:()=>Game|null,pause:(value:boolean)=>void,changed:()=>Promise<void>,sound:()=>void){
 const root=document.getElementById('realmRelics')!,inventory=document.getElementById('relicInventory')!,slots=document.getElementById('relicSlots')!,trigger=document.getElementById('realmInteract')!,portals=document.getElementById('realmPortals')!,advice=document.getElementById('relicCouncil')!;let selected='',busy=false,needsArtwork=false,clue=-1;
 async function prepareChange(){busy=true;needsArtwork=true;const close=document.getElementById('closeRelics') as HTMLButtonElement,status=document.getElementById('relicArtStatus')!,retry=document.getElementById('retryRelicArt') as HTMLButtonElement;close.disabled=true;retry.hidden=true;status.hidden=false;status.textContent='Preparing power…';try{await changed();needsArtwork=false;status.hidden=true;render();}catch(error){status.textContent=String(error);retry.hidden=false;}finally{busy=false;close.disabled=needsArtwork;}}
 document.getElementById('retryRelicArt')!.onclick=()=>{if(!busy)void prepareChange();};
 function render(){const g=getGame();if(!g?.realm)return;const spot=nearClearedShrine(g);slots.replaceChildren();inventory.replaceChildren();portals.replaceChildren();document.getElementById('relicTraits')!.replaceChildren();document.getElementById('localRelicHeading')!.hidden=clue>=0;document.getElementById('portalHeading')!.hidden=clue>=0;
  if(clue>=0){document.getElementById('relicHeading')!.textContent=['First','Second','Third','Fourth'][clue]+' inscription';advice.textContent=realmInscription(g.realm.relics,g.realm.pattern[clue]);return;}
  document.getElementById('relicHeading')!.textContent=(spot?REALM_GROTTOS[spot.id].name:'')+' Grotto';advice.textContent='Take the relic into one power slot. The power you leave behind stays here. Keep a native power until the guardians are defeated. Leaving the titan’s seal restores its defenses.';
  if(!spot)return;const relic=localRelic(g,spot.id);
  for(const [i,p] of g.powers.entries()){const card=document.createElement('div'),button=document.createElement('button'),restore=document.createElement('button');card.className='relic-slot';button.type=restore.type='button';button.dataset.relicSlot=String(i);button.textContent=(i+1)+' · '+abilityLabel(p)+' · '+MONSTERS[powerNature(g,i)].archetype;button.disabled=!selected;button.onclick=async()=>{if(busy)return;if(equipRelic(g,selected,i)){sound();selected='';await prepareChange();slots.querySelector<HTMLButtonElement>('button:not(:disabled)')?.focus();}};restore.textContent='Restore native power';restore.className='small';restore.disabled=!!relic||p.id===abilitiesForStage(g.monster.id,g.phase,g.titanKit)[i].id&&!g.realm.relics.some(r=>r.shrine===null&&r.ability===p.id);restore.title=relic?'Restore at an empty altar to leave your borrowed relic there':'';restore.onclick=async()=>{if(busy)return;if(restoreNativePower(g,i)){sound();selected='';await prepareChange();}};card.append(button,restore);slots.append(card);}
  if(relic){const button=document.createElement('button'),image=document.createElement('img'),name=document.createElement('b'),description=document.createElement('span');button.type='button';button.dataset.relic=relic.id;button.setAttribute('aria-pressed',String(selected===relic.id));image.src='assets/stage3/relic-'+relic.nature+'.webp';image.alt='';name.textContent=MONSTERS[relic.nature].archetype+' · '+abilityLabel(ABILITIES[relic.ability]);description.textContent=ABILITIES[relic.ability].description;button.append(image,name,description);button.onclick=()=>{sound();selected=relic.id;render();slots.querySelector<HTMLButtonElement>('button:not(:disabled)')?.focus();};inventory.append(button);}else inventory.textContent='This altar is empty. Restore a native power to leave a borrowed relic here.';
  for(const destination of g.realm.shrines.filter(s=>s.claimed&&s.id!==spot.id)){const button=document.createElement('button');button.type='button';button.dataset.realmTeleport=String(destination.id);button.textContent=REALM_GROTTOS[destination.id].name+(destination.occupied?' · Occupied':' · Teleport');button.disabled=destination.occupied;button.onclick=()=>{if(busy||!teleportRealm(g,destination.id))return;sound();close();};portals.append(button);}if(!portals.children.length)portals.textContent='Awaken another altar to connect its portal.';
  for(const trait of realmTraits(g)){const line=document.createElement('details'),title=document.createElement('summary'),description=document.createElement('p');title.textContent=trait.name;description.textContent=trait.description;line.append(title,description);document.getElementById('relicTraits')!.append(line);}
 }
 function close(){if(busy||needsArtwork)return;root.hidden=true;selected='';clue=-1;pause(false);}
 function interact(){const g=getGame();if(!root.hidden||!g?.realm||g.ended)return false;const index=nearbyRealmClue(g),spot=nearClearedShrine(g);if(index<0&&!spot)return false;if(index>=0){if(!readRealmClue(g,index))return false;clue=index;}else{if(!claimRelic(g,spot!.id))return false;clue=-1;}pause(true);root.hidden=false;selected='';render();(inventory.querySelector('button')||document.getElementById('closeRelics'))?.focus();return true;}
 trigger.onclick=interact;document.getElementById('closeRelics')!.onclick=close;
 root.tabIndex=-1;
 function keyboard(e:KeyboardEvent){if(root.hidden)return false;e.stopPropagation();if(e.key==='Escape'){e.preventDefault();close();return true;}const choices=[...root.querySelectorAll<HTMLButtonElement>('button:not(:disabled):not([hidden])')].filter(b=>b.offsetParent!==null);if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const i=choices.indexOf(document.activeElement as HTMLButtonElement),d=e.key==='ArrowUp'||e.key==='ArrowLeft'?-1:1;choices[(i+d+choices.length)%choices.length]?.focus();return true;}if(e.key===' '||e.key==='Enter'){e.preventDefault();if(!e.repeat){const focused=document.activeElement as HTMLButtonElement;if(choices.includes(focused))focused.click();else choices[0]?.focus();}return true;}return true;}
 root.addEventListener('keydown',keyboard);root.addEventListener('keyup',e=>{e.stopPropagation();if(e.key===' '||e.key==='Enter')e.preventDefault();});
 return {close,interact,keyboard,update(){const g=getGame(),spot=g?.realm?nearClearedShrine(g):null,index=g?.realm?nearbyRealmClue(g):-1;trigger.hidden=!root.hidden||!g?.realm||g.ended||g.realm.engaged||(!spot&&index<0);trigger.textContent=index>=0?'READ INSCRIPTION · SPACE':spot&&!g!.realm!.shrines[spot.id].claimed?'INSPECT MYSTERIOUS RELIC · SPACE':'RELIC / TELEPORT · SPACE';}};
}
