import {BUILD_VERSION} from './config.ts';
import {tintLayer} from './assets.ts';
import {REALM_GROTTOS,REALM_RING,REALM_CLUES} from './titan-realm-map.ts';
import type {Game,Enemy} from './simulation.ts';
const IDS=['portal','sealed-gate','warning','landing','titan-body','titan-head-0','titan-head-1','titan-head-2','titan-mantle-0','titan-mantle-1','guardian','acolyte','shardhound','guardian-sentinel','guardian-seer','guardian-beast','servant-thrall','servant-wing','boundary','slam','bolt','breach',...['unknown','overlord','calamity','devourer','titan','sovereign','reaper','lycanthrope','dormant'].map(n=>'relic-'+n)];
export class TitanRealmArt{
 images=new Map<string,HTMLImageElement>();private pending:Promise<void>|null=null;private appearance='';private titan:HTMLCanvasElement|null=null;private servants:HTMLCanvasElement[]=[];
 async prepare(){return this.pending??=Promise.all(IDS.map(async id=>{const response=await fetch('assets/stage3/'+id+'.webp?v='+BUILD_VERSION,{signal:AbortSignal.timeout(12000)});if(!response.ok)throw Error('Titan realm artwork could not load');const url=URL.createObjectURL(await response.blob());try{const image=new Image();image.src=url;let timer:ReturnType<typeof setTimeout>|undefined;try{await Promise.race([image.decode(),new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(Error('Titan realm artwork could not decode')),8000);})]);}finally{clearTimeout(timer);}this.images.set(id,image);}finally{URL.revokeObjectURL(url);}})).then(()=>{}).catch(error=>{this.pending=null;throw error;});}
 private compose(g:Game){const a=g.realm!.appearance,key=JSON.stringify(a);if(this.appearance===key)return;this.appearance=key;const c=document.createElement('canvas');c.width=512;c.height=640;const ctx=c.getContext('2d')!,body=tintLayer(this.images.get('titan-body')!,512,512,a.body),mantle=tintLayer(this.images.get('titan-mantle-'+a.mantle)!,512,512,a.body),head=tintLayer(this.images.get('titan-head-'+a.head)!,512,512,a.power);ctx.drawImage(mantle,18,80,476,300);ctx.drawImage(body,0,112,512,512);ctx.drawImage(head,160,26,192,192);this.titan=c;this.servants=['guardian','acolyte','shardhound','servant-wing','servant-thrall'].map(id=>tintLayer(this.images.get(id)!,384,384,a.body));}
 image(c:CanvasRenderingContext2D,id:string,x:number,y:number,size:number,angle=0,alpha=1){const image=this.images.get(id);if(!image)return;c.save();c.globalAlpha*=alpha;c.translate(x,y);c.rotate(angle);c.drawImage(image,-size/2,-size/2,size,size);c.restore();}
 drawEnvironment(c:CanvasRenderingContext2D,g:Game,time:number){const s=g.realm!;this.compose(g);this.image(c,'boundary',0,-38,REALM_RING*2.12,0,s.engaged?.46:.26);
  for(const v of [-1536,0,1536]){this.image(c,'sealed-gate',v,-1970,280);this.image(c,'sealed-gate',v,1950,280);this.image(c,'sealed-gate',-1973,v,280,Math.PI/2);this.image(c,'sealed-gate',1973,v,280,Math.PI/2);}
  for(const shrine of s.shrines){const p=REALM_GROTTOS[shrine.id],local=s.relics.find(r=>r.shrine===shrine.id);this.image(c,'relic-'+shrine.decor,p.x,p.y-300+Math.sin(time*2+shrine.id)*3,shrine.decor==='unknown'?108:180,0,shrine.cleared?1:.65);if(local&&!local.known)this.image(c,'relic-'+local.nature,p.x+150,p.y-165,80,0,.85);if(shrine.claimed){this.image(c,'portal',p.x,p.y-150,180,0,shrine.occupied?.28:.9);if(shrine.occupied){c.save();c.font='bold 13px Arial';c.textAlign='center';c.fillStyle='#ffd4c1';c.strokeStyle='#100b19';c.lineWidth=4;c.strokeText('OCCUPIED',p.x,p.y-245);c.fillText('OCCUPIED',p.x,p.y-245);c.restore();}}}
  for(const [i,q] of REALM_CLUES.entries()){this.image(c,'relic-'+s.pattern[i],q.x,q.y-35,90,0,.95);c.save();c.font='bold 13px Georgia';c.fillStyle='#eee8ff';c.textAlign='center';c.strokeStyle='#100b19';c.lineWidth=4;const label=['I','II','III','IV'][i]+' · INSCRIPTION';c.strokeText(label,q.x,q.y+35);c.fillText(label,q.x,q.y+35);c.restore();}
  for(const z of s.zones){if(z.warning<=0)continue;this.image(c,'warning',z.x,z.y,z.radius*2.1,0,.7+Math.max(0,1-z.warning/1.55)*.3);}
 }

 drawDefense(c:CanvasRenderingContext2D,g:Game){const s=g.realm!,boss=s.boss;if(!boss?.active||s.open)return;c.save();c.shadowColor='#0b0612';c.shadowBlur=8;this.image(c,'relic-'+s.pattern[s.layer],boss.x+170,boss.y-175,80,0,1);c.font='bold 10px Arial';c.textAlign='center';c.fillStyle='#f5e8ff';c.strokeStyle='#0b0612';c.lineWidth=4;c.strokeText('DEFENDED',boss.x+170,boss.y-122);c.fillText('DEFENDED',boss.x+170,boss.y-122);c.restore();}
 drawEnemy(c:CanvasRenderingContext2D,g:Game,e:Enemy,time:number){this.compose(g);const u=e.realm!;if(u.role==='boss'){c.drawImage(this.titan!,e.x-160,e.y-340+Math.sin(time*1.6)*2,320,400);if(e.flash>0)this.image(c,'breach',e.x,e.y-90,220,0,e.flash*6);}else{const size=u.role==='guardian'?(u.variant===0?175:145):u.variant===0?75:60;const image=u.role==='guardian'?this.images.get(['guardian-sentinel','guardian-seer','guardian-beast'][u.variant])!:this.servants[u.variant];c.drawImage(image,e.x-size/2,e.y-size*(u.role==='guardian'?.88:.8)+Math.sin(time*5+e.serial),size,size);if(u.role==='guardian'){const exposed=(u.exposedUntil||0)>g.time;c.save();c.font='bold 11px Arial';c.textAlign='center';c.strokeStyle='#100b19';c.lineWidth=4;c.fillStyle=exposed?'#ffe1ad':'#9fe4ff';const label=exposed?'EXPOSED':'NATIVE POWER WARD';c.strokeText(label,e.x,e.y-size*.9-10);c.fillText(label,e.x,e.y-size*.9-10);if(e.windup>0)this.image(c,'slam',e.x,e.y,340,0,.7);c.restore();}if(u.marked)this.image(c,'breach',e.x,e.y,55,0,.3);if(u.hintNature&&!u.marked)this.image(c,'relic-'+u.hintNature,e.x,e.y-38,28,0,.72);if(e.flash>0)this.image(c,'breach',e.x,e.y,size,0,.65);}if(e.hp<e.maxHp||u.role==='boss'){const w=u.role==='boss'?180:60;c.fillStyle='#100b19';c.fillRect(e.x-w/2,e.y-(u.role==='boss'?350:u.role==='guardian'?190:68),w,5);c.fillStyle=g.realm!.appearance.power;c.fillRect(e.x-w/2,e.y-(u.role==='boss'?350:u.role==='guardian'?190:68),w*Math.max(0,e.hp/e.maxHp),5);}}
}
