import {runOutcome} from './results.ts';
import {EVENT,PHASES} from './data.ts';
import {MONSTERS} from './content-monsters.ts';
import {decodeRun} from './run-code.ts';
import {RELEASES} from './unbound.ts';
const $=(id:string)=>document.getElementById(id)!;
const fmt=(seconds:number)=>Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0');
function row(label:string,value:string){const div=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;div.append(dt,dd);$('output').append(div);}
$('verify').onclick=async()=>{const status=$('status'),out=$('output'),details=$('technical');out.replaceChildren();out.hidden=true;details.hidden=true;try{const run=await decodeRun(($('code') as HTMLTextAreaElement).value);status.textContent='VALID MONSTER MASH RUN CODE · '+(run.version===4?'Authenticated':'Checksum valid')+(run.rules!==EVENT.rules?' · HISTORICAL RULESET':'');status.style.color='#a6e9c3';row('MONSTER NAME',run.name);row('TITLE',run.title||'—');row('CHAMPION / ARCHETYPE',MONSTERS[run.monsterId||'sovereign']?.archetype||'Legacy Sovereign');row('EVENT WEEK / SCENARIO','Week '+(run.phase+1)+' · '+PHASES[run.phase].name);row('RUN ENDING',run.reason==='retired'?'Practice / manually ended':'Overwhelmed');row('REIGN MILESTONE',runOutcome(run));row('COMPARISON','Compare the same champion, week, ruleset and ending category.');row('DOMINANCE',run.score.toLocaleString());row('BODY COUNT',run.kills.toLocaleString());row('WAVE',String(run.wave));row('SURVIVAL TIME',fmt(run.duration));row('ELITE KILLS',run.elites.toLocaleString());row('TITAN KILLS',run.titans.toLocaleString());row('PEAK CARNAGE','×'+run.peak);row('FINAL RELEASE STAGE',run.release===undefined?'Not recorded in legacy code':RELEASES[run.release].name);row('RULESET VERSION',run.rules+(run.rules===EVENT.rules?' · current':' · historical'));row('COMPLETION DATE',new Date(run.ended).toLocaleString());row('CODE FORMAT','MM'+run.version);if(run.build)row('BUILD ID',run.build);out.hidden=false;details.hidden=false;$('raw').textContent=JSON.stringify(run,null,2);}catch(e){status.textContent='INVALID / MODIFIED RUN CODE · '+(e instanceof Error?e.message:'Unable to decode');status.style.color='#ff918b';}};
