import {runOutcome} from './results.ts';
import {EVENT,PHASES} from './data.ts';
import {rulesForStage} from './stage-two.ts';
import {courtSummary} from './results.ts';
import {MONSTERS} from './content-monsters.ts';
import {decodeRun} from './run-code.ts';
import {RELEASES} from './unbound.ts';
const $=(id:string)=>document.getElementById(id)!;
const fmt=(seconds:number)=>Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0');
function row(label:string,value:string){const div=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;div.append(dt,dd);$('output').append(div);}
$('verify').onclick=async()=>{const status=$('status'),out=$('output'),details=$('technical');out.replaceChildren();out.hidden=true;details.hidden=true;try{const run=await decodeRun(($('code') as HTMLTextAreaElement).value);status.textContent='VALID MONSTER MASH RUN CODE · '+(run.version===4?'Authenticated':'Checksum valid')+(!run.testing&&run.rules!==rulesForStage(run.phase)?' · HISTORICAL RULESET':'');if(run.testing)status.textContent+=' · STAGE 2 PLAYTEST / NOT COMPETITION';status.style.color='#a6e9c3';if(run.court)row('COURT HUNTS',courtSummary(run));row('MONSTER NAME',run.name);row('TITLE',run.title||'—');row('CHAMPION / ARCHETYPE',MONSTERS[run.monsterId||'sovereign']?.archetype||'Legacy Sovereign');row('EVENT STAGE / SCENARIO','Stage '+(run.phase+1)+' · '+PHASES[run.phase].name);row('RUN ENDING',run.reason==='cleared'?'Mission cleared':run.reason==='retired'?'Practice / manually ended':'Overwhelmed');row('REIGN MILESTONE',runOutcome(run));row('COMPARISON','Compare the same champion, stage, ruleset and ending category.');row('DOMINANCE',run.score.toLocaleString());if(run.mission?.scoring){row('MINION / COMBAT SCORE',run.mission.scoring.combat.toLocaleString());row('CAPTAIN SCORE',run.mission.scoring.captain.toLocaleString());row('HUNT OBJECTIVE BONUS',run.court!.bonus.toLocaleString());row('CLEAR SPEED BONUS',run.mission.scoring.speed.toLocaleString());if(run.mission.colossus)row('ASHEN COLOSSUS',run.mission.colossus.reward?'Slain · +'+run.mission.colossus.reward.toLocaleString():'Not slain');}row('BODY COUNT',run.kills.toLocaleString());row('WAVE',String(run.wave));row('SURVIVAL TIME',fmt(run.duration));row('ELITE KILLS',run.elites.toLocaleString());row('TITAN KILLS',run.titans.toLocaleString());row('PEAK CARNAGE','×'+run.peak);row(run.mission?'HUNT EVOLUTION':'FINAL RELEASE STAGE',run.release===undefined?'Not recorded in legacy code':RELEASES[run.release].name);row('RULESET VERSION',run.rules+(run.testing?' · Stage 2 playtest':run.rules===rulesForStage(run.phase)?' · current':' · historical'));row('COMPLETION DATE',new Date(run.ended).toLocaleString());row('CODE FORMAT','MM'+run.version);if(run.build)row('BUILD ID',run.build);out.hidden=false;details.hidden=false;$('raw').textContent=JSON.stringify(run,null,2);}catch(e){status.textContent='INVALID / MODIFIED RUN CODE · '+(e instanceof Error?e.message:'Unable to decode');status.style.color='#ff918b';}};
